### ISSUE TITLE
Issue with canvas-prebuilt in version 3.0.3

### ISSUE THREAD

**Issue by abudaan** [vega/vega#1024]
See https://github.com/vega/vega-scenegraph/issues/55

Probably not a Vega issue but an issue in canvas-prebuilt

**Comment by jheer** [comment]
Thanks! The problem was that Vega's package.json was missing `"browser": {"canvas-prebuilt": false}` to ensure exclusion of the package when bundling for the web. (The vega-scenegraph and vega-wordcloud modules were properly configured, but this detail was erroneously left out of the main vega repo.) I've fixed the issue and released v3.0.4.
