### ISSUE TITLE
view.data returns vega_id Symbol

### ISSUE THREAD

**Issue by Lacroute** [vega/vega#1028]
Hi,

I'm using this specification : https://vega.github.io/vega/tutorials/bar-chart/bar-chart-axes.vg.json

I want to update the full dataset of my spec. So first, I generate my new dataset:
```
let updated = view.data('table').map(row => {
  row.amount = parseInt(Math.random() * 100)
  return row
})
```

Then I change the dataset with the new one:
```
view.change('table', changeset().remove(d => d).insert(updated)).run()
```

But it doesn't work because of the vega_id Symbol is passed to the `row` object and I suppose it troubles the renderer. In order to generate a newdataset, I have to do:
```
let updated = view.data('table').map(row => {
  row.amount = parseInt(Math.random() * 100)
  return {category: row.category, amount: row.amount}
})
```

Is there a better way to update existing values of a dataset?

Thanks

**Comment by jheer** [comment]
It looks like the major issue here is that you are removing and adding the same data points, which makes the marks disappear when I try to replicate the issue. Instead, you can use the changeset `modify` method, like so:

```js
view.change('table', vega.changeset()
    .modify(vega.truthy, 'amount', (d) => parseInt(Math.random() * 100)))
    .run()
```

This modifies all tuples (indicated by the initial `truthy` argument), updating the amount field to the value returned by the given function.

Also, you will need to update the spec so that the `y` and `y2` encoding properties of the `rect` marks are in the `update` set rather than the `enter` set.

**Comment by Lacroute** [comment]
Thanks for the tips, `modify` and changeSet's `methods` aren't clear in the doc, modify is what I was looking for.
