### ISSUE TITLE
Rotate transform

### ISSUE THREAD

**Issue by hadley** [vega/vega#105]
It would be useful to have a transform that "rotates" the data, so you could send column oriented data like:

```
{"a": [1, 2, 3], "b": [4, 5, 6]}
```

and have it converted to:

```
[{"a": 1, "b": 4}, {"a":2, "b": 5}, {"a": 3, "b": 6}]
```

this would reduce the size of the vega spec (esp. datasets with many rows) and would be much easier (and faster) to generate from R.

**Comment by djouallah** [comment]
@marcprux do you know of any javascript library that do that, my inline data is nearly doubled because of that format.

**Comment by marcprux** [comment]
The way I reduce the size of the data (at the cost of some readability) is to just use bare arrays for the data rows and reference them by index. For example, instead of https://vega.github.io/editor/#/examples/vega/bar-chart :

```json
  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    }
  ],
  …
  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "height"
    }
  ],
```

you can define the data as an array-of-arrays and just reference the field by index (which seems to work, despite not being listed as a valid field format at https://vega.github.io/vega/docs/types/#Field):

```json
  "data": [
    {
      "name": "table",
      "values": [
        ["A", 28],
        ["B", 55],
        ["C", 43],
        ["D", 91],
        ["E", 81],
        ["F", 53],
        ["G", 19],
        ["H", 87]
      ]
    }
  ],
  …
  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "0"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "1"},
      "nice": true,
      "range": "height"
    }
  ]
```

Another possibility is to try the new Apache Arrow loader and store your data in the arrow format: https://github.com/vega/vega-loader-arrow

**Comment by domoritz** [comment]
We do have a flatten transform now https://vega.github.io/vega/docs/transforms/flatten/.

**Comment by domoritz** [comment]
I'm closing this issue since flatten does what you ask for. Let us know if there is anything else.
