### ISSUE TITLE
Matrix - Map interactions

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1094]
I applied a self-organizing map to characteristics describing catchments of European rivers and while I'm quite pleased with the result, I still had some troubles. Firstly the result
![som_eu_catchments](https://user-images.githubusercontent.com/5186265/34080611-7ee41448-e341-11e7-96bb-9aab222cee44.gif)

Complete specification is there: https://vega.github.io/editor/#/gist/vega/mattijn/884fd593a4e63c743b8d332cc1309886

My little troubles down the line:
- In the csv file, I'd to parse all columns explicitly as `number`, as in `auto` mode it detects many columns as `strings`.
- In `canvas` mode the map component sometimes keeps hanging while panning the 'selection-box' in the matrix component (this does not happen in `svg` mode)
- I tried many approaches, but I was not able to get the legend show up below the matrix using the `orient` variable.
- The `title` for the map component is not showing up.
- Once I got a selection box, the hover functionality (black cell outline) doesn't work anymore on the selected cells. 
- I was not able to keep the matrix size fixed and filter the elements in it (see what I mean by sliding `filter_u_matrix` to 0.2)

My future wishes:
- Include crossfilter, by also applying a 'selection-box' in the map component to filter the matrix.
- Include a shift-`click` function on top of the `interval` selection box. 
- To make this in vega-lite 2!

**Comment by jheer** [comment]
Nice! This is a very interesting visualization. Thanks for sharing! Some responses to your issues:

_In the csv file, I'd to parse all columns explicitly as number, as in auto mode it detects many columns as strings._

This is due to the non-standard 'nan' values. You might filter those out as part of your data generation or pre-processing. Blank csv entries (e.g., 1,2,,3) will get mapped to null and ignored by the type inference methods.

_In canvas mode the map component sometimes keeps hanging while panning the 'selection-box' in the matrix component (this does not happen in svg mode)_

I've been unable to replicate this so far. Both renderers are working for me, and I'm noticing what appears to be slightly faster updates with the canvas renderer. I'm on a 2017 MacBook Pro running Chrome.


_I tried many approaches, but I was not able to get the legend show up below the matrix using the orient variable._

It looks like you set the legend orientation default in the config block. If I change the setting to `"orient": "bottom"` it works for me. The tricky bit is that hybrid settings such as `"bottom-left"` (which are intended to place legends *within* the data rectangle) are defined relative to the defined width/height of the enclosing component; in this case both are zero! The other values (top, left, bottom, right) are determined relative to the computed bounds and so work regardless.

_The title for the map component is not showing up._

It appears the map title is getting clipped by the `"clip": {"value": true}` setting for the map group.

_Once I got a selection box, the hover functionality (black cell outline) doesn't work anymore on the selected cells._

I didn't check closely, but I suspect your brush component is consuming the input events and so the black box hover highlights are never triggered.

_I was not able to keep the matrix size fixed and filter the elements in it (see what I mean by sliding filter_u_matrix to 0.2)_

To keep the matrix size fixed, you will want the matrix_width and matrix_height signals to stay constant. Similarly, I think you want your matrix_x and matrix_y scales to be calculated over the non-filtered data and then stay constant. To do this, you probably want to create a data source for your unfiltered matrix and use that to set the scales and sizing signals. Then, filter your matrix data in a derived data source that drives the visual encodings.
