### ISSUE TITLE
Array domains smaller than data domain break rendering

### ISSUE THREAD

**Issue by ericsoco** [vega/vega#1096]
When setting a scale's domain to an array literal with a max value smaller than the max value of the corresponding data domain, the rendered chart gets smaller, as expected.

However, there is a point beyond which the chart stops getting smaller and instead appears to be drawing at zero height, and below the bounds of the chart...and therefore disappears.

This spec offers a simple example:

```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "description": "",
  "width": 800,
  "height": 600,
  "autosize": {
    "type": "fit",
    "contains": "padding"
  },
  "signals": [],
  "data": [
    {
      "name": "dataset",
      "values": [
        {
          "x": 1,
          "y": 0
        },
        {
          "x": 2,
          "y": 100
        },
        {
          "x": 3,
          "y": 300
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": {
        "data": "dataset",
        "field": "x"
      },
      "zero": false,
      "padding": 0.05,
      "round": true,
      "range": "width"
    },
    {
      "name": "y",
      "type": "linear",
      "domain": [0, 170],
      "zero": false,
      "range": "height"
    }
  ],
  "projections": [],
  "axes": [
    {
      "orient": "bottom",
      "scale": "x",
      "title": "x"
    },
    {
      "orient": "left",
      "scale": "y",
      "title": "y"
    }
  ],
  "legends": [],
  "marks": [
    {
      "type": "line",
      "from": {
        "data": "dataset"
      },
      "encode": {
        "enter": {
          "x": {
            "scale": "x",
            "field": "x"
          },
          "y": {
            "scale": "y",
            "field": "y"
          },
          "stroke": {
            "value": "#99CCFF"
          }
        }
      }
    }
  ]
}
```

Setting the max value of the "y" domain to e.g. 155 demonstrates the problem starting to happen; setting it below 150, the chart is drawn completely outside of the chart bounds (and at zero height).

This seems to hold true when the scale's domain max is set to 50% of the data's domain max, so there's probably some obvious math I'm not quite wrapping my head around.

Note that setting `"clip": true` on the mark obviates the problem completely.

**Comment by jheer** [comment]
If values lie outside the given domain, continuous scales indeed will interpolate outside of the provided scale range. This is intended behavior. To prevent it, you can either use clipping (works generally!), delete data points outside the desired domain (works well for scatter plot points but not lines/areas), or use a different scale setting such as `clamp: true` (warning: can distort the data, but might be workable for area marks).

The specific behavior at issue here arises due to the use of `"autosize": "fit"`. This results in a "death spiral" in which Vega attempts to reduce the data rectangle size to fit the requested display. However, as the plotted marks overrun this rectangle size (defined by the width/height signal values), the autosizing ultimately squashes the plotting range down to nothing.

To avoid these issues one might use a different sizing approach (`"autosize": "fit"` can be handy, but can not solve all problems) or use clipping to ensure that the width / height signals accurately capture the spatial range of the plotted data. I'd probably lean towards the latter approach.

**Comment by ericsoco** [comment]
I thought it might have been `autosize`, thanks for the explanation! Good to know about `clamp` as well.
