### ISSUE TITLE
zindex is not documented for marks

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1151]
Several graph examples, e.g. [force](https://vega.github.io/editor/#/examples/vega/force-directed-layout)  and Voronoi use `zindex: 1` as a top mark field. Several others, like graticule, geopath, and geoshape, use `zindex` inside encoding sections. Yet there is no zindex documentaiton on any of the **mark** pages.

**update**:  related question - how `zindex` is different from the mark's `sort` value?

Please add something explaining how it should be used.  Thanks!

**Comment by jheer** [comment]
Hmm, you're right. That is definitely an oversight. Will add.

`zindex` affects painting order, determining what is drawn on top of what. It is useful for making points temporarily pop out to the top when highlighted so that they are not occluded. It is also used at the group level to determine if axes should be drawn above or below the marks.

`sort` has a similar affect among sibling marks but actually reorders them in the scenegraph data structure itself, not just their rendering order. For line and area marks this determines the order in which points are connected to each other.

**Comment by jheer** [comment]
Updated documentation: `zindex` now included among shared mark properties and visible on all mark type documentation pages.

**Comment by pelotom** [comment]
It looks like, while the `zindex` property which can occur in encoding sets is now documented, there's also a top-level `zindex` property that can occur on the root of the mark itself, e.g. [here](https://vega.github.io/editor/#/examples/vega/force-directed-layout):

```json
  "marks": [
    {
      "name": "nodes",
      "type": "symbol",
      "zindex": 1,
      ...
```

I'm actually not sure what this does. I was hoping it would cause one type of mark to be drawn on top of all instances of another type of mark. For example, I'm making a multi-line time series and want it to turn into an area when I hover over any of the lines, and the areas should always be drawn over the lines. It doesn't seem possible to do with the `zindex` encoding property, so my hope was that this top-level property would do the trick, but it seems to have had no effect...
