### ISSUE TITLE
Missing "signal" docs for formula transform

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1162]
The `"formulaTransform"` in 3.0.10 schema allows `signal`, `initOnly`, `expr`, and `as`. The [formula docs page](https://vega.github.io/vega/docs/transforms/formula/) only covers the last 3, not the `signal`. What does it do?  Thx!

**Comment by jheer** [comment]
As discussed briefly on https://vega.github.io/vega/docs/transforms/, all transform definitions accept a `signal` property to make the operator value accessible as a named signal. (This property does not otherwise parameterize the transform, it only exposes its internally computed state value.) This is only useful for transforms that generate a value as a side effect, such as `bin` (which computes a binning specification with start, stop and step values) and `extent` (which computes min/max extents).

The `formula` transform's operator value is always `null`, so there is no value to using the signal property with it. Hence no documentation on the formula page.
