### ISSUE TITLE
Svg event when cursor left svg

### ISSUE THREAD

**Issue by Muskos** [vega/vega#1172]
You can try it on 
https://vega.github.io/editor/#/examples/vega/budget-forecasts

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1798651/36842165-cb0bebd0-1d5b-11e8-8a9b-728dd0c757a9.gif)

1. Mousedown on triangle. 
2. Move it out from window (svg element). 
3. Mouseup
4. Try to hover any element in svg. There is no hover effect. 

Did you see it? Maybe you know decision?

**Comment by jheer** [comment]
Thanks! I note the same issue with the canvas renderer. Turns out the problem is not with Vega itself, but with how this example has been written. The signal `dragging` should reset not on `"mouseup"` (which is specific to the canvas or SVG element) but on `"window:mouseup"` (triggered from anywhere).

I will update the examples in the Vega repo accordingly, and these will eventually propagate to the editor as well!

**Comment by Muskos** [comment]
@jheer 

> The signal dragging should reset not on "mouseup" (which is specific to the canvas or SVG element) but on "window:mouseup" (triggered from anywhere)

Thanks. It's helped for me too!
