### ISSUE TITLE
autosize fit-x results in height === 0 thus no visible grid

### ISSUE THREAD

**Issue by benib** [vega/vega#1193]
If `autosize.type` is set to `fit-x`, the `height` seems to stay `0` thus the grid on a bottom or top axis is not visible (the grid lines are rendered but their y2 value is 0).

The result is different if the height would get set here: https://github.com/vega/vega-view-transforms/blob/master/src/ViewLayout.js#L409. But I am pretty sure that is not the correct thing to do.

I have not enough understanding of how exactly `viewHeight` and `height` are used throughout at the moment. If you could provide me with some pointers I could try to come up with a PR.

See this chart as an example: https://vega.github.io/editor/#/gist/vega/benib/6d142b61881211b7e7388d2666b19de1/8c782c9107c3789ac3b4c9ed37f3ed759e303978/vegaspec.json
As soon as a fixed `height` is set, the grid is visible.

A workaround could be to calculate the height signal probably, but that's exactly what should be obsolet when using `fit-x` as far as I understand.

Happy to help with anything. Please advise.

**Comment by jheer** [comment]
For standard charts with a rectangular plotting area (bar charts, scatter plots, etc) there *must* be a basic height setting. This is true regardless of `fit-x` or any other autosize property. Otherwise Vega has no idea what the vertical scale range should be!

(In the case of `fit` autosizing Vega may reduce the range such that the total chart size fits the specified size. In the case of `pad` autosizing Vega may grow the total chart size while keeping the provided range extent constant. Either way, a starting width or height value is needed.)

You are still seeing bars in the provided example because you are using a `groupHeight` signal value to drive the layout, and the autosize method is then padding the total chart size in response to the bounds of these groups. Nevertheless, the top-level `height` signal value (which the x-axis depends on for gridline layout) is still zero, having never been set.

In this example, you can set the top-level `height` signal dynamically by adding the following definition:

```json
    {
      "name": "height",
      "update": "span(range('yScale'))"
    }
```
