### ISSUE TITLE
Expression parse error

### ISSUE THREAD

**Issue by MD65** [vega/vega#1290]
Hello, 

I have a question about  "Expression parse error". Can I get some help ? 
**This is the code witch makes mistake**

 "transform": [
        {"type": "filter",
         "expr": "datum._source['srcIp'] != ip "}
      ]
**Accessing Object Values:** 
VEGA_DEBUG.view.data("nsg")[0].hits.hits[0]._source.srcIp

**The type of  srcIp** is a string

**I have already tried** 
 "expr": "parent[0].hits.hits[datum]._source.srcIp != ip "

**Comment by MD65** [comment]
It ok now, I find a another way, but I don't know yet the good expression.  

However, I have a other error

_Cannot read property 'match' of undefined_*

 {"name":"source_ip",
      "url":{
          "%context%": true,
          "%timefield%": "@timestamp",
           "index": "logstash-*",
           "body":{"size": 10000 , "_source": ["srcIp"]} 
          },
      "transform": [
            {
            "type": "countpattern",
            "field": "source_ip", 
            // "case": "upper",
            },
          {
            "type": "formula", "as": "angle",
            "expr": "[-45, 0, 45][~~(random() * 3)]"
          },
          {
            "type": "formula", "as": "weight",
            "expr": "if(datum.text=='10.201.73.7', 600, 300)"
          }
      ]
          }

**Comment by jheer** [comment]
This is a help request, not a Vega issue. Given the non-standard dataset definition this also seems to pertain to the Kibana plug-in, which we do not support directly here at the Vega repo. If there is a dedication Kibana/Vega help forum I recommend posting there! Otherwise, you might try posting to the Vega mailing list: https://groups.google.com/forum/#!forum/vega-js

As for your original post, I don't know why your expression is failing, but it may be due to the use of the identified `ip`, which would need to be a defined signal in order to be referenced in an expression. If you want to compare to a string value, be sure to put it in quotes (`'ip'` vs. `ip`).

**Comment by MD65** [comment]
I am sorry for this misunderstanding ! It is actually a request. Thanks for your understanding. For the bug it was about a slip of "format": {"property": "hits.hits"}, it ok now. 


And the https://groups.google.com/forum/#!forum/vega-js did not answer me yet, despite of my subscription request.
