### ISSUE TITLE
4.0.0-rc.2: transforms not registered

### ISSUE THREAD

**Issue by ericsoco** [vega/vega#1307]
When instantiating a View in 4.0.0-rc.2 with specs created with v3.3, I ran into the error
`Unrecognized transform type: formula`.

I tracked it down to the fact that the registry exported from `vega-dataflow` (`transforms`) was not being populated correctly on init. Turns out this was because I had an old version of `vega-tooltip` as a project dependency, and it pegged `vega-dataflow` to an older version (`3.0.5` instead of `4.0.0`) in my `yarn.lock` file.

So...just posting in case anyone else runs into this issue.

**Comment by hydrosquall** [comment]
Thanks @ericsoco and @pelotom for leaving notes. I encountered this same issue recently using the combination of `vega-lite@5.0.0` and `vega@5.20.2`. The reason for the issue was exactly as you pointed out: there were multiple copies of `vega-dataflow` being extended.

https://github.com/vega/vega/blob/02d79dddb2850a24abfe6a4ebaf8823548709bb5/packages/vega/index.js#L17-L20

I was able to confirm this by running `yarn why vega-dataflow`, and finding that both `5.7.3` and `5.7.4` were present in my project, and I didn't have a way to get rid of the old one. 

I fixed the issue by adding an entry to my `resolutions` in package.json:

```ts
{
   "vega-dataflow": "^5.7.4"
}
```

As a longer-term fix, we may want the other sub-packages that transforms to the default vega bundle to have their versions set to 5.7.4 as well  in order to prevent this isues from affecting other developers.

![Image 2021-07-28 at 11 26 13 PM](https://user-images.githubusercontent.com/9020979/127426874-dc244663-dc8c-49e0-8061-ad3fa86f2f1a.jpg)

**Comment by hydrosquall** [comment]
I had a brief chat about this with @arcanis , who recommended that if some of these dependencies just need to sync with whatever version of `vega-dataflow` that is used by the root `vega` package, they could declare `vega-dataflow` as a `peer dependency` instead of a regular dependency. This would prevent the need to manually keep all these versions in sync.
