### ISSUE TITLE
Document 'key' property in groupBy aggregation?

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#1308]
I note that some examples use the `key` property when performing a `groupBy` aggregation, such as this [histogram example](https://vega.github.io/vega/examples/histogram/), but that `key` isn't documented on the [Aggregation transform page](https://vega.github.io/vega/docs/transforms/aggregate/).

The examples would appear to function correctly without specifying a key, so I assume it is just there to optimise the aggregation process when aggregating values into bins. Is that correct? Is use of`key` encouraged or is it deprecated? If not deprecated is there a reason for not documenting it?

**Comment by jheer** [comment]
Yes, this is missing from the documentation. It is not deprecated.

Your assumption is spot on. The `key` property is superfluous, enabling optimization of aggregate group key calculation when there is redundancy among the groupby fields. For example, for a histogram it is faster to key solely on the `bin0` property, and this is safe because the `bin1` property (also included as a groupby field) contains only redundant information with respect to grouping.

**Comment by jheer** [comment]
Documentation added.
