### ISSUE TITLE
projections in groups (multiple layouts) potentially use  global width, not groups width

### ISSUE THREAD

**Issue by Casyfill** [vega/vega#1333]
see [here](https://gist.github.com/Casyfill/f742b60200a032ba1a7acc601ac86f44):

map group's width is too large, even if set groups `width:{"signal":"globalWidth*.03"}`. However,
if I add this global size into projection,  chart picks the right size: 
`"size": {"signal": "[globalWidth*0.3, height]"},`

**Comment by jheer** [comment]
Hmm. In the linked example I don't see any place where you are setting the group width. It is fine to use `globalWidth * 0.3`, though that should have the same result as `width * 0.3`, as you never change the `width` signal. Alternatively, you can override the width and height signals by defining new signals within a group scope. If you define a new signal within a group mark, it will override any existing signal with the same name from outer scopes. Also note that the group width/height *encoding* properties are separate from the width/height *signals*, so setting the encodings would not have any direct affect on your projection's size.

Also, the use of `"autosize": "fit"` is squeezing the layout, but that may be intentional.

**Comment by Casyfill** [comment]
oh, I got it - for some reason though `{"type":"group", "width":400}` should work, but it does not.

**Comment by jheer** [comment]
No that’s not supported. You need to define width / height **signals** inside the subgroup.
