### ISSUE TITLE
Transform data from json object to list of records.

### ISSUE THREAD

**Issue by joejuzl** [vega/vega#1360]
Hi,

I am trying to build a visualisation for percentiles data I have from elasticsearch.
The data is in the format:
```
{
  "1.0": 354,
  "5.0": 354,
  "25.0": 354,
  "50.0": 451,
  "75.0": 451,
  "95.0": 451,
  "99.0": 451
}
``` 
As mentioned in the docs, vega works with data in the form of records e.g.
```
[
    {"percentile": "1.0", "value": 354},
    {"percentile": "5.0", "value": 354},
    {"percentile": "25.0", "value": 354},
    {"percentile": "50.0", "value": 451},
    {"percentile": "75.0", "value": 451},
    {"percentile": "95.0", "value": 451},
    {"percentile": "99.0", "value": 451}
]
```

Is there any way to do this transformation in vega? I can't seem to find anything in the docs, or issues. 
I would prefer to have it output this way from elasticsearch, but unfortunately the percentiles_bucket aggregation does not have the `"keyed": false` option like the standard percentiles aggregation. 

Thanks!

**Comment by jheer** [comment]
Yes, this can be accomplished using a [`fold`](https://vega.github.io/vega/docs/transforms/fold/) transform. For your current example:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.0.json",
  "data": [
    {
      "name": "srcdata",
      "values": {
        "1.0": 354,
        "5.0": 354,
        "25.0": 354,
        "50.0": 451,
        "75.0": 451,
        "95.0": 451,
        "99.0": 451
      },
      "transform": [
        {
          "type": "fold",
          "fields": [
            "[1.0]",
            "[5.0]",
            "[25.0]",
            "[50.0]",
            "[75.0]",
            "[95.0]",
            "[99.0]"
          ],
          "as": ["percentile", "value"]
        },
        {
          "type": "project",
          "fields": ["percentile", "value"]
        }
      ]
    }
  ]
}
```

The brackets (`"[1.0]"`) are used to indicate that the keys should be interpreted as string literals. Otherwise, Vega treats dot (`.`) characters as field delimiters (for example, `object.property`). (It is perhaps a bit annoying to hard-wire the fields here. Feel free to request a `keys` expression function in a new issue if you need to extract these automatically.)

The `project` transform is not strictly necessary, but ensures that the resulting output objects have only the `percentile` and `value` fields.

**Comment by joejuzl** [comment]
This works perfectly, thank you very much!
