### ISSUE TITLE
Lay out legends horizontally

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1365]
It would be nice if there was a way to lay out multiple legends horizontally rather than vertically. 

See https://github.com/vega/vega-lite/issues/3873

**Comment by jheer** [comment]
A few general thoughts:

- FWIW, we do support horizontal layout, but only for `top` and `bottom` legend orientations.
- We intentionally apply vertical layout for `left` and `right` orientations as this is more common. Of course, this can be complicated by (a) large vertical gradients or (b) long symbol legend lists. For use cases like Vega-Lite, one could modify legend properties rather than the layout -- such as using horizontal gradients or multi-column symbol legends. In case of two legends, one could also place one legend on the left and one on the right.
- We could certainly add control over layout to specify legend layout direction. One question is how this should be specified, as this decision applies across multiple legends. My inclination would be to add new config options that are then passed as parameters to the view layout. However, this would cause this setting to be global (i.e., all subplots would use the same scheme), but I don't think this is a significant problem.

For the specific example linked from vega/vega-lite#3873:

- The default gradient length appears to be too long relative to the default Vega-Lite plot size. This is a config issue.
- Changing the vertical gradient to a horizontal gradient in the face of multiple legends would clean up the display.

**Comment by domoritz** [comment]
I completely agree with the last two points. We will change the default height to be limited to the chart height and make legends horizontal when there is more than one legend. It'll still be a bit tricky to set the right number of columns for symbol legends but at least it will be better than what we generate right now. 

We discussed similar options in https://github.com/vega/vega-lite/issues/3853.

**Comment by domoritz** [comment]
I guess for now we won't need support in Vega-Lite. Feel free to close this issue or leave it open if we might add this in the future.

**Comment by jheer** [comment]
I'll leave this open as a potentially useful future enhancement. Thanks!

**Comment by jheer** [comment]
Closing out this issue, as Vega added legend layout control in a prior release. For more, see https://vega.github.io/vega/docs/config/#legends-layout
