### ISSUE TITLE
Legend does not update items to reflect bound data array when modified by View API changeset.

### ISSUE THREAD

**Issue by handsfelloff** [vega/vega#1374]
Vega Version 4.2
Legend does not update items to reflect bound data array when modified by View API **changeset**.

To Reproduce:

1. Copy spec from "Donut Chart"
2. Empty the data "table" values array(will insert this later via the View API) 
3. Add a very simple Legend definition (bound to the 'color' scale)
`"legends": [
    {
      "fill": "color"
    }
  ]`
4. Add the first items 1, 2 & 3 to the view via a **changeset**
```
state.vega_view.change('table', vega.changeset()
                       .insert([{"id": 1, "field": 4},
                                {"id": 2, "field": 6},
                                {"id": 3, "field": 10}
                                ])
                       .remove(d => true));

state.vega_view.run();
```
5. Following with another **changeset** for items 4, 5 & 7
```
window.requestAnimationFrame(() => {
    state.vega_view.change('table', vega.changeset()
                       .insert([{"id": 4, "field": 3},
                                {"id": 5, "field": 7},
                                {"id": 6, "field": 8}
                                ]));
    state.vega_view.run();
});
```
6 Observe (Only legend items 1, 2 & 3) rendered
![image](https://user-images.githubusercontent.com/7437715/43002368-646a6ae4-8c20-11e8-8f3c-2534355f97f3.png)

**Comment by freefood89** [comment]
I'm having trouble with this as well with a pie chart. Adding `encode` to `legends` didn't seem to change things. 

However, I did get it to work on line charts, stacked area charts, and grouped bar charts. Maybe it has something to do with the aggregation this transform does.

**Comment by jheer** [comment]
Thank you for sharing this. The problem is due to the use of implicit domain construction: the scale does not have a domain defined, but is automatically populated by values as they are looked up (this is a side effect that Vega's dependency tracking is unaware of). As Vega has matured we now dissuade people from using this feature if at all possible, but we still include it for backwards compatibility. Obviously we overlooked updating the pie/donut examples to reflect this!

To fix the problem, add an explicit domain definition to the color scale:
`"domain": {"data": "table", "field": "id"},`

Now Vega knows to propagate those domain value changes forward, including legend updates.

I have updated the examples to use best practices. Thanks again for bringing this to our attention!
