### ISSUE TITLE
Have removed axis labels be of width 0

### ISSUE THREAD

**Issue by Eveliyse** [vega/vega#1394]
I've noticed that in certain situations a chart does not occupy the full width of it's given space due to a hidden label.

[Example in editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwogAw7FESCkbV8WgEx6DUQujVrGM6loCs1yGvR5MOANpKIUAhgqBl0VGQtSG92ABtI6xDICnRY1mRYLX8QkOBIeC8abgAnAE8ogEEFKHDuVhk8CwAOAF9EnLyCvCKyqIAhasha+sacFxc2gI78wuoS8pxIAGFB4YatUQBmSZzgztn5qIARVdQ69ZwATgBGHd2wfe653sWAUVPz0bAm2-bcmaeh0WACVkKlYqUwLFZNQwN1YHgoeh2MhYmB2NxuIR0chkNiMYQPiMtE0AOwtKYQAC6Uwp1PcCFSGSyUyCOUgYQiUQAHoz4gpKVA8KVCJFFux0DI1ALdh5uBhHFo8p5vFEYvz5FAAGaMVHSxZdHrlO5JYqS6hilTqTR-Gx2BxOLQ6Og6NyCyDFc76uHFdK09pspKcy2QUp8hLutTy9CKnDKrw+IXIjXa3Wxb1DM7Ek3BDmMeCWvC+5C2j3mkPGUyNWlKKnudDc5l+VmQEq6i5QDEEeWDcM8vuayCxZGogDyVGKw8Ji1sxWYxoDrbnyA7Q+QWsag77izDBX5dLAdaUkAwxQA1plm7l3cLRVFish4Jv3VrPaglR4E2rk5Ec4YV-A3BqJagbsiu3TFEqgpJNyH7blAvJ7gkqZ6lEhrPAu0G5qoGiIHBSH9gRg4SlKWi-FhhgLA8kDwaGA4oemURrI0f7sqU5j4UyUS7lxg4pGklo6AeuysYYrCECqIGQDqsSxB+-HpFECK4rEcSKS0om4NwE4fjJclxskqSKYsD7ShpgrCWAB40i0QA)

In the above example you can see that there is a large gap to the right of the chart. If you remove `"labelOverlap": "parity"` from the x axis you will see that the previously hidden label actually occupies all of that right space.

This leads me to believe that removed labels are given an opacity of 0 as opposed to actually being removed. If that's the case I think it would perhaps make sense for removed labels to also have a width of 0 or something similar so that removed labels do not contribute to a chart's rendering?

**Comment by domoritz** [comment]
This is the first use of the sharing feature in the editor to report a bug. Thank you for the bug report with a working example! We'll look into it and get back to you.

**Comment by jheer** [comment]
Thanks @Eveliyse! What you're observing is in fact the intended behavior. We do toggle opacity and "hidden" labels are intentionally included in the layout. In many cases, Vega specs may have dynamic axes, for example due to zooming. To handle these cases correctly we want to ensure sufficient and appropriate layout and sizing, unfortunately in this case that decision leads to extra padding on the display.

If you would like to ensure a more "trimmed" layout, I recommend using the `"labelLimit"` property on your axis definition!
