### ISSUE TITLE
autosize: fit doesn't fill available space unless size is set multiple times

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1429]
This is a long-standing bug which I've finally found time to whittle down from a production system into a self-contained reproduction:

https://codesandbox.io/s/xllpppyj5z

When you click the "shrink" button, it cuts the width of the chart in half. The bug is, even though `autosize: fit` is enabled, the smaller chart doesn't fill the available horizontal space; it uses only a small fraction in fact. The larger the initial size of the chart relative to the reduced size, the poorer the use of space in the reduced size.

Before:

![image](https://user-images.githubusercontent.com/128019/46830939-f7f6a300-cd6f-11e8-9fea-d73e49edbd99.png)

After:

![image](https://user-images.githubusercontent.com/128019/46830954-00e77480-cd70-11e8-9352-3e51283204ac.png)

There is a listener attached to the `width` signal and logging it to the console; you can see that the width changes twice for any given external update; the first width is the full specified width, and the second one is the reduced width (presumably what autosize has calculated). For the large chart the width reduction is reasonable, corresponding primarily to the width needed for the legend. For the small chart the width reduction is drastically more than needed.

Interestingly, if we tell the view to update its `width` _twice_ (with an intervening `run`):

```js
  componentDidUpdate() {
    this.view
      .width(this.width)
      .run()
      .width(this.width)
      .run();
  }
```

we get the desired appearance, albeit presumably having done some wasteful extra computation:

![image](https://user-images.githubusercontent.com/128019/46831160-9edb3f00-cd70-11e8-8240-5b7f5d595612.png)

**Comment by jheer** [comment]
The issue arises because all of your `rect` mark encodings are defined in the `enter` set. As a result, they are not initially being re-evaluated, and so the `"fit"` layout is then using the unaltered bounds from the previous (larger) size setting.

There are two solutions you could apply here:
1. Place your `x`/`x2`/`y`/`height` encodings in the `update` block instead.
2. Or, perhaps more simply, when you make API calls, be sure to request re-evaluation of the `enter` set: `view.width(400).run('enter')`.

**Comment by pelotom** [comment]
@jheer I see, thanks for the tips! This has been an annoyance for a long time that I never understood until now.
