### ISSUE TITLE
Examples with vega view

### ISSUE THREAD

**Issue by braaannigan** [vega/vega#1477]
Hi - thanks for all your work on vega!  I'd like to use vega in a way that requires interaction with other non-vega components on the page.  It seems like I need to use the View API to do this. For example, I might want to download the data from a chart, or extract the parameters of a selection. However, I'm struggling to find concrete examples anywhere online that show how these are used in practice.

1) Does anyone know of such examples?

2) If not, would people provide me with some guidance if I created a PR with examples using the View API?

**Comment by jheer** [comment]
The `getState` and `setState` methods can be used to capture and update all internal state in the form of signal values and internally generated datasets. For most cases, however, I'd recommend designing your Vega specs so that you can simply use signals (`view.signal`) directly as the primary means of coordinating with other components.

**Comment by braaannigan** [comment]
Thanks @jheer
