### ISSUE TITLE
Vega's bind signals duplicated in Kibana

### ISSUE THREAD

**Issue by yechanpark** [vega/vega#1506]
hi.  im using Kibana 6.4.1.

when i using bind signals, they are duplicated.

like this.
![duplicate](https://user-images.githubusercontent.com/18444806/50440988-f3d42d80-093b-11e9-8e8f-588070d7da4c.jpg)

following is my config (all of configuration)
```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "config": {
    "kibana": {
      "controlsLocation": "top"
    }
  }
  "autosize" : {
    "type" : "pad",
    "resize" : true
  },
  "padding" : 50,

  
  "signals" : [
    {
      "name": "KeyQuery", "value": "",
      "on": [
        {
          "events": "@keyFilterButton:click!",
          "update": "datum.keys.key"
        },
        {
          "events": "dblclick",
          "update": "''"
        }
      ],
      "bind": {
        "input": "text",
        "placeholder": "search key",
        "autocomplete": "off"
      }
    }
  ]
}
```

at first, i guess above has been occured by my wrong vega config.

but when i tested using only signals, it's same.

both are working properly when i typed the text.
(i made this signals for data filtering)

but just one element working when binding value via click event.
(below is working properly, but above is not working when binding value via click event)

i referenced this example : https://vega.github.io/vega/examples/job-voyager/

is this a bug??

**Comment by jheer** [comment]
Hi, we do not provide support for Kibana at this repository. If you believe a bug is due to a Vega error, please provide a "pure Vega" example that replicates the problem, for example using the "Share" functionality of the [online Vega editor](https://vega.github.io/editor/#/).

Otherwise, please file this with an appropriate Kibana support forum. @nyurik may be able to suggest a good place for this.

For what it is worth, I fixed the JSON errors in your provided spec and ran it in the online editor and do not see any duplication.
