### ISSUE TITLE
Binning

### ISSUE THREAD

**Issue by marcprux** [vega/vega#152]
There is no convenient way to perform binning in vega, thus making histograms and boxplots challenging to implement.

One way this might be implemented would be to have a "scale" property for the "facet" transform, thereby allowing the specification of a quantile scale into which the values would be faceted. E.g. something like:

``` javascript
{
"data": [
  {
    "name": "table",
    "values": [ 2, 3, 30, 31, 90, 200, 202 ]
  }
],
"scales": [
  {
    "name": "pos",
    "type": "ordinal",
    "from": "table",
    "domain": {"data": "table", "field": "data"},
    "range": "height"
  },
  {
    "name": "quant",
    "type": "quantile",
    "from": "table",
    "domain": {"data": "table", "field": "data"},
    "range": [ 0, 25, 50, 75, 100 ],
    "zero": false
  }
],
"marks": [
  {
    "type": "group",
    "from": { 
      "data": "table",
      "transform": [
        { "type": "facet", "field": "data", "scale": "quant" },
        { "type": "stats" },
      ]

 ... each facet will then contain the binned data points, and we can draw a histogram based on the "count" stat ...
```

**Comment by ianhoolihan** [comment]
I'm not sure if this should be a separate issue or not, however I'm looking to create a histogram from *pre*-binned data. The population example illustrates this, i.e. 

    {"year":1850,"age":0,"sex":1,"people":1483789},

is displayed with a value of 1483789 for the bar age=0. This is not actually correct, as 1483789 represents a count for the people with 0 <= age < 5, whereas this implies there are 1483789 aged 0. The best (I believe) solution would be to move the labels and major ticks to the left-hand side of the bars (instead of in the center). I've read through the examples and the online editor, but can't seem to find evidence of how to do this (without e.g. using "dx" properties for the labels, which I don't think would scale well).

Is there an obvious solution, and if not, could one be implemented? Possibly updating the population example, or providing a separate histogram one, would be very useful.

**Comment by jheer** [comment]
I would classify this as a separate issue, but I'll respond here anyway :)

Let's consider the [existing population example in the Vega editor](http://trifacta.github.io/vega/editor/index.html?spec=population). There are two ways I can think of to layout the (y-axis) labels as you describe. The first is to use the `dy` property. You could update the text label mark by replacing
```
"y": {"scale": "y", "field": "age", "offset": 11},
```
with
```
"y": {"scale": "y", "field": "age"},
"dy": {"scale": "y", "band": true},
```
As the `dy` value is drawn from the range band of the scale, you should get correct results even as other aspects change. So in that sense it "scales" well. However, one issue is that there is no longer a label for the maximal end of the scale range.

Another option is to layout the axis labels using a quantitative scale. You could add the following top-level scale definition to the population example:
```
{
  "name": "yq",
  "range": "height",
  "domain": [0, 95]
},
```
and then update the text label mark's `y` property to use the scale:
```
  "y": {"scale": "yq", "field": "age"},
```
In this case we're still missing a maximal value, but that is only because the text mark is driven by the population data set directly. If instead you were to create an axis (e.g. `{"type":"y", "scale":"yq", "ticks":20}`) you'd see `95` at the top of the scale. However, if you use the quantitative scale approach you need to carefully set the domain. Here we set it manually to `[0, 95]`; in other contexts you may need to use data transformations to create a new data set with the correct range of values.

**Comment by ianhoolihan** [comment]
Perfect! Thanks for the thorough and helpful response, despite it being a pretty simple question.

@ajturner, this might be a good solution: you can manually calculate your bin size however you like, and use this method. That's what I do -- I'm using python to process much larger data sets into small plot-ready ones, and then I plan to use Vega to plot them.

@jheer: I was planning on writing my own python module that I sent a JSON request to and received a plot from -- thankfully I discovered Vega, as it does exactly that, and has all the grammar sorted too!
