### ISSUE TITLE
Support D3 Scales 2.2 scale types

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1536]
https://github.com/d3/d3/releases/tag/v5.8.0/https://github.com/d3/d3-scale/pull/156 has new scale types that would be great for Vega-Lite.

**Comment by domoritz** [comment]
https://github.com/vega/vega/issues/1369 is part of this so I closed it.

**Comment by jheer** [comment]
Here is a proposal for a backwards-compatible redesign of Vega's scales. All previous scale types would still work, though we may wish to deprecate some of them. The new standard scale `type` values would be as follows, augmented with a new `transform` property:

- `continuous` (requires numerical domain)
  - transform: linear (default), log, symlog, pow, sqrt
- `sequential` (requires two-element domain)
  - transform: linear (default), log, symlog, pow, sqrt
- `diverging` (requires three-element domain)
  - transform: linear (default), log, symlog, pow, sqrt
- `binned` (requires binned numerical domain)
  - transform: linear (default), log, symlog, pow, sqrt, ordinal
- `time` (requires date-time domain)
  - transform: local (default), utc
- `quantile` (requires domain with all values)
- `quantize` (requires numerical domain)
- `threshold` (requires numerical domain)
- `ordinal` (requires discrete domain)
- `band` (requires discrete domain)
- `point` (requires discrete domain)

The new `binned` type would subsume the previous `bin-linear` and `bin-ordinal` types, adding support for binned domains using a different continuous transform.

The scale `type` parameter will not accept signal values, but the new `transform` property will.

@domoritz, @kanitw, @arvind: Thoughts / reactions?

There are arguably opportunities for additional groupings, such as combining quantize and threshold, or band and point, but I'm unsure of those. For example, I could imagine a future scenario in which we support quantize scales that subdivide the domain according to a non-linear continuous transform (log, etc).

**Comment by domoritz** [comment]
My reaction is 😍. I think there is a great opportunity to expose the `transform` property in Vega-Lite once this lands in Vega. 

Tagging @mbostock to see whether he has comments.

**Comment by kanitw** [comment]
I may have to think about this deeper, but my initial reaction is this is quite complicated to users. 

I think the things that we _primarily_ need input from users are not the distinction between continuous/sequential/diverging, but rather the distinction between linear/log/symlob/pow/sqrt -- so I'd prefer to use `type` (rather than `transform`) to distinguish these.

We could then find another secondary keyword to distinguish "continuous" / "sequential" / "diverging".  This keyword could be even perhaps optional, since we probably can infer that something is sequential/diverging if `"scheme"` is specified (and use the `"domain"` length to distinguish between sequential and diverging). 

I've not thought about this would work for `"binned"` case.  

At very least, I don't think Vega-Lite users should have to learn about two keywords: `type` and `transform`.  Maybe it's okay in Vega, but I also would like to have consistent patterns for both Vega and VL if possible.

**Comment by jheer** [comment]
Also, it would be easy to also allow top-level types for all scale variants (e.g., `diverging-log`, etc) as part of the design above if we decided that was a good idea. It's just that those would not be bindable to signals.

**Comment by arvind** [comment]
> I'm becoming more convinced that the design is too convoluted

I'm still thinking on this proposal but, @jheer, it would be helpful for me to know why your original proposal is becoming too convoluted. At the Vega level, it seemed like a clean decoupling of concerns and I especially liked that the transform could now be signal-driven (anecdotally, I feel like that's been a common feature request). 

I also agree with @kanitw's concern about the complexity of exposing both type/transform at the Vega-Lite level. But, perhaps that's an opportunity to introduce new abstractions at the Vega-Lite level rather than pushing it down to Vega? In particular, a variant of @jheer's second proposal reads to me like what Vega-Lite's scale `type`s should be?

**Comment by jheer** [comment]
I felt the design was becoming too convoluted in two respects: after appropriately updating units test and test specifications the design felt cumbersome from an end-user perspective (@kanitw's point) and it was making the internal code more convoluted (two-key indexing and lookup system for scales based on both type and transform). When I implemented the second design both were improved: specification that better matches a designer's mental model (I can say `linear` and get the right result based on domain and range information) and more concise and straightforward code (the "inference" procedure for determining the specific scale instance is just a couple if/then/else statements!).

As I thought about it more, I also think we might still ultimately support signal values, but for the `type` property itself rather than a subordinate `transform` property only. There will be some caveats and limitations (not all scale types are interchangeable), but this too is a smaller delta from the current schema and will actually allow more possible options for dynamic scale types (at the cost of some runtime restrictions, such as no moving from `linear` to `band`, for example).

**Comment by mbostock** [comment]
Having types that encompass the transform (e.g., type=log instead of type=continuous + transform=log) is essentially the same conclusion I came to with d3-scale, as opposed to exposing *continuous*.transform.

Sequential and diverging scales are distinct types in d3-scale because they have domains with fixed cardinality (sequential defaults to [0, 1], diverging defaults to [0, 0.5, 1]) and the “range” (the output of the scale) is specified in terms of a function rather than a series of range values plus an interpolator. They are similar to continuous scales with fixed ranges of [0, 1] and [0, 0.5, 1] respectively, but you have to do a little dance to make *continuous*.interpolate give you the same result as *sequential*.interpolator and *diverging*.interpolator. E.g.,

```js
 d3.scaleLog()
    .domain([min, max])
    .interpolate(() => d3.interpolateMagma)
```

but this only works if the domain is ascending. Still, it’d probably be possible to reconcile the implementations. It just hasn’t felt pressing as opposed to having the type (class) dictate the transform.

**Comment by kanitw** [comment]
Thanks @jheer and @mbostock.  Here are some more thoughts/responses: 

## Binding Transform Type is Important

Thinking more, I agree that the requirement to support binding is quite important. As users often want to toggle the scale "transform" (e.g., linear vs log) all the time, having the `type` (or `transform` in the older proposal) bindable means Vega can use signal binding to enable this kind of toggling interaction easily.  

## Fine-grained `type` vs `type` + `transform`

I'm now having mixed feelings for these two options.

> Provide top-level types for all continuous scales (linear, log, pow, sqrt, symlog) that encompass standard continuous scales as well as sequential and diverging variants. The vega-encode scale operator performs some checks based on the input scale type, domain, and range values. If the type is continuous and the range uses color schemes or color literals, we can switch to a sequential variant (if the domain length is 2) or a diverging variant (if the domain length is 3, for example by using domainMid).

> As I thought about it more, I also think we might still ultimately support signal values, but for the type property itself rather than a subordinate transform property only.

Overall, I still like one `type` property more, especially if we can support binding `type` for the common use cases anyway.  This will also be pretty natural in Vega-Lite. And we could still add `binned-log/pow/sqrt` types if needed in the future. (I don't think the latter is high priority though.)

That said, only support some types of signals is a bit weird (but not important). 
Basically, I think there are a few types of scale types changes in Vega and Vega-Lite:

1. Simple type changes, which requires only one change to the spec (just the `type`). There are two sub cases here:
  a) Change within the same category of scale types (e.g., among quantitative scales like from `linear` to `log`) -- it seems like we will still support this. 
  b) Change from linear to band -- this is probably less important and probably ok (but slightly weird) to _not_ support.  

2. Complex type changes that require changing other properties (such as domain, range, or encoding entry). For example, changing from a linear/sequential to discretizing scales for size/color. This requires users to change the `domain` and `range` in addition to the `type` to make the transition work.  Thus, supporting this case for binding signal wouldn't work on its own anyway. 


As I think about the original proposal more, I could see myself "ok" with a separate `"transform"` property too as long as we only have one `"continuous"` type that does the reconciliation for "sequential" and "diverging" cases (and keep `"sequential"` for backward compatibility).  Basically, I think the need for users to distinguish continuous/sequential/diverging is way more confusing that the need to learn two properties.  

Overall, I still like one "type" property better (since one type property is simpler to explain, the quirks about signal binding is more like a low-level detail).

**Comment by kanitw** [comment]
## Binned Scales

> I still need to think more about what to do with bin-linear and bin-ordinal under this design. 

I think it makes sense to keep them separate as they have different range types. 
But it would be worth revising the categorization in the docs to simplify explanation. (It took me a while to understand their difference given the current docs.) 

- In the current Vega scales docs, these two binned scales are considered "discretizing" scales. However, I think binned scales are a bit different from discretizing scales: binned scales deal with "already-discretized/binned" field while discretizing scales do the discretizing transformation themselves.   

- For both binned scales, they have similar setup for domain and mark encoding entry. By having this grouping, we can reduce redundant text and better explain their similarities.  In their subsections, we then only need to discuss how their range types differ (2-element continuous range vs discrete/discretized interpolation).

**Comment by jheer** [comment]
A few responses to @kanitw's points above:

- Complex type changes are possible (albeit odd use cases) under a unified `type`. For example, given a `linear` scale, if I change from a numeric range to a color scheme, internally the scale type could change from `linear` to `sequential` (or `diverging`). The `type` itself would not have to change. Again, though, I think this is an exceedingly rare use case.

- I agree that binned scales are different from discretizing scales! I plan to update the documentation later to separate these types, just like you suggest. What differentiates binned linear/log/etc from the continuous variants are:
  1. pre-binned (discretized) domain
  2. customized tick generation (i.e., don't produce ticks at intervals smaller than the bin boundaries), and
  3. custom legend label generation paths within vega-encode.

That's it! All other methods (`range`, `invert`, etc) are the same as the continuous cases. (Of course `bin-ordinal` is different, as it maps the binned domain to a discrete range.)

**Comment by kanitw** [comment]
Btw, as we're revising scales, this might be a good opportunities to fix https://github.com/vega/vega/issues/995 and https://github.com/vega/vega/issues/1479. :)
