### ISSUE TITLE
Support groupby KDE calculation.

### ISSUE THREAD

**Issue by sirahd** [vega/vega#1608]
We plan to support violin plot in vega-lite with the flexibility to use shared scale for density value across data source after the data is partitioned based on particular field. However, to achieve that we would need the ability to specify groupby field in density transform (specifically on kde distribution, since it does not make sense to support groupby on other distributions), so that we can compute the shared scale.

cc: @domoritz

**Comment by domoritz** [comment]
@jheer Does it make sense to compute a shared scale across different densities? If yes, is this a reasonable feature request?

**Comment by jheer** [comment]
In terms of visualization, it absolutely makes sense to compute a shared scale: the area of the distribution should represent the integral of the pdf (= 1, ignoring issues of min/max value cutoffs), so each distribution should be scaled similarly so that they have the same total area. The current Vega violin plot example fails in this regard!

As for doing this properly in Vega, I'll have to think about it more. I looked at the current Density transform, and I don't think it is well-suited to being modified to include a groupby calculation. In the worst case we could add a new KDE transform, but at the cost of some feature redundancy.

That said, I also wonder how hard it would be to extend the aggregate transform to support a density estimation aggregate -- it would require adding the ability to pass additional aggregate function parameters (which would be useful in other scenarios, too) and would depend on us being able to unpack an output aggregate record into multiple tuples (which I think would work using our existing support for pre-faceted data). BUT I worry this would require a significant effort...

**Comment by domoritz** [comment]
Thanks for the insight. At some point we will want to have violin plots in Vega-Lite and I don't see a way for us to do that until we have a way to group the densities. Is this something @sirahd could take on?

**Comment by jheer** [comment]
@domoritz and I discussed this offline and it looks like a reasonable solution would be to develop a dedicated `kde` transform that includes groupby support. Both the existing `density` (vega-transforms) and `stack` (vega-encode) transforms might be good starting points to consider.

**Comment by jheer** [comment]
Added by #1783, released in v5.4.
