### ISSUE TITLE
Dynamically changing Vega 5 Legend "orient"

### ISSUE THREAD

**Issue by roying** [vega/vega#1665]
Vega v5.0.0-rc5 Legend "orient"

> https://vega.github.io/vega/docs/legends/#orientation

 does not seem to accept signal expressions:

> 	"orient": {"signal": "'top'"},  // does not work
> 	"direction": {"signal": "'horizontal'"}, // works
> 	"columns": {"signal": "2"}, // works

Could "orient" also accept signal expressions so that the position of the entire legend can be changed during run time? The use case for this is when the chart container size changes, the legend should be allowed to change also for optimal placement.

Note: The tutorial at: 

> https://observablehq.com/@vega/a-guide-to-guides-axes-legends-in-vega

shows changing placement of legends using select option for
	

> **Symbol Orient** and **Gradient Orient**

but there is not a complete example with Vega signal binding to illustrate how this can be accomplished from within the Vega v5 spec.

**Comment by jheer** [comment]
Legend `orient` does not currently support signal values, but that can be changed fairly easily. Look for that in the official 5.0 release. However, a signal value for `direction` violates the schema and can not be supported: the parser uses the direction value to generate appropriate encodings at parse time. If it happened to work in your example above it is probably only because the parser assumed the direction to be horizontal by default.

**Comment by roying** [comment]
Thanks, Jeff. That's great!
