### ISSUE TITLE
Modify not updating store when signal inits use scale

### ISSUE THREAD

**Issue by arvind** [vega/vega#1672]
In the following specification, when the `init` expression for `brush_x` and `brush_y` reference a scale function, the `modify` expression does not correctly clear out the dataset under the following sequence:

1. Click in empty space --> selection state (the `brush_store` dataset is correctly cleared).
2. Drag out a new brush.
3. Click in empty space --> selection state is not cleared.

Interestingly, if the brush is projected over [only a single dimension](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAIuvTUw3VnjDow65PDzoZ1VgBt06sO3WtYiMHm4wREZqRBcQ-DBCbkYZPFg6BSVIdAtuWEYAL2RsKEJ0ZSSISHzlZVjqXNFFYoB3RmUWXIAmAAZWmtxkCLwW9s7IWDwATxcc-XhkFxcilXQHXIBtJQhgSBl0VHGoLx9EAH0h7ltIAF9O1fXN7cHzdUn91oUoVnUZ-WV5kXh3BKlZZ6QABmxwwvRwaxGhBu-zkp1OSgAugMMtQNi5YEsVmBQBA8VANltcpBWDJmLN8ZAKOgXKxtsBztjigCcMt8fi1sgqHFMfpUOZYGhuFRAaxCJ88DdGLAACpisYACmo6nMhAVAEp1WAAPxgZWqjVgHCk8kI9lgRHYxkcq5E-S7Xyi8XzG4UFwAZSmdh0sgASmpuC4qAqADqQB0HI62MPqs4XHFMgnXYkR-YADwpeMgsXJ+kWCBpyFDkDTYfkYFEonV5YLirDpeeAEYAGytdWIzPMvRgNnmhN9rNc5A83JraSvSbEhDcaGAqE3fk+ZDKbi1OHx80k52S4mLNMKk14atgfeH9uQRMQa193EDqBDkcQy-s24Tm71GQr2qdvuQefExdBX5EUN1-eBZFgVg7X8bxkFAzd2GQPBamQYcsTvdkxzuSd9GnWdyz-YZZz5AVl1Xddn3NLC32JD8vznIiF1IsUzkovFLQw68By3CUbkWVM00WVpkTAeA3FQNVTzJI9yw6MB6kaRBz2fM12Q4vEuP7F9CRuVMAAljkFaIUPUH9s2k3dK3LFthLMlke2fW9uIfeJR0GEJ0RTbxfHTOM2J4l0vL2dMhMRMAAF5Is8byDkExswt1GRXBcI0wFiKh1DwYsG3LATYxUxN1KveMnKzHSgp8vB5RyUDzNzKBgEPHAwzLMAgUYKZlBIaLgqqwgxn2drOtgctqVpNRWUWKywBsxFEVOOzu17Kj-Jc3kezHDyaQqg4DPUIzV2QUzTmRfyxV4nb9j2g6TJ1HEmrAFrniGlwupwVM+oGl6utGmk6W6-iYquwzkGMo75tSpLpgvAdVPxIqwE00rinK+0gc+5BBo617MVqsa6SWNZvuJa7QcO0yCKQRwZCmYkMwI-99F9M4EaRxNbV0oH+XKIFhjM87ApInnhmLVMo2QVqPuq8s8Fg-L8VU07igwdQAGt1uWrTKVRnYgdTdhKlqxmoFsewzLErRcllulauHcDVFHZ9IGHSVTIhYFGGh938ZuABiABmQO4ygdrpgAeXyeBmD572-u2Vo6EbZpRHheCXm3el-IzVk2NWXOs0lIZiQldBRaB8WYzoMYnBYMAADI67AEuy+CivIHVUK6EPCKoqen9uNRTy0eCwTbPzzSBzWH3claOG+yVu9IBjhyMLz1eC7UcE5gcFufLb9Uq+Haha4bpuvl3yMAmjdvO+7yLwseyAw3739p5wVpx7Tm037AWe2IX7iaZmjoVXsjRehct6QGbmGMWV8Jbt0PjXPwp9oHhnLnAmMt9pI9wfn3L+L5B7bWHj5OKHZP75ynnHGec9zQAN-MMYBOd15gO4hA4u58YHoOOPAg+1dj7IMbqg2B3DMHCS7tg++j9n74MpMTd2+oWL6BQD0Vi68J43ipFQ9+NC1IFXNHPNmm4daQBVurMyxtBjDFQOwQMZkhijG2IsEoMQ4iQDocUIEKpUBuRLlObCmMnjqOdjIe2mduICx3E+DCkAZzoCjiMNyP8E4AHZ1GyM9u8FeoD87FDYR8eYUFFhhlJmDdQYYwqSKhilAAPtUtKsAABy6AGkKglIU4pINSnlK1LUs+VVUBFMgAAWU9mofY0J1D7AAOI0hcLIcpOCwBVLAL06UTSWltIGWGEZYxYDjKOtM2Z8y3GxhkVmH+VTyHMM0eNYkstHCwHyLYVxOj4b4MGLLbgqtHEUJyVAPJ292mQBKeTBZlTkorLqWs5prSClbOBZ00FJzIV9KBTssZEzDnTGORUqKyzVmNJhZswZ6K9mYpmdimQ3SX6bguclK52T165M3sSAAhAqPhLBYU704a3DB7dNQooVG6T0Yx7C6BlJvC+hx+Xlk2ZqGlBCfhjGJOBOZFM-ke06sSAAwqMWIqh9ow1XmkzCNyCb6GVMgPmrz2LvICIGHQhBHbr3cmiIhDUOn7TJiZMMOAQTqDBNyoFILfVuPLE9Y82zRlkoORSuZVLcgBqDcS6Nuz9mTPjTiiNT9245r1eET8R1YB+rAAAcjLQAalTZAAtBri3lIWmxU1xRs44kGMqm49MQ7Y0KPoUNR0-LROXmOTtxI+YETkVAUlGasUJtUX2HRBiSrs2MfrGK5jGLElNr0WqFtnU4GtnBdmdtuAOyib+F2g73ah0yZQ25+h7kyEee4F2ZxTUBUiVrX8bbNaT01QCqBHC0F8pEQgzlAi+ml15XvflHcxF317rmxVlJCGZJAyQ0KxrOJnPvRa3+tqIDuJfMvP9N4AMsvyTyjDl8wO8KPifQRwHhHX3g4icRzBFl4M1UkhlGE8Px0Ixad5QCQH8Yo0XKj0GaMyro4g-h9cmPUZYzwrBnHJHcaZVANDl1SHYbvC2vEAnqH-3eQwsTd4WG-kA0IrhrH5OMag9K-eanLAaeQ2cjxva3IKIPV0FRQnioUPNYJ0z-khgqm+RZyef5KO6xHqFMArKooCUWPFQEP9IC1GCDuQzlw6XTCEwjBWiYDFIhRJ2jW2IwEczppu4iUBC3IHcGZFcGBYg+K+H4t8jxARToRd60pQ6XzGCcI4uSm13XoYUk0E6tUyQ4Rgjbdm2QVRW1glaFdRjkz6AnezCxTWWu1Ta+gDr7tfG4X8b1yd3n9AzvJUciim5RvUEcZNoe-nQi9HOL-Yj6xGCLaPbVVb3B1t0k29V1dO2oBquOPVm4xxyieWO9wdr3Y1gXe01dp4N3tX6DrUWo1BFpCZTB8gIJL2EfqCR9tWqsRXbRDcF+yAiAxL6cVgMdAaY1AWZq7WLtdlNBvvtNwAgqOzLKgaEmmkgojbMBVf2xFJkzJuEQi4AAYrSR0h7YK1VV1MMOGU3B+aB-tgHqsdXmFce7HTExuguAVDNxApAAAsbZhuUkyPWttjYIccnZvzurtVjgdWtzsUXARvG1Ul8od0Y7dsS80H2pbx7Nw6HgBbq3W93sesgJMT2juGgsFd+7oJJ2zttRl6nl8+uMTS4xNXykGA0wAFE0ySjDx0dmqBYht471vLvafzfrSBFX4H3uZ5+6MwH+PUA9ubhD8LxryAgS7vZjH+vsuzd4AV9OmNs6s1yD1+gNXhujrG7J3LjPlvSTZ7dR9vP9uFTKK+yX2MQSvdFp91PteSrCzjsF1D0gTGFX0TwaDj3-30HpnXyT0vzN2vyzzcltxhyfxf3wDfw9yzHL27FHwb2PzVxHzH27y5z7yX0HxfB7xkFIM7yvzMX9SIM3E-1UDbQ-hKyIwGDGFe0-Cq3903Aiy+RuFhw1U3GVAKCAIABkGNEAkCtp0MxJNg1Q0C8ByxmwXdyw2hS85cd8bgCdDVcYT0Qkz0wlfxYArEbE68L1wkM4XVV4PYvZ21Msn0X1nlvszkYlI5o5EktFf46BUlm09F2Qyt2DkhwIZB2pKh3YudpQABNNySg6gref2WeBEU4IAA) clearing seems to work correctly. 

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "Drag out a rectangular brush to highlight points.",
  "autosize": "pad",
  "padding": 5,
  "width": 200,
  "height": 200,
  "style": "cell",
  "data": [
    {"name": "brush_store"},
    {"name": "source_0", "url": "data/cars.json", "format": {"type": "json"}}
  ],
  "signals": [
    {
      "name": "unit",
      "value": {},
      "on": [
        {"events": "mousemove", "update": "isTuple(group()) ? group() : unit"}
      ]
    },
    {"name": "brush", "update": "vlSelectionResolve(\"brush_store\")"},
    {
      "name": "brush_x",
      "init": "[scale(\"x\", 55), scale(\"x\", 160)]",
      "on": [
        {
          "events": {"source": "scope", "type": "mousedown"},
          "update": "[x(unit), x(unit)]"
        },
        {
          "events": {
            "source": "window",
            "type": "mousemove",
            "consume": true,
            "between": [
              {"source": "scope", "type": "mousedown"},
              {"source": "window", "type": "mouseup"}
            ]
          },
          "update": "[brush_x[0], clamp(x(unit), 0, width)]"
        }
      ]
    },
    {
      "name": "brush_Horsepower",
      "init": "[55, 160]",
      "on": [
        {
          "events": {"signal": "brush_x"},
          "update": "brush_x[0] === brush_x[1] ? null : invert(\"x\", brush_x)"
        }
      ]
    },
    {
      "name": "brush_y",
      "init": "[scale(\"y\", 13), scale(\"y\", 37)]",
      "on": [
        {
          "events": {"source": "scope", "type": "mousedown"},
          "update": "[y(unit), y(unit)]"
        },
        {
          "events": {
            "source": "window",
            "type": "mousemove",
            "consume": true,
            "between": [
              {"source": "scope", "type": "mousedown"},
              {"source": "window", "type": "mouseup"}
            ]
          },
          "update": "[brush_y[0], clamp(y(unit), 0, height)]"
        }
      ]
    },
    {
      "name": "brush_Miles_per_Gallon",
      "init": "[13, 37]",
      "on": [
        {
          "events": {"signal": "brush_y"},
          "update": "brush_y[0] === brush_y[1] ? null : invert(\"y\", brush_y)"
        }
      ]
    },
    {
      "name": "brush_tuple",
      "init": "{unit: \"\", fields: brush_tuple_fields, values: [[55, 160], [13, 37]]}",
      "on": [
        {
          "events": [
            {"signal": "brush_Horsepower"},
            {"signal": "brush_Miles_per_Gallon"}
          ],
          "update": "brush_Horsepower && brush_Miles_per_Gallon ? {unit: \"\", fields: brush_tuple_fields, values: [brush_Horsepower,brush_Miles_per_Gallon]} : null"
        }
      ]
    },
    {
      "name": "brush_tuple_fields",
      "value": [
        {"field": "Horsepower", "channel": "x", "type": "R"},
        {"field": "Miles_per_Gallon", "channel": "y", "type": "R"}
      ]
    },
    {
      "name": "brush_modify",
      "update": "modify(\"brush_store\", brush_tuple, true)"
    }
  ],
  "marks": [
    {
      "name": "brush_brush_bg",
      "type": "rect",
      "clip": true,
      "encode": {
        "enter": {"fill": {"value": "#333"}, "fillOpacity": {"value": 0.125}},
        "update": {
          "x": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_x[0]"
            },
            {"value": 0}
          ],
          "y": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_y[0]"
            },
            {"value": 0}
          ],
          "x2": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_x[1]"
            },
            {"value": 0}
          ],
          "y2": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_y[1]"
            },
            {"value": 0}
          ]
        }
      }
    },
    {
      "name": "marks",
      "type": "symbol",
      "style": ["point"],
      "from": {"data": "source_0"},
      "encode": {
        "update": {
          "opacity": {"value": 0.7},
          "fill": [
            {
              "test": "datum[\"Horsepower\"] === null || isNaN(datum[\"Horsepower\"]) || datum[\"Miles_per_Gallon\"] === null || isNaN(datum[\"Miles_per_Gallon\"])",
              "value": null
            },
            {"value": "transparent"}
          ],
          "stroke": [
            {
              "test": "datum[\"Horsepower\"] === null || isNaN(datum[\"Horsepower\"]) || datum[\"Miles_per_Gallon\"] === null || isNaN(datum[\"Miles_per_Gallon\"])",
              "value": null
            },
            {
              "test": "!(length(data(\"brush_store\"))) || (vlSelectionTest(\"brush_store\", datum))",
              "scale": "color",
              "field": "Cylinders"
            },
            {"value": "grey"}
          ],
          "tooltip": {
            "signal": "{\"Horsepower\": format(datum[\"Horsepower\"], \"\"), \"Miles_per_Gallon\": format(datum[\"Miles_per_Gallon\"], \"\"), \"Cylinders\": ''+datum[\"Cylinders\"]}"
          },
          "x": {"scale": "x", "field": "Horsepower"},
          "y": {"scale": "y", "field": "Miles_per_Gallon"}
        }
      }
    },
    {
      "name": "brush_brush",
      "type": "rect",
      "clip": true,
      "encode": {
        "enter": {"fill": {"value": "transparent"}},
        "update": {
          "x": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_x[0]"
            },
            {"value": 0}
          ],
          "y": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_y[0]"
            },
            {"value": 0}
          ],
          "x2": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_x[1]"
            },
            {"value": 0}
          ],
          "y2": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_y[1]"
            },
            {"value": 0}
          ],
          "stroke": [
            {
              "test": "brush_x[0] !== brush_x[1] && brush_y[0] !== brush_y[1]",
              "value": "white"
            },
            {"value": null}
          ]
        }
      }
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": {"data": "source_0", "field": "Horsepower"},
      "range": [0, {"signal": "width"}],
      "nice": true,
      "zero": true
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {"data": "source_0", "field": "Miles_per_Gallon"},
      "range": [{"signal": "height"}, 0],
      "nice": true,
      "zero": true
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "source_0", "field": "Cylinders", "sort": true},
      "range": "ordinal",
      "interpolate": "hcl"
    }
  ],
  "axes": [
    {
      "scale": "x",
      "orient": "bottom",
      "grid": false,
      "title": "Horsepower",
      "labelFlush": true,
      "labelOverlap": true,
      "tickCount": {"signal": "ceil(width/40)"},
      "zindex": 1
    },
    {
      "scale": "x",
      "orient": "bottom",
      "gridScale": "y",
      "grid": true,
      "tickCount": {"signal": "ceil(width/40)"},
      "domain": false,
      "labels": false,
      "maxExtent": 0,
      "minExtent": 0,
      "ticks": false,
      "zindex": 0
    },
    {
      "scale": "y",
      "orient": "left",
      "grid": false,
      "title": "Miles_per_Gallon",
      "labelOverlap": true,
      "tickCount": {"signal": "ceil(height/40)"},
      "zindex": 1
    },
    {
      "scale": "y",
      "orient": "left",
      "gridScale": "x",
      "grid": true,
      "tickCount": {"signal": "ceil(height/40)"},
      "domain": false,
      "labels": false,
      "maxExtent": 0,
      "minExtent": 0,
      "ticks": false,
      "zindex": 0
    }
  ],
  "legends": [
    {
      "stroke": "color",
      "gradientLength": {"signal": "clamp(height, 64, 200)"},
      "title": "Cylinders",
      "encode": {
        "symbols": {
          "update": {
            "fill": {"value": "transparent"},
            "opacity": {"value": 0.7}
          }
        }
      }
    }
  ],
  "config": {"axisY": {"minExtent": 30}}
}
```

**Comment by jheer** [comment]
So this one is a bit of a doozy. The short of it is that it looks like there are multiple signal event listeners (within a compound, array-valued event stream definition) where one would normally use a single `update` -- presumably because `init` precludes the use of `update`. This leads to a bit of a mess. The proximal solution is to rewrite the spec to avoid using multiple signal event listener definitions.

In the case of a direct `update` expression (not related to an event stream), all referenced signals are extracted and the update expression itself depends on _all_ those signals. In the case of an event stream definition with multiple signals within it, the dataflow includes an internal proxy operator for _each_ individual signal. So instead of a single invocation that respects all upstream dependencies, you get *two* separate invocations of the same update expression at different points. In particular, the resulting double invocation of `brush_tuple` creates the bug you've observed as a side-effect of multiple state updates to the `brush_tuple` in the same pulse propagation cycle.

This is bad enough on its own, but there is a further complication: The use of event handlers instead of `update` expressions for signals such as `brush_Miles_per_Gallon` also affects the topological sort for operator precedence. Proxy operators (those that evaluate an event handler's update expression and then set the value of the corresponding named signal) always have highest precedence, which can result in other named signal (non-event) `update` expressions being invoked later. As a result, I'm seeing execution traces like this upon mousedown:

1. `brush_x` (triggered by mousedown event)
2. `brush_y`(triggered by mousedown event)
3. `brush_Horsepower` (triggered by brush_x signal listener)
4. `brush_tuple` (set by a proxy operator triggered by first signal listener)
5. `brush_modify` (triggered by brush_tuple signal listener)
6. `brush_Miles_per_Gallon` (triggered by brush_y signal listener, only evaluated now due to toposort)
7. `brush_tuple` (set by a _different_ proxy operator triggered by second signal listener)

The "late" evaluation of `brush_Miles_per_Gallon` comes about due to the combination of the observations above: (1) precedence of proxy operators (which is a critical aspect for correctness elsewhere) and (2) the use of signal event listeners, which do not induce *dependencies* but rather only act as event *triggers*. Note that none of this is necessarily "wrong", though it is certainly confusing! If we want to make changes to Vega's design, we might start with how we treat compound event stream definitions that include multiple signals -- should they be automatically consolidated? Another possibility would be to see how hard it would be to support _both_ `init` and `update` within the same signal definition.

In the meantime, the smallest delta fix here is to remove the two signal event listeners for `brush_tuple` and combine them into a single signal listener so that there is only one invocation (e.g., `{"signal": "brush_Horsepower || brush_Miles_per_Gallon"}`). While this resolves the double invocation problem, this doesn't address the toposort ordering (which but doesn't seem to cause undesired behavior for this particular spec).

That said, I also recommend writing these specs differently. The `brush_x` and `brush_y` signals are making use of `init` they way `init` is intended to be used, so these are just fine. What I don't understand is why `init` is being used for all the other signals where `value` could just as easily be used -- those `init` properties are really just constants, and so don't need expressions. Dropping `init` in these cases then allows `update` to be used and all the signal listener complexities can be avoided. So, I would strongly recommend using `value` and `update` instead of `init` and `on` wherever applicable.
