### ISSUE TITLE
log file for cli tools

### ISSUE THREAD

**Issue by blset** [vega/vega#1677]
for the CLI tools, would it be possible to send to a log file  all debug/warn expressions that normally go to javascript console in a web context ?

also to be able to specify the log level for CLI

**Comment by jheer** [comment]
You can redirect output to a log file using standard command line syntax. For example:

`vg2png ... &> log.txt`

on Unix and MacOS will route both stdout and stderr to log.txt. 

We can also add log level as a parameter in the next release. I will look into using a custom logger so that info or debug level output will be written to stderr, allowing continued use of the cli tools with image output written to stdout (e.g., for use in pipes).
