### ISSUE TITLE
How to achieve aligned header and title groups using `layout`

### ISSUE THREAD

**Issue by blset** [vega/vega#1692]
When I try to set width, height and fill of a group with role colum header
I get a strange result

the title of the column header  is placed above the group where it belongs, but the rectangle set by width height and fill is not aligned with the title and overlays the group below

here is a short example

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJBSNq+XQEYADO7tQA7owMsbqJeJhgATgDWsLoA2koQoBBJUHgAnoQ6OJDUYdyshMbJ9rkANplQ8NwlrKgyALR4zGWFRZCNeM04iUX2eMgAHni6kCXoqXl4YO3N3j2Q7OiwyCWW5d099hTo1eVt3AXxRQC+hxBHs0mQyDKVBmunl-kG6H266xuQAGaMJSVvD3MtjthmFkEYAUlzhD7I5nEMutDLkDWOUAEzuRFQjaXPwBRD-bHJSAaagybbDXGBTEQk49WmQi7vXrpXY5PIFC7FKq7SrVWp1FCGZBhFpE6b3bFtAbw3DIIVhVyi1qfWR4ADKWnKAA5OZdtk45Fkyp8hg8sa1rrcJR8ni9rZLvr8CYTNtsUcMcshrpBMbqibCXAiXa7gTgAMwYl3myX7dDwZipZ0uyDI8ruOio32IyCU-FB4PEg3krK50ion1Rmlmw7RsBMlIsj25fJK+yW7h3JMWmR9EX5yW5ruSklkv4l-wsMsVwm1uYBmX1uYj4uypwuLPJ2B4XIRe2ElNu3bsYHU7H05KzqDhKKxCGLy5pDLDPqDVvdq1Dj7XXufyUvheIoCh7PtK07BmAl6SgsSwrDIe7gQeoYpPsYHBueM6nhs6EQAAujWjIPG0jZZGyLa6pApQ8lUNT1IKdwiuR4q-ikoFZHRwrln6UAqj2GraLoOoQpA+qksMxqmnS5Htp2-atLaryyXMjpjnWgFQKmwzHu6G77rG8ZpMxRIaTg6aiDpkrzoZSLAeGkYzlx9iDopHzLipOYTogU7mS527cLuVkhu6WRaTomF0tWF4EXMj6ss2HKEdJ8GXN+wpWe5eIBVArkUh5XlRg5q5wplhakiuDjIGuEn2dmW47klQFIdkoLemFxxmuR17RDgcTYvezJPlk-5vkSiXFSlfaqeBvSsZNU2BbsQ1qWcBVEtByyrJlRk2chBxzdhWGtReDx4UduHeCMYwTF2wkrKJWTbH8FyQPA426NuKJPeKABC6AyEYJlPexYQ-X9uh2eabRNHuUqviR1zCtsUxQ9OJwnEAA

**Comment by jheer** [comment]
Thanks for posting! This particular use of layout is a bit tricky...

First, layout of headers and titles was designed primarily with individual text marks in mind. As a result the layout defaults to placing the x, y coordinate of the header/title directly adjacent to the edge of the nearest grid cell. You can adjust this behavior by using specific offset values. (Note that alternatively one can use normal grid cells -- without explicit header roles -- that act as headers if desired.)

Second, the `title` directive intentionally tries to place the title *outside* the group width / height. If you want text labels *within* the group width / height, use a text mark directly.

Third, by default the layout uses the complete calculated bounding boxes to determine positioning. As a result, including strokes in the group boundary can affect the layout placement, potentially resulting in suboptimal alignment. You can tell the layout to use the group width / height values (instead of the full calculated bounds) by setting `"bounds": "flush"`. Or, you can avoid using strokes and avoid internal elements that exceed the group width / height.

Combining these concerns, here is [an example spec that I believe achieves your layout goals](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJBSNq+XQEYADO7tQA7owMsbqJeJhrUMugANrC6ANpKEMCQEag6OA7IhsgATgASyE4u8lAUUaxpYADM7gC+3onJ6Km6kHjMkcj5hXgKJWUVAEy1SgC63pAY2QDWMTjxEIkJC60AnoQVkNTZ3KyExgvL2x0t8NyRrKgyALRteMf1y8gypwYVoAcHkLsG6HhvSx8oAAzRiRSK6JKlc4bbLIIx1AEfDLdCGQMIRcHpW4dLrOHoIwGfPwBRCo9FRFrEwI1REQGmAglIyYzOK0sDvQn2PBrDZ-AAePQegMgTxe-05n2+v3FEs+fNRIOQkSMOCSWx2e3SVNJdSgqFYkR6OHcdFEjNl9hWCsYSpV7M2212LUceMguomBqNYBNZqFEsgUScclVkCh5ROTz+2Tdfs5kHY6FgSssb1D-RaqH8BmO5otrWQAtRYY2kXQKx2eDA2J0udlkCBsjwAGUtKni24BrX-Q2ZHgAOoFV0h9vpdhneFsg70iXThmIkZLXMcz7c9YtdVOv2QI4bU7nS5XFBZaNb0XcV4QtlfQg-P6XusgsFF9PpLbIJ4xye4QcuEPkzHfseuIuF2nzcPo8DMFaw4vt6dCdrGyzamSQYUlq-gsGApBgAMbpsrOCxdhM6DTLMYDzISy6Eqsa5YgWgpfiKzznjKdZSneqpfnK1q2qiG6ar4GE6sUHqGroPqgdR0H2oqyp8Y6AnIq67r6mJxqmpJwqBuEz7QhGvY5J+FrLAmSaRCmunhukmbmDmiHCvyXqQrBGTHq4RnGcCjYttolkVAAHARnJBR8IV0vOi4PFRXI8uuCn7EiZ4XpxcaRoZKX+shf6oQBkDalhOEeXGLq-va-7Oj++L2cCoIAc5enpOZeLsHpYVgCFRHMmRFGAtFSKrry9EJalzHJeyXFQGl0YZcZ+aFjBDVQI57maUipnJjIbYuWoextVOX5tSFC5TlFiI0Rs-HDYcZy7mcFzXEerwnmdSWsUi7FvcKj51Wmi3xq11WQOB6CQdyfniRpgMlU5aI5RVQGVUV1FZWVcPoSSBW4YdiKdSRLJzGyfUrrFdGFoDr33nmH2U7N8ohrJdpqvF6PUiJqlehJ1WfNJSQM-JGoVSiKmehDvoTfY2nBvaI5QPAU1I3W63mZt4PWVmdni0tQ0LVZgFPVjXPLD2zatqrYCBRNe3tfhEUnUsfXnXFAunqNn2PAZ03jXWKNJOVLOIJjCtItDKHhGh35C4D31m5ATX4G+H7YwyW5daynJE8sA0tI5V3ChTM3+vLBd1jnOuDQKBua-GiYbVtf07XhxlW0nHzHYRozjKW5aqDTyhNVLAZPg8kByx7uh4Nk5TD9WABC6AyHaISfI9ORzwv4nD2YFhWBvSxA0CQJJk5Z17vdAAq7Spn7S2X8BVUn3dlz5MeocYvDT13437d0uM1a93NXpNhPByFEKsl9IBKBpDSIAA).

**Comment by blset** [comment]
thank you very much
