### ISSUE TITLE
Add array filter to vega expressions

### ISSUE THREAD

**Issue by melissachang** [vega/vega#1717]
[Vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7QECJAA2yAGZ5dABkV2oawroCMAOxedpAATozU+B4h9uzcBNyoAQBsSgC+IZAA7owGLLoATAAcAJx0pcUArADMVf5VKYVVWbB4AJ5OupDwyA4OxvYG6HiYOADaShC23lAy6Kg6OJDSrGG9APrug7OQFOgOrMiwupOzdjPn9s7ovXgb+4dLUM5oBzqxVz3crDJuOEEUp4pl8LKhFkYcDcHLBkJ9zpA8MgAB7-F5vJwAwJAnZXKDcfQARyOujwYSOIO8mUpFxp3kgNzuDwOJOWGC68N28B+fwCgVEwLxQ0Y4OQkLA0NhnPpSNR3XZyCxAtxXwJ6GJzzJFLx1Lxly+jOQ90erPRCpVCO5vzRgMFQsgYIhuklcLpoVlaIZGMVYFtFt2ao1zoOsLduqu+oRhuNLOekHN0tCVt5WKBieFovFLvTPhRnoVSu2OcggdNLrDNIAuiDw9MaZB5otusNRlt-Ssfus46su23OYiwugZLBnNwwskJm7I7sOoQ46Px6wHJhiyjCGFmyNWKhxgAdBm3I3Mp77ysAXgv+9eCv3YAA-GB3GAcC3t3uD0yTchTxez-ub5A96+s+YCFP69LoCcyztBs0bHkcGzSGE9yWAYKKQBW5zVlSSiVq0kTzDCpwgtODYLHGMFtMgfj9l+ug1P4NafKRjZxigkTRP2rCEC2cbsEOBiwPovQABQGEk6CWCJADk7TSQAlHQThWCw8iPnQoiFGp7h0P4hTyWAABUYCUUifg1rhWQYGEADWUFgGctIIqx8roLZJz9rOcZhMg8BuP2bSdM8jkIvxG5Vv2zhhEkNhug6IxjFALboG2NK1qEyAyNyaGxXikDcbxuX2vAaxIUVQpQHRyyENwlhIuFFXpVGjD9MRFV1u17rHJ6r47vuyZ4KeYC-mAMhLg4YAAD6TWAjCwAAcug81iVufXfNap7yeBXxVaN41ulSOYdZ1UAIO83Tcg4Y7bc1fTig6IpOgddjpM9eHPSWwnMO05X2mdXTLGq8DfTdoTOIwd3dKWOjPU1M7cNwDh4Iwfg4NOCIaNQhHdNJ0kANS9e+HqnhhjXFsiv15f9cYU0dLwQw490DaTQpw-SyJgWjz32NT3S09zlWxh4sPFj9XOdSs8DndBoPXAz91wXRIsfexURoujuy8zLdOQPxMjilqyCw5hsyvThEDvTzUtOPZIVgCx5F8+2XndA4ljIG57biRgliU6EyWbq2RZxeDkPLMzaX9oOVjBW6drnBrPMEQc3S5PkiAs+cZuzJbuwyIwvSkuSroIto0VF9qL3MfWLna-WLvLHrRj9t7klyOLoIJYHKXB3loeM90itC4mHbIX79IEvKvvFv390wUPTyIWOKH6+hJuHfW0fUM8GsrGZ4+hJj2PQYh+-r1X9ZmBYVgAJIyDIyAbjgOmaf2V+WNQADyqiPx4ulafWA4BFhYb28A7Js4dEbXU8u0OcUMwjXxTi3CSvsO4IgDssZKfYQ7y2bI9MU21R5okNpHTeQ5t5tS+AAYlEFLdgBhRCEKoewV4-hnDbCrExEiNdHaAy+h0Z2sC4w1Tql7FB7d7ZxQwUlBK2C+64L4eqEkI8kLEOLqQhEW9Y54njrMRiWELIWyyOgZExxKHHXpFrKA-MERjghimKA8REjJH7NQCIWYQwl12MudgfQABisg8AAGUtDPH8Lo+wPj-GHFgBnHAht+xRIcJ-KgYRlyozAAk+uBcbIAGEeTqzikfFO4dkAtREmnFgpABRbQ0bsTQqF0IAi4WA+sVjIA2IDBETKnonFqBcfWNxeQgnWwou2IZBti6eRyfk60B8VjJwGKU8plTEDVPcLUrOyCfYSOzPWJJ9k9kIgwMiAAoqiHpMR6yoEsOcpEDiIk+ByYczx-YGmrwps-FpTlNajO6D9fsdjLnLCcK4cZ7jgwwi8fSJJAS-ghO0AEABCIkkABkRTMCRY8yA7y0KfN9P2TK2Ud5xQOQfewdVH63GRlQCu0KvgFRGCSiWahEbIwyYnTWizu4yR7JsdwClAIC2zjqc+EARVgGzrnb4MhwbWDQcoZEc0-YOnEfkq6T8oBUPQMgdgNR+LgryOq66ywqG6rFC4dsSTjWasgFQmoDrnBVDAok9AviHBws9AAWUCbCMIg5-L7Ldf4wJAB1MpatdBVHcNipJAAFQw195VgFKNM+AdlIWhlAaEExc0ACaKqbkyDucCsANR3CGMlSAdIQA)

In the above editor, if you hover over first bar the tooltip says "female: 1760". I want the tooltip over the "female" axis label to say the same thing.

If there was a filter function I could do something like:
```
"signal": "data('source_0').filter(v => v.facet_value == datum.value)[0].count"
```

Here's a workaround using `expressionFunction`.
- Go to editor link
- In Console type `VEGA_DEBUG.vega.expressionFunction('getFacetValueCount', function(facetValueName) { return this.context.data.source_0.values.value.filter(v => v.facet_value == facetValueName)[0].count;});`
- Change `signal` to `"datum.value + ':' + getFacetValueCount(datum.value)" `

However, it would be nice if I didn't need `expressionFunction`. One downside of `expressionFunction` is that I can't figure out how to get `import * as vega from "vega";` to work. (`vega` is undefined; I think there's some circular dependency problem.)

**Comment by jheer** [comment]
This request would involve adding functions to the expression language, as well as higher order functions that then accept them as parameters. For a variety of reasons I don't think we are likely to do that. An alternative might be a find operation that given a key and a value returns the subarray of objects with matching key/values entries.

That said, if at all possible, I would recommend creating a derived `data` set that you can instead access in your axis tooltip property. For example, with appropriate filters and/or aggregations you might find a suitable solution.

Also, if helpful, the `datum` objects for the axis also have an `index` property that is a fraction between 0 and 1. You might use that to help determine a lookup key.

**Comment by melissachang** [comment]
Thanks, `datum.index` worked great ([vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7QECJAA2yAGZ5dABkV2oawroCMAOxedpAATozU+B4h9uzcBNyoAQBsSgC+IZAA7owGLLoATO6eJrB4AJ5OupDwyA4OxvYG6HiYOADaShC23lAy6Kg6OJDSrGF1APruTX2QFOgOrMiwul19dr0b9s7odXiTC0vDUAAS6LBgAOoA4gDKYAAy3NlgAMLcVGHo1MhgAEIAQQAsrNtlB4NxWDI3DhCgBWADM8Ni20gFlQQyMOF2DlgyFRG0geGQAA9YWcLtd7k8Xu9Pshvr8ASC4Uj4WC0dx9ABHZa6PBhZbdPqZEXeLZo3b7Q6Lfkjc6XACipKSfyBoMJc0h0IpCORWu86MYmOQ2LAuPxhtCJPJNUVYBVapZwLZyM5RO56D5J0FwvBYvBkqJ0uQByO8spl1uD2erw+Xx+fzeACUQR7tVCYUUkaJrc0TVjdJaCeK5raKZAHTHafGGUzk2nXWB9aIM0avT6BULkGWIIHtsG5qHw3KTlWqU6hu8m+3Qjrs26833QhiizjFlaV-YK-bJ6rp6nWS3c3P7J3I37ewHrUOjSPZcc95dAap1M6AGpvABiZ4hWb1eF3GXcEC1Nc0S3zHwyUrB1XzUaRpy-b82WAv9IAvX0exXAcNjvUIHwjccHTeRAwjAABNMBkPQhcKX8QpEURKDjXA4tN1LUDoLtBUqVI8iqOQnAGKY9DMO7f1tlwvp8J2PYw0fSMJ2jGlTkiRB6UTZkNVogDdERUouNY9cLQ4ljd14lSHjUqJNMZJMXRwAyxN5S9sJvFdZKgQix2falrPUuyGxndMWLo3QUhYtczXYvFONA4kYL8msbI0hN7OZI9mxSFzvTcySNmkiVt28+TRyfSz-NrIKHJ0sK9LdFESuMmKNzi8yksqms4xq7Tj31DkWPEtr8Rw29mp8iqo0dA91VC5rwsaqLC1a0z2uaizpqnObmwG3KuxG68pPGozJqU6saR69Lgqy3TdRzA1muiiCzI2zrpu6ulrocrKl32yMSzGzyJrKxTiP3Z1bvq+6lqelaXvWozNuUmbIabP6htck5AY8oMQZlIi-Pg98kJ-O7FxPR6jOe2KtyR96UeJxC-iEk80MxvLsY4oG8dO0HCcq-jKOosnoYpgblrYw6Op46ahcEn9hMYxF-q5uKecHfGFIFj7VMC76+s1BaGspprqfh2n4vBRLZZRlL9frWrj2cjmDrW0bcc1vmCd8rq9dsg3G3mozFtNyWTMgt7bYugKA8dzL0bAHLXYB7mAzLABdEVpKHSABiGGoWjaaYM1GKEJnHMYK5LrViW+GRYGcbgwmSTpgaRipCHHJuW9YBxMBYslCDCQvWlYVAOgAHUgM7kGnjOAF4l+nmPqsDl1p7AAB+MB3DAHAi-HqeZ-5sd56XheV4h6cNU3nf-H3sBD4n6fZ-P5e7cur746D4E75bR+z9j5v0gIvD+DptohT-pAbeYBESALHi-E+Ptjjv0vozN8zMRbfn-qIBBeAj6v1Pqg0BF8r6XHltg-+8J8GEOQdrM+pDwFUntnHLSO1-4pFoUgkBYD0Gr1Sr1X+-9AiPwABzoQuDUCokxZ6TGkGEA4lgDBkkgDhTO2clAZyyBoagAw8RrBFLnfO44ZHlGQH4WuOtET+GzqiYxgxxwoHUm4WurBCBF3HOwdAMgDCwH0HUAAFAYJI6BLCBIAOQVAiQASjoE4KwLB5C7zoKIQoyT3B0AYjEsAAAqMAZiSR+E0RAbRJgMBhAANarDbsVIkJiagVOqaXSoXcahhGQPAVxZZRiVGqLUtE3iR6Z1rs4MISQbArnRK0doUAi7oBLmWIqUBkAyEhCoyZ1t3GeM2QleA4wFG7KMjrUw3BLAkmGVxZZ95GANEMVxHoJUjQknKKPAhSC6LzzABfMAMg+4ODAAAH0BWARgsAABy6BwXBMQcfT5oCYl-iNDrP5DQnlgGuTJdF9gECLHHJCBwzckUEUYPUc0LUjDovSCVMpRkvTwGYBUI5CVcX9KgPSxlxKZ6kocOS8SJVMU7m4NwBweBGB+BwF5HFkR9E1AiREgA1EA6eFZ55qKuSxUkzLrasvHFqqCOweXkvCgKzVhRtVol1TUfV6L5i+13qa5qTLJW2qtSMJlBrvJGpqLPdVoFBW4GQC4i1RI3VQA9ba7xviJJHXTnG0UJSwC0qgLqmpYB1ibB6Q0kYNqiStPHA4SwyB0Aj1riEjAlgQ1zJmW8hZMxrTcrJTUE1hVa711+Pc7YhkvYsplYsGouR8iID9YVEZWbGB1BjbXbQ4yY12KMVmxx0iWmdy8T4owZbQmVpddbeZtaa5TOcN6kYvqG0KIpF5DCEqoCoErSxI9Tb3WyOIcseRzclG+NUeo1tPT20nHwr0ixVbpV6P7U+8xxT43eGWaYQwFgrAAEkZAyEZB4VJ6SelmHg9QAA8qoVDOBMkMVrosGVHh511LmNm-8hLS09PzTUZu8H+2borXIHdaI90jHmQe62D7eWFwtme99c6f1Ej-Z2okABiUQ8B0DsAMG2BtUn2DOGQP4ZwMwNHQfsYuguIwOWVBXW0kYhAznZlY2E9jYAANcercXeth7j3sqxnOMuijROijbT4jtAyNjdo2LYjYWdoNaKyOgUkKxJM2Z6WGyAua5jN1JRTSA8REjJFrtQCICM6ZzH7uweo35ZB4DuFoE4-gAuhHy4VpYsBh04CvLXarDgcNfH7texr9GJ2VI+DDGLOq+2NBGHUW5gTB0sFIKIdwiKlnTuUao4SFHM2hrk2y+LpckurMrGltQGWelZbyHcVbpjS4HfNJ1vN3XesUwA7o2Vw2g0ODG3kCbU2ZtibmOWqzlsmvyfqGmyORIMCkhVCSCmlX7C3pkKDrbMQuvwGadLHpmh5tasI0tx5K28XLtrptlLThXCneyz9npzWiswlK9oAIGGiTNceCaZg1OIdQBR5+tHYB-C11Wes-9Uzmtpsvec+yXTGBUCnc1bZrRecPJ8MK0V4rgNzDu2B+z486BETAAqsAEScARM10-GZkSq5THcLEjoz8uBs7yWAQJCTqAsBhW0I35cTexJiaQQoYAAC0HOYkZzoC2h51KrnfoTaF0pWRIQyCPdYDj9gItgoteiLdMgPi0ZqFJ9AyB2CIm8UTvIaeiUjCk9ns0LhS7NcLyPYvTFETOHhOa37BWHDk8rMCYr+IwjfG6bTv7LfitXCDVECkQFmeOD7wABTg5YWPYAACctcxUI4B2nOw0lIAJ9gBRJPUOYcUwMom6l6QgA)).
```
signal: "datum.value + ': ' + data('source_0')[datum.index * (length(data('source_0'))/2 - 1)].count"
```

Not adding functions to expression language makes sense.

The alternative sounds good. Although matching on key/value might be restrictive. What if you have an array of strings? Or an array of nested dicts? Maybe filter could take a string, and an array element would match if any key or value or element matched the string.

(Wanted to document here in case anyone else has this problem. I could not for the life of me get expressionFunction/`import * as vega from "vega";` to work (I get `vega` is `undefined`). I suspect there's a circular dependency but I couldn't find it. I even created a [codesandbox](https://codesandbox.io/s/1rnyr5w8j4) with the same imports and `package.json`, but the codesandbox couldn't repro the problem. I'm using create-react-app so I can't use [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin).)

Since `datum.index` worked for me, I'll leave it up to you whether to close this issue or not.

**Comment by melissachang** [comment]
Actually with other charts, I encountered some issues with `datum.index`. So the signal expression is more complicated:
```
signal: "datum.value + ': ' + data('source_0')[round((isNaN(datum.index)?0:datum.index) * (length(data('source_0'))/2 - 1))].count"
```
So I think it's worth having a filter function.

I'll file a separate issue for the `datum.index` issues.

**Comment by jheer** [comment]
OK thanks! I'll look for your new issue to see why `datum.index` might be coming up with a `NaN` value. I don't think that should be happening.

For an array of strings or other primitive types, we already have `indexof` and `lastindexof` methods. Nested data structures should be pretty rare in this context -- and perhaps better treated by creating a derived data set (e.g., via `fold`, `flatten`, and/or `project` transforms).

**Comment by roying** [comment]
@melissachang 
A simple solution for your example is to use text marks (with tooltip) instead of axis labels. 
Here is an [example in Vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7QECJAA2yAGZ5dABkV2oawroCMAOxedpAATozU+B4h9uzcBNyoAQBsSgC+IZAA7owGLLoATO6eJrB4AJ5OupDwyA4OxvYG6HiYOADaShC23lAy6Kg6OJDSrGF1APruTX2QFOgOrMiwul19dr0b9s7odXiTC0vDUAAS6LBgAOoA4gDKYAAy3NlgAMLcVGHo1MhgAEIAQQAsrNtlB4NxWDI3DhCgBWADM8Ni20gFlQQyMOF2DlgyFRG0geGQAA9YWcLtd7k8Xu9Pshvr8ASC4Uj4WC0dx9ABHZa6PBhZbdPqZEXeLZo3b7Q6Lfkjc6XACipKSfyBoMJc0h0IpCORWu86MYmOQ2LAuPxhtCJPJNUVYBVapZwLZyM5RO56D5J0FwvBYvBkqJ0uQByO8spl1uD2erw+Xx+fzeACUQR7tVCYUUkaJrc0TVjdJaCeK5raKZAHTHafGGUzk2nXWB9aIM0avT6BULkGWIIHtsG5qHw3KTlWqU6hu8m+3Qjrs26833QhiizjFlaV-YK-bJ6rp6nWS3c3P7J3I37ewHrUOjSPZcc95dAap1M6AGpvABiZ4hWb1eF3GXcEC1Nc0S3zHwyUrB1XzUaRpy-b82WAv9IAvX0exXAcNjvUIHwjccHTeRAwjAABNMBkPQhcKX8QpEURKDjXA4tN1LUDoLtBUqVI8iqOQnAGKY9DMO7f1tlwvp8J2PYw0fSMJ2jGlTkiRB6UTZkNVogDdERUouNY9cLQ4ljd14lSHjUqJNMZJMXRwAyxN5S9sJvFdZKgQix2falrPUuyGxndMWLo3QUhYtczXYvFONA4kYL8msbI0hN7OZI9mxSFzvTcySNmkiVt28+TRyfSz-NrIKHJ0sK9LdFESuMmKNzi8yksqms4xq7Tj31DkWPEtr8Rw29mp8iqo0dA91VC5rwsaqLC1a0z2uaizpqnObmwG3KuxG68pPGozJqU6saR69Lgqy3TdRzA1muiiCzI2zrpu6ulrocrKl32yMSzGzyJrKxTiP3Z1bvq+6lqelaXvWozNuUmbIabP6htck5AY8oMQZlIi-Pg98kJ-O7FxPR6jOe2KtyR96UeJxC-iEk80MxvLsY4oG8dO0HCcq-jKOosnoYpgblrYw6Op46ahcEn9hMYxF-q5uKecHfGFIFj7VMC76+s1BaGspprqfh2n4vBRLZZRlL9frWrj2cjmDrW0bcc1vmCd8rq9dsg3G3mozFtNyWTMgt7bYugKA8dzL0bAHLXYB7mAzLABdEVpKHSABiGGoWjaaYM1GKEJnHMYK5LrViW+GRYGcbgwmSTpgaRipCHHJuW9YBxMBYslCDCGoEEWZAAAoAHIx6cSZm4MRkp-kMAi9YVAOins7kCnjOAEp0IuGoKkmbfJmkMIDksRfSUgHDM+zpQM6yDRqAGPE1hFXP8-HE-ymQPwtcdaIn8NnVE39BjjhQOpNwtdWCECLuOdg6AZAGFgPoOoE8DBJHQJYaeFQp57zoE4KwLAV7uDoKIQo5C6AMT3mAAAVGAP+JI-CPwgM-EwGAwgAGtVht2KkSH+NRuF8NLpULuNQwjIHgLAssoxKjVAEWiZBI9M612cGEJINgVzolaO0KARd0AlzLEVKAyAZCQkXjo628DEE2ISvAcYF8HFGR1qYbglgSRqK4mY+8jAGify4j0EqRoSTlELq0deHQAA6tQAJxIzmAAAvKksAMg+4ODAAAH2yWARgsAABy6BClYKiRvOJdFEkHygkaHWGSGihLAH4mSTT7Cz3HJCBwzc-z+PqOaFqRgmnpBKpwoyXp4DMAqK4hKHSagTKmb07yjB+nzKxnfXx5luDcAcHgRgfgcBeXaZEd+NQp5TwANRrwqTbPAiSNmgRafYW+hymmjHgOPGot9anLNWSMcKJUnlQFJIUGZ1s5kjG+W8nW7hAUsWma84JUAIVQGmT8yAzgVkOAGdvB5ntrbQKiBSI5yKPlKNRUsyAyDUESSOuneloowEgGZcywR5ZO7jl3BorRrcwD4T0W0SJxcZimNrhYqxJx+V2NaJKpQG1tm7P2WCtEr9TkjGuZvCsu88XHWai8vl0LfZgAALT+FhZs1lCUEUGqRe8z5Iw0VvMxX80qPsnxwstdbAw1rgDzCNfCMUUdiWjBOYsIV0St78zHNqoFkBFgnJsH6qa4QYGQFjcg-EDhLCSqTUpXwabPWMsKo-S1YzSXj34WAdYmx5HCMheIjlNQs0yGQOgEetdsEYEsMq5o+ihXGJmNaDFWKBkAsKrXeuvwgnbEMl7WZobGgjFyPkRAOrvAjI2GWo0MhGB1FpbXbQWjaVMrZduyBx8G2SJGNSowHacHdsRWiIx-aa66OddimouKh0X2Jc1bkIju0sXfQMk+Z8f2TGvmSNddgN2ignSgqdj6iT-wOTa+db8w0OvPqw6D-ZRXyLMBYKwABJGQLaR44AoVQ2uhHLDUAAPKqEZB4Wh1D5Hxrfh4E9NahHnv+TsnptcJHjgXpYMNd6u1yCQ3MZ96r9GvutsBwuFtv3NwpFefDRJJ0nGrUSAAxKID57ADBtiHXp9gzhkD+GcCKzd3GQm8YLiMBZlRL3jkIJ47MEncFSbQ0SWThj5ODrfSOtZnM5xl0vse8d8jtPTo2LOjYoC7PrsUF-WtfHy1zwXsx7zD6q120ul9eOO0FBbVmi6MrhXYzFa0kHTU5W0ahWmkzT8os5ZkWFjRFe1WwCpV6qVnrMc+sOzqyFUEW7Qhxc6J4MA-gV7ULAMxMAeYwAoiTivQIWd10stLVkdApIVjxb86EFFkAoWegiBYys8REjJFrtQCICM6ZzH7uweo35ZB4DuFoE4Zra5vY+0sWAq6cBXgB+gd7Dh6NfH7qh8H8i9nwB4R8GGJ2jSqswxCZAASJ7LpYKQUQ7gD6abmJoSD+rkswfAfIs7F25jNxWRTKlCQ1D3fkY9vIdwyW-1Lpz80COiRI5RybflmPF3Y9x-jxAhPifQbMeie9vnI5EkBx-aW8iMCkhVCSCmiXQioEsDr67MREe7rERrok5PUFQco-Z9HWXee10ZybkYThXClzV5WnGMGn5ZEhDITF1hpNxtJAU5VivJMfG6RRqAen0DIHYIiZBfOnvR56SMPTiezQuE95D+o6fY) that also includes using a scale as lookup instead of nested 'if'.

**Comment by sladiri** [comment]
> 
> 
> @melissachang
> A simple solution for your example is to use text marks (with tooltip) instead of axis labels.
> Here is an [example in Vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7QECJAA2yAGZ5dABkV2oawroCMAOxedpAATozU+B4h9uzcBNyoAQBsSgC+IZAA7owGLLoATO6eJrB4AJ5OupDwyA4OxvYG6HiYOADaShC23lAy6Kg6OJDSrGF1APruTX2QFOgOrMiwul19dr0b9s7odXiTC0vDUAAS6LBgAOoA4gDKYAAy3NlgAMLcVGHo1MhgAEIAQQAsrNtlB4NxWDI3DhCgBWADM8Ni20gFlQQyMOF2DlgyFRG0geGQAA9YWcLtd7k8Xu9Pshvr8ASC4Uj4WC0dx9ABHZa6PBhZbdPqZEXeLZo3b7Q6Lfkjc6XACipKSfyBoMJc0h0IpCORWu86MYmOQ2LAuPxhtCJPJNUVYBVapZwLZyM5RO56D5J0FwvBYvBkqJ0uQByO8spl1uD2erw+Xx+fzeACUQR7tVCYUUkaJrc0TVjdJaCeK5raKZAHTHafGGUzk2nXWB9aIM0avT6BULkGWIIHtsG5qHw3KTlWqU6hu8m+3Qjrs26833QhiizjFlaV-YK-bJ6rp6nWS3c3P7J3I37ewHrUOjSPZcc95dAap1M6AGpvABiZ4hWb1eF3GXcEC1Nc0S3zHwyUrB1XzUaRpy-b82WAv9IAvX0exXAcNjvUIHwjccHTeRAwjAABNMBkPQhcKX8QpEURKDjXA4tN1LUDoLtBUqVI8iqOQnAGKY9DMO7f1tlwvp8J2PYw0fSMJ2jGlTkiRB6UTZkNVogDdERUouNY9cLQ4ljd14lSHjUqJNMZJMXRwAyxN5S9sJvFdZKgQix2falrPUuyGxndMWLo3QUhYtczXYvFONA4kYL8msbI0hN7OZI9mxSFzvTcySNmkiVt28+TRyfSz-NrIKHJ0sK9LdFESuMmKNzi8yksqms4xq7Tj31DkWPEtr8Rw29mp8iqo0dA91VC5rwsaqLC1a0z2uaizpqnObmwG3KuxG68pPGozJqU6saR69Lgqy3TdRzA1muiiCzI2zrpu6ulrocrKl32yMSzGzyJrKxTiP3Z1bvq+6lqelaXvWozNuUmbIabP6htck5AY8oMQZlIi-Pg98kJ-O7FxPR6jOe2KtyR96UeJxC-iEk80MxvLsY4oG8dO0HCcq-jKOosnoYpgblrYw6Op46ahcEn9hMYxF-q5uKecHfGFIFj7VMC76+s1BaGspprqfh2n4vBRLZZRlL9frWrj2cjmDrW0bcc1vmCd8rq9dsg3G3mozFtNyWTMgt7bYugKA8dzL0bAHLXYB7mAzLABdEVpKHSABiGGoWjaaYM1GKEJnHMYK5LrViW+GRYGcbgwmSTpgaRipCHHJuW9YBxMBYslCDCGoEEWZAAAoAHIx6cSZm4MRkp-kMAi9YVAOins7kCnjOAEp0IuGoKkmbfJmkMIDksRfSUgHDM+zpQM6yDRqAGPE1hFXP8-HE-ymQPwtcdaIn8NnVE39BjjhQOpNwtdWCECLuOdg6AZAGFgPoOoE8DBJHQJYaeFQp57zoE4KwLAV7uDoKIQo5C6AMT3mAAAVGAP+JI-CPwgM-EwGAwgAGtVht2KkSH+NRuF8NLpULuNQwjIHgLAssoxKjVAEWiZBI9M612cGEJINgVzolaO0KARd0AlzLEVKAyAZCQkXjo628DEE2ISvAcYF8HFGR1qYbglgSRqK4mY+8jAGify4j0EqRoSTlELq0deHQAA6tQAJxIzmAAAvKksAMg+4ODAAAH2yWARgsAABy6BClYKiRvOJdFEkHygkaHWGSGihLAH4mSTT7Cz3HJCBwzc-z+PqOaFqRgmnpBKpwoyXp4DMAqK4hKHSagTKmb07yjB+nzKxnfXx5luDcAcHgRgfgcBeXaZEd+NQp5TwANRrwqTbPAiSNmgRafYW+hymmjHgOPGot9anLNWSMcKJUnlQFJIUGZ1s5kjG+W8nW7hAUsWma84JUAIVQGmT8yAzgVkOAGdvB5ntrbQKiBSI5yKPlKNRUsyAyDUESSOuneloowEgGZcywR5ZO7jl3BorRrcwD4T0W0SJxcZimNrhYqxJx+V2NaJKpQG1tm7P2WCtEr9TkjGuZvCsu88XHWai8vl0LfZgAALT+FhZs1lCUEUGqRe8z5Iw0VvMxX80qPsnxwstdbAw1rgDzCNfCMUUdiWjBOYsIV0St78zHNqoFkBFgnJsH6qa4QYGQFjcg-EDhLCSqTUpXwabPWMsKo-S1YzSXj34WAdYmx5HCMheIjlNQs0yGQOgEetdsEYEsMq5o+ihXGJmNaDFWKBkAsKrXeuvwgnbEMl7WZobGgjFyPkRAOrvAjI2GWo0MhGB1FpbXbQWjaVMrZduyBx8G2SJGNSowHacHdsRWiIx-aa66OddimouKh0X2Jc1bkIju0sXfQMk+Z8f2TGvmSNddgN2ignSgqdj6iT-wOTa+db8w0OvPqw6D-ZRXyLMBYKwABJGQLaR44AoVQ2uhHLDUAAPKqEZB4Wh1D5Hxrfh4E9NahHnv+TsnptcJHjgXpYMNd6u1yCQ3MZ96r9GvutsBwuFtv3NwpFefDRJJ0nGrUSAAxKID57ADBtiHXp9gzhkD+GcCKzd3GQm8YLiMBZlRL3jkIJ47MEncFSbQ0SWThj5ODrfSOtZnM5xl0vse8d8jtPTo2LOjYoC7PrsUF-WtfHy1zwXsx7zD6q120ul9eOO0FBbVmi6MrhXYzFa0kHTU5W0ahWmkzT8os5ZkWFjRFe1WwCpV6qVnrMc+sOzqyFUEW7Qhxc6J4MA-gV7ULAMxMAeYwAoiTivQIWd10stLVkdApIVjxb86EFFkAoWegiBYys8REjJFrtQCICM6ZzH7uweo35ZB4DuFoE4Zra5vY+0sWAq6cBXgB+gd7Dh6NfH7qh8H8i9nwB4R8GGJ2jSqswxCZAASJ7LpYKQUQ7gD6abmJoSD+rkswfAfIs7F25jNxWRTKlCQ1D3fkY9vIdwyW-1Lpz80COiRI5RybflmPF3Y9x-jxAhPifQbMeie9vnI5EkBx-aW8iMCkhVCSCmiXQioEsDr67MREe7rERrok5PUFQco-Z9HWXee10ZybkYThXClzV5WnGMGn5ZEhDITF1hpNxtJAU5VivJMfG6RRqAen0DIHYIiZBfOnvR56SMPTiezQuE95D+o6fY) that also includes using a scale as lookup instead of nested 'if'.

@melissachang Do you still have an example, since the editor cannot parse the spec in your link? I also was looking for a find expression, and I think that I managed to use the scale function, but I cannot recreate it anymore.

**Comment by melissachang** [comment]
Sorry, I no longer work on the project that used vega
