### ISSUE TITLE
Subplot alignment

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1747]
Somehow [titles of two v-concated plots](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070pVNwqNkseYpUaAvuqMV4y+DosA2gaGkHjMYsgWkABKOoxK1LBqGkYmyITI-vqQPmKsqCo4ATHcBMhKAPoAKtwYeNyOFbFhCWpQAJIAsgAiAEJNca0Auh4pULAZ8BbBhlAA7oyaLBYAjACsAAyes7jIjNT4Fpvbs5AYJgDWUezoJsk7UOU+mvHU02OnAB7vDw+QAGYOMSaaaQNIZLJQXL5FSjX47SDseKgjCfJFKJI4ABMGzh8JCeAAnhkogBHVjoJRhXRhKiQD47PHwyCE0HoajUNK0PCRHA5bisKltULE3lQcmU6lxOluBmy2bysAeGZQakRKIAcRM3FgSROUHBmTwoOhBUCkAAqgBlCpanV6qAAdW4Zk0C00yFt2t1kBG+sgE2QU30DMg7uWOHWW1DKH2hxwx1DT24L1aIeZ33T+KMgOQwNBhsh-LyZqZ+MRyOyqPRmLAOLLzKJJL5EqpzGlkQZCv1f1Z2XZnOEPKiPkFxtUqtFZIpbZpjBlcp7UHOVz5NzuY0VbiG235SkBbyzRlHVKq4TFkAAwgKhe4QLKgA) do not align:

(I believe that the generated Vega spec is quite straightforward, so this is probably a problem in Vega?) 

![image](https://user-images.githubusercontent.com/111269/55285049-4147a880-5338-11e9-9f5d-e5523eb16827.png)

**Comment by jheer** [comment]
You're right that this is a Vega-level issue, but it is not really a bug. It's how the system is designed.

Title layout (when using `frame: bounds`) is based on the total bounds of the corresponding group. It does not know about other groups and so can't align based on those. If you use `frame: group`, the title can anchor to the (appropriately aligned) edges of the data rectangles.

Right now the variably-sized axes are causing different offsets for the `frame: bounds` title layout. The only "easy" solutions I can think of at the moment are:

- Use `frame: group" instead, if you're OK with the resulting placements.
- Use our old friends minExtent / maxExtent to synchronize axis sizes.

Otherwise, I think we would need some new mechanism of aggregating bounds info across sub-groups and then propagating that information back to a group's ViewLayout... but that sounds like a dataflow cycle and I'm not sure it's feasible.

Meanwhile, there are other problems: the charts on the right are not aligned either!

**Comment by kanitw** [comment]
> Use our old friends minExtent / maxExtent to synchronize axis sizes.

Yeah, I guess this is probably ok (for now), so we won't need to change any behavior.   

> Meanwhile, there are other problems: the charts on the right are not aligned either!

It's weird that it's still not align even [with titleLimit set](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJFYAnMdi070pVNwqNkseYpUaAvuqMV4y+DosA2gaGkHjMYsgWkABKOoxK1LBqGkYmyITI-vqQPmKsqCo4ATHcBMhKAPoAKtwYeNyOFbFhCWpQAJIAsgAiAEJNca0Auh4pULAZ8BbBhlAA7oyaLBYAjACsAAyes7jIjNT4Fpvbs5AYJgDWUezoJsk7UOU+mvHU02OnAB7vD6cAZg4xJpppA0hkslBcvkVKNfiF2PEQRhPgilEkcAAmDawuFQPAATwyUQAjqx0EowrowlRIB9DDiHpB8SD0NRqGlaHhIjgctxWBS2qFCdyoKTyZS4jS3HTpbNZWAPDM8eERZAAOImbiwJInKBgzJ4EFQgqBSAAVQAyhUNVqdVAAOrcMyaBaaZDWzXayAjXWQCbIKb6OmQV3LHDrLbBlD7Q44Y7Bp7cF6tINwyDfVO4yAA5BAkH6iG8vImhm-SCopHoFHxdFgLGlxkEok8sUU5iSyJ0iANkLM7Ks9nCLlRHz8w2qPHCklkttUxhSmW6oznK48m53MbytxDba8pQAt6ZoyjilVFVRADCfIFvqrjFgAA0QZSIgAZRioZirTalyB32AAJo-DsZzxAAop8XICjgAAsGybu4IDSkAA). 

![image](https://user-images.githubusercontent.com/111269/55285779-cd60cc80-5346-11e9-8927-a74a6a286465.png)


Adding `"labels": false` to config makes it align though, so there might be a bug with how the label affect bounds. 

![image](https://user-images.githubusercontent.com/111269/55285784-e8cbd780-5346-11e9-8a45-b3c515e4d71a.png)

**Comment by jheer** [comment]
Thank you! You just uncovered a different bug. Our label overlap logic toggles label opacity, so does not change the bounds. The hidden labels here are over-running the visible plotting area.

I'll have to investigate that further at a later date!

A stop-gap solution here (for issue 2) could be to use a more compact label format (`s`). I mean this as an end user config solution -- not a Vega-Lite modification.
