### ISSUE TITLE
Vega v5 expression function data() throws error instead of returning empty array

### ISSUE THREAD

**Issue by roying** [vega/vega#1757]
According to documentation for Vega expressions:
https://vega.github.io/vega/docs/expressions/#data-functions

> **data(name)**
> Returns the array of data objects for the Vega data set with the given name. 
> If the data set is not found, returns an empty array.

But Vega v5 throws error instead of returning empty array:

>   Error: Undefined data set name: ...

Example in Vega editor (v5.3.2):
https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA0IEJFiNqM9ABtY2MAG1wEMMACQkDamS6VajZoD6eZLDwKwIE58itCAE3RO1v546AAUAOQAHtHhAJSQHiYAvkoQALpKSUA

**Comment by Stephanemw** [comment]
I'm also coming across this - I'd love to be able to test for the presence of datasets generated by vega-lite to inform my trellis autosizing signals and resize vega to fit the div container.

**Comment by jheer** [comment]
Thanks for the issue! The `data` function itself is implemented correctly, but the parser was trying to find the non-existent dataset in order to track changes. However, if there's no data set there's nothing to track, so no problems... I'll add some error catching to the dependency tracking logic so that this works as intended!
