### ISSUE TITLE
Axis disrespects "format" specifiers "" and "," (but not ",f")

### ISSUE THREAD

**Issue by adamhooper** [vega/vega#1760]
Vega Version : 5.3.5

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "data": [{"name": "table", "values": [{"x": 30}, {"x": 100}]}],
  "scales": [
    {
      "name": "xscale",
      "type": "linear",
      "domain": {"data": "table", "field": "x"},
      "range": "width"
    }
  ],
  "axes": [{"orient": "top", "scale": "xscale", "format": ""}],
  "width": 400,
  "height": 100
}
```

[Live example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABN0eTDgDawSDPSpk2KOvYAbQ-KgV0p1slhHtkAB5GAzAAYAvpZ2ucAIwe3gC6XiGKEJAINvaOShCgEMlQegZGLjHmCgnJkHgAnoSGOJCmjDLI6ABOOSlRytwYFUY6quoZJtmWkABmjMimyhmuPrlR1egy1CVQAO6MyiyQuV5KEUqQ6M5xWjrc1QMyeJ3chApQWbOZ8LEXfQcYJ6WQ4ZHzi8s4ACzB75AoRjUfBGIIeEBeIA)

Expected results: axis ticks `0 10 20 30 40 50 60 70 80 90 100`, because that's what d3-format gives when the format is `""`

Actual results: axis ticks `0 1e+1 2e+1 3e+1 4e+1 5e+1 6e+1 7e+1 8e+1 9e+1 1e+2`

A list of specifiers and whether they do what we'd expect:

* `""`: buggy
* `","`: buggy
* `"d"`: gives expected results
* `"f"`: gives expected results
* `"n"`: gives expected results (`0.00000 10.0000 20.0000 ...`)
* `"g"`: buggy (should be same as `"n"`; gives `0 1e+1 2e+1 ...`)
* `".2"`: buggy: gives `0 10 20 30 40 50 60 70 80 90 1e+2`
* `".3"`: gives expected results

**Comment by adamhooper** [comment]
Forgot to mention the workaround. Instead of `"format": ""`, use:

```json
                    "encode": {
                        "labels": {
                            "update": {
                                "text": {
                                    "signal": "format(datum.value, '')"
                                }
                            }
                        }
                    }
```

**Comment by jheer** [comment]
Thanks @adamhooper! Internally Vega uses not just d3-format but also d3-scale, including the `tickFormat` method, which can take a format specifier as input and can add additional aspects based on the underlying data. Often, this is a good thing (e.g., determining an appropriate precision based on the scale domain), but in this case appears to have been confusing.

For more about the `tickFormat` method see, https://github.com/d3/d3-scale#tickFormat

It sounds like, at minimum, we should double check the documentation and, as needed, update it to make it clearer. Going further, we might also consider an additional configuration that ensures the format specifier is used exactly "as-is", rather than augmented with scale domain information. I'll have to think about what an appropriate design might be for that.

**Comment by adamhooper** [comment]
Thanks for the clarification! This sounds like a bug with d3-scale. (Its docs and unit tests suggest this behavior is unintentional.) I'll take my main gripe there.

I'm not looking to make Vega do more than it does today. Just looking to solve my problem (letting users configure number formats).

**Comment by adamhooper** [comment]
Filed https://github.com/d3/d3-scale/issues/169

**Comment by jheer** [comment]
Closing out this issue on the Vega side.
