### ISSUE TITLE
Add window operations to "fill" in missing values.

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1791]
[impute transformation](https://vega.github.io/vega/docs/transforms/impute/) has these methods: value, mean, median, max or min, but in some cases it might be just as good to repeat the `last` value (the one that was set in the previous datum.  This method would not guarantee imputing at the beginning if there was no data, but it will make sure that data will be there ones started (another impute with a value could be used to solve that).

The initial request with a simple code example was posted [here](https://discuss.elastic.co/t/how-to-pick-the-previous-value-when-current-value-is-undefined/177828)

**Comment by jheer** [comment]
Thanks! In data wrangling tools this is sometimes referred to as a `fill` operation, and one could either "fill down" (use the last defined value) or "fill up" (use the next defined value).

Adding both methods, with names like `"previous"` and `"next"`seems reasonable to me. In contrast, `"last"` feels ambiguous: is it the last element most recently observed, or is the last element in the group? Moreover, these methods can not be added without additional changes. To talk about `previous` and `next` we need to have a well-defined ordering, which means we need a `sort` parameter alongside these imputation methods (not just whatever order the records happen to be in).

What we're describing above is a variant of a window transform. This leads me to think that this use case might be better handled via extensions to the `window` transform: the fill prev/next operations are similar to `lag`, `lead` window operations, but with a variable amount of look-ahead/behind (and of course, no change of result if the existing value is non-null). So I'm tempted to add new window operations rather than modify the impute transform.

If any one else has thoughts on either functionality or naming, please chime in!

**Comment by nyurik** [comment]
Thanks @jheer, it does seem reasonable.

**Comment by nyurik** [comment]
Awesome, thanks!!!  Very quick turnaround :)

Do you add docs as a separate commit? (in theory, it could go into the same PR, and just use newer version than currently released, thus indicating that it is an upcoming feature in the docs)

**Comment by jheer** [comment]
Docs will be added in a separate PR for the next release!
