### ISSUE TITLE
Support `undefined` in expressions

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1792]
It seems that Vega does not allow `undefined` as a known keyword inside the expressions, similar to `null`.  Undefined is very useful to check if a value is present in the datum, plus many built-in Vega functions return undefined as part of their normal operations, so it should be possible to use it.

Currently using `undefined` in an expression shows `Error: Unrecognized signal name: "undefined"`

I'm not sure if this is a bug or a feature request.

**Comment by jheer** [comment]
For better or worse, we intentionally left `undefined` out of the original expression language design, in part because undefined is specific to JavaScript, which might hamper future efforts to implement Vega in other places. Of course, the expression language is itself a subset of JavaScript and one could point to many many things that would be onerous to re-implement elsewhere. But even within the JS world `undefined` is a bit dodgy; for example it is disallowed by the JSON specification.

So, I'm not against adding `undefined`, though I do wonder if we might be better served by instead providing a new predicate function, such as `isDefined(value)`, rather than allow explicit `undefined` literals. (Already, one can do `foo == null` to simultaneously check either `null` or `undefined` status, but obviously that is of little help if you want to discriminate between the two.)

@domoritz @arvind @kanitw: Let me know if you have any thoughts / opinions on the matter!

**Comment by nyurik** [comment]
`isDefined()` seems like a good solution that doesn't change language syntax (and avoids weird scenarios where users had defined a `undefined` signal)

**Comment by domoritz** [comment]
I support this.
