### ISSUE TITLE
Support background for text mark 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1820]
To draw a background behind text mark like in Figure 5 from http://idl.cs.washington.edu/files/2019-InteractiveTableRepair-CHI.pdf,  users need to manually add a rect layer and _manually adjust the start and end position of the rect_ to match text length.

![image](https://user-images.githubusercontent.com/111269/58753693-521bb400-8478-11e9-867e-904222f15750.png)

We could instead make text mark support having background (with inset/padding) like in Keynote

![image](https://user-images.githubusercontent.com/111269/58753705-8ee7ab00-8478-11e9-8afe-1bddc0fcf3e1.png)

**Comment by domoritz** [comment]
You can use reactive geometry to do this, no?

**Comment by kanitw** [comment]
I'm not sure, but even if it's possible, it's still much more complicated than having a native support (that better matches user's mental model).

**Comment by domoritz** [comment]
I agree that it would be nice to support it natively but I think reactive geometry should let you create a rect mark that has the same size as the text.

**Comment by kanitw** [comment]
Note: a user is asking for this in Stackoverflow.

https://stackoverflow.com/questions/57564317/is-there-a-practical-way-of-setting-a-background-colour-or-halo-for-text-marks-i

**Comment by domoritz** [comment]
One issue here is that there is not enough documentation or examples for reactive geometry beyond  https://vega.github.io/vega/docs/marks/#reactive-geometry.

**Comment by jheer** [comment]
As @domoritz points out, this is exactly what reactive geometry enables. Here is an [editor example ](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwARgAMuxREgpG1fFr0GQSyGvR5MOANpKIwSDPSpkWyABt0dmQ-WAUoCnQ-VmRQ53cAoL9fABVkAA88SABfAF0spRzFGwwAJwBrWLAXCDdXGsg8AE9CHxxIahLuVkIFOqNYU08QrWqasfdPb192am4AMznYZEz5cMjorQBmfLGIQr6oUoqR3ZqD2tOxjy9WqDx0vCPey-qmlt97jOeXqDnO1C07jsDl8CWCoSyhh+kGQMng3DUt1AP3qsPuJUB50uDQegMgc0YwTUoMCwWyUJRRjSeIiUVuol0kKxp0gjRp63pjIplPxsjwAGVGAAvJGQWkbHDaAAsTMp9Uig3ZdN88DRyAxsrlUHY6CWfkYMlF4tukFQ6jUfh8O0p1pempekCFBsR1MlWPtu2R0MmJpKyHgj3Q5W+Drevv9K2Zv3+eOBjjuDyeHpZsPhiMxcphMnRGa1kFdYHcBKJ0y6MjUsDoaW0YUgnVY5a0eBK0VWkHmi2WeIG1CGvgAtDMO0tMllk9C0gAmPHFvzEtrsMsVqvTtv1xs4ZutqDDrs4dw9vsL2YLEfZccOtn7-GEuelhvLxo1tdLpst5Bt3eZa+HyIDoenl2Y7ciirLTtes7ztqS6Vo0q5QOuUFbh+O6Ad+haQL+STHl+54gdCBJ+NhGHGr4CqquwyoXtisDNtwZRGhyvi0cgwSURsto-JxpzcTUvE5HU1oCSAWRAA) of adding a background rectangle to text. I encapsulate it within a single group so that local parameter signals can be defined and the zindex layers affect the internal group content only.

As Vega provides the necessary "assembly language" primitives, I think "syntactic sugar" for generating these designs should occur at the Vega-Lite level. The current Vega setup allows for using the full range of text *and* rect features (cornerRadius, etc) without changing the surface area of Vega. One might also use a similar approach but with different background marks.

For example, you could use a similar strategy to create halos. I do that manually here: https://observablehq.com/@vega/vega-lite-annotated-time-series

Based on the above considerations, I'm closing out this issue. (Feel free to open a new issue with specific requests for richer reactive geometry documentation.)
