### ISSUE TITLE
Provide clear error message for incompatible color schemes.

### ISSUE THREAD

**Issue by david-waterworth** [vega/vega#1872]
I was directed here after logging https://github.com/altair-viz/altair/issues/1603

When I accidentally used a discrete colour map for continuous data, I got the error

> Javascript Error: e is undefined

i.e. 

`color=alt.Color('Loss',` scale=alt.Scale(scheme='dark2'))

I should have used

`color=alt.Color('Loss',` scale=alt.Scale(scheme='viridis'))

Sorry, I'm not sure how to express this as vega-lite syntax, but it seems to me there's potentially a bug as the error message seems to indicate that there's an exception handler missing an `e` argument somewhere?

**Comment by david-waterworth** [comment]
Note this seems to be platform dependent. @jakevdp could not reproduce but it fails for me in both chrome and firefox on linux (Ubuntu 18.04)

**Comment by domoritz** [comment]
I can reproduce it on Mac os. I doubt that it depends on the os.

**Comment by Toxyl** [comment]
I am getting the same issue on a Linux OS. For me it happens when I try to make a chart interactive (using Altair) - as long as the chart is static there is no issue. I've done some elimination and the piece of code that causes the error is this: `chart.encode(y = 'count()')`, if I remove it everything works as expected - except for my chart not being what I want....

**Comment by jakevdp** [comment]
@Toxyl - are you setting a categorical color scheme for a continuous quantity? If not, you're having a different issue, and I'd recommend opening an issue on Altair with a full minimal code snippet that reproduces your problem.

**Comment by Toxyl** [comment]
@jakevdp - First off: thanks for the fast reaction! At first I thought it might have to do with it because I'm dynamically generating charts and do a simple guess what settings to use: if a column contains float values I use `<colName>:Q` and else `<colName>:N`/`<colName>:O` - these are also used for the color scheme. So I've eliminated all of those and left it up to Altair to decide what to use, but the error persisted. Only removing the `y = 'count()'` setting helped. Then I re-enabled the rest and it would still render fine, but as soon as I added the `y = 'count()'` setting it broke down again. 

I don't have access to my code now (it's at work), so I'll try tomorrow to produce a minimal code fragment that reproduces the error. If I get it fail without a categorical color scheme for a continuous quantity I'll create a new issue on Altair, else I'll post it here.

**Comment by jakevdp** [comment]
Your error is only related to this issue if you are directly specifying the ``scheme`` argument. Since it sounds like you are not, I would suggest opening a separate issue.

**Comment by Toxyl** [comment]
Alright, I thought the same applies to the `color` argument. Will open a separate issues then.

**Comment by jheer** [comment]
In addition to better error warning, this issue also revealed an issue in color scheme handling. Array-valued schemes can be interpolated to be used within interpolating scale types. This was already supported for array literals as the scale `range`, but not for named schemes. PR #1950 fixes this bug and also adds a new, friendlier warning for incompatible schemes.
