### ISSUE TITLE
Scenegraph tests fail on node 12

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1893]
Because of minor differences in the generated scenegraphs.

**Comment by jheer** [comment]
Yes, small differences result in different outputs. I've been delaying moving the test suite over, as I don't want to maintain two versions. Now that v12 is current and v10 is LTS it probably the right time to switch.

**Comment by jheer** [comment]
Turns out the different output is due to a change in the underlying sorting algorithm used by V8, which provides stable sort by default. To get consistent results across node versions as well as various browsers, we can further augment Vega's sorting infrastructure to ensure stable sort criteria, using the underlying tuple id values in case of ties. While we already perform stable sorting in some places, up until we did not require it in conjunction with comparator functions used as parameters to transforms. PR #1966 changes this, and also adds tuple ids to internal hierarchy data structure nodes so that the hierarchy layouts also use stable sorting.
