### ISSUE TITLE
monthAbbrevFormat not working

### ISSUE THREAD

**Issue by mcmcgrath13** [vega/vega#1896]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug.
- [x] Use the latest Vega version, if possible. Always indicate which version you are using.
- [ ] If you are using Kibana, first read the [instructions for posting Kibana Vega issues](https://gist.github.com/nyurik/736c34970ba3c32f3fe3d45d66719b3e).
- [x] Include error messages or gifs/screenshots of problematic behavior, if applicable.
- [x] Provide an example specification and accessible data. Try to provide the simplest specification that reproduces the problem. To share a specification, use the [Vega-Editor](https://vega.github.io/editor/) and click "Share" to embed a working link, or provide an example spec in JSON, wrapped by triple backticks like this:

When using monthAbbrev Format, an empty string is returned.  With the same data using timeFormat, a month abbreviation does get returned.  See in the below example that using `new_month` works, but changing the `x` to `str_month` everything is undefined.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "autosize": "pad",
  "padding": 5,
  "height": 200,
  "data": [
    {
      "name": "source_0",
      "values": [
        {
          "month": "9",
          "year": 2017
        },
        {
          "month": "9",
          "year": 2017
        },
        {
          "month": "9",
          "year": 2017
        },
        {
          "month": "9",
          "year": 2017
        },
        {
          "month": "5",
          "year": 2018
        },
        {
          "month": "5",
          "year": 2018
        },
        {
          "month": "Missing",
          "year": 2017
        }
      ]
    },
    {
      "name": "data_1",
      "source": "source_0",
      "transform": [
        {
          "type": "formula",
          "as": "int_month",
          "expr": "parseInt(datum.month) - 1"
        },
        {
          "type": "formula",
          "as": "new_month",
          "expr": "isValid(datum.int_month) ? timeFormat(datetime(2000, datum.int_month), '%b') : 'Unk'"
        },
        {
          "type": "formula",
          "as": "str_month",
          "expr": "isValid(datum.int_month) ? monthAbbrevFormat(datum.int_month) : 'Unk'"
        }
      ]
    },
    {
      "name": "data_0",
      "source": "data_1",
      "transform": [
        {
          "type": "aggregate",
          "groupby": [
            "new_month"
          ],
          "ops": [
            "count"
          ],
          "fields": [
            null
          ],
          "as": [
            "__count"
          ]
        }
      ]
    }
  ],

  "marks": [
    {
      "name": "marks",
      "type": "rect",
      "style": [
        "bar"
      ],
      "from": {
        "data": "data_0"
      },
      "encode": {
        "update": {
          "x": {
            "scale": "x",
            "field": "new_month"
          },
          "width": {
            "scale": "x",
            "band": true
          },
          "y": {
            "scale": "y",
            "field": "__count"
          },
          "y2": {
            "scale": "y",
            "value": 0
          }
        }
      }
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "band",
      "domain": {
        "data": "data_0",
        "field": "new_month"
      },
      "range": {
        "step": 20
      },
      "paddingInner": 0.1,
      "paddingOuter": 0.05
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {
        "data": "data_0",
        "field": "__count"
      },
      "range": [
        {
          "signal": "height"
        },
        0
      ],
      "nice": true,
      "zero": true
    }
  ],
  "axes": [
    {
      "scale": "x",
      "orient": "bottom",
      "grid": false,
      "labelAlign": "right",
      "labelAngle": 270,
      "labelBaseline": "middle",
      "zindex": 1,
      "labels": true
    }
  ]
}
```

Result using timeFormat:
![image](https://user-images.githubusercontent.com/24885580/62491719-b6b9fe80-b79a-11e9-8c74-9e05eaebd251.png)

Result using monthAbbrevFormat:
![image](https://user-images.githubusercontent.com/24885580/62491761-d6512700-b79a-11e9-89ec-36a31110b894.png)

Snapshot of data:
![image](https://user-images.githubusercontent.com/24885580/62491796-e537d980-b79a-11e9-8ada-286590a5af41.png)

**Comment by roying** [comment]
When changing from "new_month" to "str_month",  be sure to change also "data_0" transform groupby to "str_month" -- otherwise "str_month" is undefined in "data_0".

This spec works as expected in Vega Editor using Vega expression "monthAbbrevFormat":

![screenshot_vega_x](https://user-images.githubusercontent.com/37225856/62568634-addd3180-b85b-11e9-98c7-47b99172fada.png)


https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJBSNq+XQCYADO7tQD6PJhwAbSUIUAhwqBl0VB0cSGlWACd4ZAB9d2MI+wp0ABtWZFhdYKzwsNLwyFRZFl1IAE5MivsAT2R0RLd3AEYAdhCsgF9vUvLmqprEOsaRisg2jq6+gYjhlbL1iImZWriZzcqFzpwPZea15rG56p2pvabxo6X+89mIq9Lt3ahRB7mnk49AAcBwuFQ+WS+dx+f0+ALApxBrwOEK2N2+kAAsoxYBorLDIfDTi8KoN1gBdAZg0LrSBRGJ1Xz+VLdAnxbhJFJ1BLJNIZN5QPCJdAyWAAM24iVQxRRB3seBahFiUAlUtYuUwAq26CKcUseFS6KmWsqyAAHoRjnoOrBkABJHYACiZrFQdCNAEowABaMCs0Em1GVBVKuqq1DqzVy5S6yLIADuhsmBK25stdRxADU8owDM6-K6uDsk7cvQB+MB4RgxABikoweHzeGQVZijo8nnkYBdbv1JZYHq7AHIAKTsIdenBDgCqMgA1kPIAHZc15YrlZBw5GU5Uddyhf3jdHIGmrZAszm8z2iwbPWAK0aAILsdiJZAUOtSvxNwt9u9T2cFyXc4KSpWYITpaINyZdB0jZHkuTiGCWTZIURXFesZUuY8Qw3dBqGoN9aGbHd7EIjlCHYFosNXexYAPI1gNXckTXsbhiBo2jIHgDkdiY5oWOPMVGGQXIDFjEpaLAGR1VyaNBK4vcgmjexUlSHjWD4+TQVA1YlEEkwMESOcJIGCD6Q3IyTNQ9c6jfeA8HghVcmVSTPnYRYKQFTdEm4aUcCDSAYMZPxYIydZqVNGQeIMZVAtYQgmTi48zV0IMtgQPIN1S1jKmE0SjDiejEkPfjSVyyB41zb50sqTKXLqHKVKgDyZEKytEgKaNIrhNLmvieAsrqajcvsfKxLqNSNK02iesJVw+qkqB6o3Eb+pyfJlXcbqdNKMk9IgBTlsGlzTPeWkLMamzQziVqjG8gw-PQSxFrmYKkNCuCTU3ESJqKhjkwi7zhSsZLxno5BCC6IHaTMCwrAdGRkCtdw6G6by4csagAHlVGR3RUfcUQwLMi6oOG66N1ySx2k6B6npegKDiC0KQuZflmfG9rICm3jHJhz4QeoVyV1XeInCiXI6kcZx+eRZpttKI6thkRhEI6gpvO0XzdCFLqDrAI7IHQM1Ck4sAIJWq7vMlES+Nu7gCD8tlCNzXQxTyW1vI1dhRMfanqDkOJEicFxvfQX3ckfKwGpOXovFpH3RIAIR1USabqVBcwMBqtcsWLUpwdHE4j0TYz15AqX0kBBiAA

**Comment by mcmcgrath13** [comment]
@roying In a fresh session, it does seem to be working now.  I think I tracked down the bug - if you pass an unexpected value (such as `"Missing"`) to the function, it "permanently" breaks it - at least for the rest of the session.

![image](https://user-images.githubusercontent.com/24885580/62635540-e3d6f000-b905-11e9-974b-97ab1cff2d78.png)

I think this is because in [the code](https://github.com/vega/vega/blob/master/packages/vega-functions/src/format.js) there is one date object that is re-used for all of the formatting, so if that object becomes corrupted, the functions no longer work.  I'll start a PR to address this.
