### ISSUE TITLE
Embedded Vega renders differently than the online editor

### ISSUE THREAD

**Issue by crulplay** [vega/vega#1902]
I'm working on integrating Vega into an Angular webapp. The Vega spec is generated by domain model data. 
I encountered a spec that doesn't render correctly in my webapp, but when I use the online editor to find the issue with the spec, the chart is rendered correctly.
The Vega version is 5.4.0 (the same as the current version of the online editor)

This is the rendered chart in my webapp. As you can see, the datapoints are aligned to the left side.

![grafik](https://user-images.githubusercontent.com/6766410/62631932-dfc0c780-b931-11e9-978d-35427b6cf802.png)

This is the code to invoke Vega
```javascript
render(model: VegaChartModel, elementRef: ElementRef) {
    const json = JSON.stringify(model.getSpec());
    const parsed = parse(model.getSpec());
    return new View(parsed).renderer('svg').initialize(elementRef.nativeElement).run();
}
```

This is the generated spec (I'm sorry for the length, but it is hard to strip it down without the issue disappearing):
```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 1110,
  "height": 300,
  "title": {
    "text": "Historical Line"
  },
  "data": [
    {
      "name": "table",
      "values": [
        {
          "xval": 1362474900000,
          "series": "Port 1 (Down)",
          "yval": 9
        },
        {
          "xval": 1362359040000,
          "series": "Port 1 (Down)",
          "yval": 8
        },
        {
          "xval": 1362474900000,
          "series": "Port 1 (Up)",
          "yval": 13
        },
        {
          "xval": 1362359040000,
          "series": "Port 1 (Up)",
          "yval": 12
        },
        {
          "xval": 1362474900000,
          "series": "Port 2 (Down)",
          "yval": 14
        },
        {
          "xval": 1362359040000,
          "series": "Port 2 (Down)",
          "yval": 15
        },
        {
          "xval": 1362474900000,
          "series": "Port 2 (Up)",
          "yval": 12
        },
        {
          "xval": 1362359040000,
          "series": "Port 2 (Up)",
          "yval": 14
        }
      ],
      "transform": [
        {
          "type": "filter",
          "expr": "(dropdown === '*' || datum.series === dropdown)"
        }
      ]
    },
    {
      "name": "selected",
      "on": [
        {
          "trigger": "clear",
          "remove": true
        },
        {
          "trigger": "!shift",
          "remove": true
        },
        {
          "trigger": "!shift && clicked",
          "insert": "clicked"
        },
        {
          "trigger": "shift && clicked",
          "toggle": "clicked"
        }
      ]
    },
    {
      "name": "minNegativeY",
      "source": "table",
      "transform": [
        {
          "type": "filter",
          "expr": "datum.yval < 0"
        },
        {
          "type": "aggregate",
          "fields": [
            "value"
          ],
          "ops": [
            "min"
          ],
          "as": [
            "value"
          ]
        }
      ]
    },
    {
      "name": "maxPositiveY",
      "source": "table",
      "transform": [
        {
          "type": "filter",
          "expr": "datum.yval > 0"
        },
        {
          "type": "aggregate",
          "fields": [
            "value"
          ],
          "ops": [
            "max"
          ],
          "as": [
            "value"
          ]
        }
      ]
    },
    {
      "name": "minNegativeX",
      "source": "table",
      "transform": [
        {
          "type": "filter",
          "expr": "datum.xval < 0"
        },
        {
          "type": "aggregate",
          "fields": [
            "value"
          ],
          "ops": [
            "min"
          ],
          "as": [
            "value"
          ]
        }
      ]
    },
    {
      "name": "maxPositiveX",
      "source": "table",
      "transform": [
        {
          "type": "filter",
          "expr": "datum.xval > 0"
        },
        {
          "type": "aggregate",
          "fields": [
            "value"
          ],
          "ops": [
            "max"
          ],
          "as": [
            "value"
          ]
        }
      ]
    }
  ],
  "signals": [
    {
      "name": "tooltip",
      "value": {},
      "on": [
        {
          "events": "rect:mouseover",
          "update": "datum"
        },
        {
          "events": "rect:mouseout",
          "update": "{}"
        }
      ]
    },
    {
      "name": "clear",
      "value": true,
      "on": [
        {
          "events": "mouseup[!event.item]",
          "update": "true",
          "force": true
        }
      ]
    },
    {
      "name": "shift",
      "value": false,
      "on": [
        {
          "events": "@legendSymbol:click, @legendLabel:click",
          "update": "event.shiftKey",
          "force": true
        }
      ]
    },
    {
      "name": "clicked",
      "value": null,
      "on": [
        {
          "events": "@legendSymbol:click, @legendLabel:click",
          "update": "{value: datum.value}",
          "force": true
        }
      ]
    },
    {
      "name": "minY",
      "value": 0
    },
    {
      "name": "computedYMin",
      "update": "if(length(data(\"minNegativeY\")) == 0 || minY < data(\"minNegativeY\")[0].value, minY, data(\"minNegativeY\")[0].value)"
    },
    {
      "name": "maxY",
      "value": 0
    },
    {
      "name": "computedYMax",
      "update": "if(length(data(\"maxPositiveY\")) == 0 || maxY > data(\"maxPositiveY\")[0].value, maxY, data(\"maxPositiveY\")[0].value)"
    },
    {
      "name": "minX",
      "value": null
    },
    {
      "name": "computedXMin",
      "update": "if(length(data(\"minNegativeX\")) == 0 || minX < data(\"minNegativeX\")[0].value, minX, data(\"minNegativeX\")[0].value)"
    },
    {
      "name": "maxX",
      "value": null
    },
    {
      "name": "computedXMax",
      "update": "if(length(data(\"maxPositiveX\")) == 0 || maxX > data(\"maxPositiveX\")[0].value, maxX, data(\"maxPositiveX\")[0].value)"
    },
    {
      "name": "dropdown",
      "value": "*",
      "bind": {
        "name": "Datenserie",
        "input": "select",
        "options": [
          "*",
          "Port 1 (Down)",
          "Port 1 (Up)",
          "Port 2 (Down)",
          "Port 2 (Up)"
        ]
      }
    }
  ],
  "scales": [
    {
      "name": "xscale",
      "type": "time",
      "padding": 0.2,
      "domain": {
        "data": "table",
        "field": "xval"
      },
      "range": "width",
      "reverse": false,
      "domainMin": {
        "signal": "computedXMin"
      },
      "domainMax": {
        "signal": "computedXMax"
      }
    },
    {
      "name": "yscale",
      "type": "linear",
      "domain": {
        "data": "table",
        "field": "yval"
      },
      "range": "height",
      "round": true,
      "nice": true,
      "reverse": false,
      "domainMin": {
        "signal": "computedYMin"
      },
      "domainMax": {
        "signal": "computedYMax"
      }
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": [
        "#99220d",
        "#e64427",
        "#009959",
        "#27e695",
        "#0d8499",
        "#27c9e6",
        "#45e0ff",
        "#e67e27"
      ],
      "domain": {
        "data": "table",
        "field": "series"
      }
    }
  ],
  "axes": [
    {
      "orient": "left",
      "scale": "yscale",
      "labelPadding": 4,
      "titleFontSize": {
        "value": 15
      },
      "zindex": 1,
      "title": "[db]"
    },
    {
      "orient": "bottom",
      "scale": "xscale",
      "title": "Zeitpunkt",
      "titlePadding": 5,
      "titleFontSize": {
        "value": 15
      }
    }
  ],
  "legends": [
    {
      "stroke": "color",
      "title": "Legende",
      "fill": "color",
      "orient": "right",
      "padding": 10,
      "cornerRadius": 5,
      "strokeColor": "#ccc",
      "encode": {
        "symbols": {
          "name": "legendSymbol",
          "interactive": true,
          "update": {
            "fill": {
              "value": "transparent"
            },
            "strokeWidth": {
              "value": 2
            },
            "opacity": [
              {
                "test": "!length(data(\"selected\")) || indata(\"selected\", \"value\", datum.value)",
                "value": 1
              },
              {
                "value": 0.25
              }
            ],
            "size": {
              "value": 150
            }
          }
        },
        "labels": {
          "name": "legendLabel",
          "interactive": true,
          "update": {
            "opacity": [
              {
                "test": "!length(data(\"selected\")) || indata(\"selected\", \"value\", datum.value)",
                "value": 1
              },
              {
                "value": 0.25
              }
            ],
            "size": {
              "value": 10
            }
          }
        }
      }
    }
  ],
  "marks": [
    {
      "type": "group",
      "from": {
        "facet": {
          "name": "series",
          "data": "table",
          "groupby": "series"
        }
      },
      "marks": [
        {
          "name": "linechart",
          "type": "line",
          "from": {
            "data": "series"
          },
          "encode": {
            "update": {
              "x": {
                "scale": "xscale",
                "field": "xval"
              },
              "y": {
                "scale": "yscale",
                "field": "yval"
              },
              "stroke": {
                "scale": "color",
                "field": "series"
              },
              "opacity": [
                {
                  "test": "(!length(data ('selected')) || indata('selected', 'value', datum.series))",
                  "value": 1
                },
                {
                  "value": 0.15
                }
              ]
            }
          }
        },
        {
          "type": "symbol",
          "from": {
            "data": "series"
          },
          "encode": {
            "update": {
              "x": {
                "scale": "xscale",
                "field": "xval"
              },
              "y": {
                "scale": "yscale",
                "field": "yval"
              },
              "tooltip": {
                "signal": "{ \"Series\": datum.series, \"x\": datum.xval, \"y\":datum.yval}"
              },
              "fill": {
                "scale": "color",
                "field": "series"
              },
              "signal": "{ \"Series\": datum.series, \"x\": datum.xval, \"y\":datum.yval}",
              "opacity": [
                {
                  "test": "(!length(data ('selected')) || indata('selected', 'value', datum.series))",
                  "value": 1
                },
                {
                  "value": 0.15
                }
              ]
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by roying** [comment]
Not sure why the Vega spec works on Vega editor but not on your server. Use the browser's debug console to see if there are Vega error messages.

Your screenshot shows Vega not rendering the x-axis, so the error could be related to "xscale". In your spec, "domainMin" and "domainMax" are specified but may not be necessary because Vega automatically handles the domain extent based on dataset values. 

      "domainMin": {
        "signal": "computedXMin"
      },
      "domainMax": {
        "signal": "computedXMax"
      }

If "domainMin" and "domainMax" are omitted, the result in Vega Editor shows the exact same chart. Here is a simplified version of the spec that works in Vega editor (and may work on your server):

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwARl0AGRREgpG1fFoDMeg0sh5mAG2RbQEI3mQAPPFsgAJRlg8bgAnRnh0BzAAGUYZZyUAX0MoNXQ8TBwAbSUIVzcjGXRUZxw7dHYnBVy3SApI1mRYLRyCgvy22s96hy1tCwA2ACYAFgB2EYBOaxmUzqNYZDCm3wAFULwdMAAKABFuZRkASmr52oBPHq1JmoLk27cO+chuyL7BoYtRaZGZmzOFktGCsyusQpttDt9ocTnNnpc3jgABwPCD3M5PTovK44frDcZTP7-AGQRbLZqgjZbbYAVUIsNRFxxOgsjPR80xbWxiJZwy+Pz+cKxZOBFKgYIhOzpDIBUARvVxQzZQsejKMrwVvNGE2mgrVUBFIPFVKGUIOx1OJPlfRGysZnIK3M1eM+3z0v1m+tJQKNkAlYFNe3NMqtzO0ojtGK9Gve+J1RJVjsNYr9Jql9MtZ0g1sVkY50bDH357r1su95LWadpGcTTJ52ltZ0SDwAuiq7CF0DJYAAzUKoFr2r14c6EUpQHuMBweEKZ55eQizsrbNQhbiENTmsAAXl3YAA5AAqfdgAA+p7AaTwrFQdGTO73q-Xm5hkDZrZq7LyD0gRRKvkWJx4A8NQ5yMWRByjMs8DCahqCWXx4CcdBZ1rIwQjQbgqC0GDGjzToHVqGDTHgpcoAAQlgRBGB7Hw0KgDDUCw8dcOQfC2kI9xYNI3xKOo2iwAAMkEsAkPCABrZBQPoyA4jJHwyjE+BJNA9j2mHbiELKKiaM2YTRIcCSpLArlgjgqpFMM5TjPfToW0-EAlDbWxYFMIoHDFVpVSxP9xzsbhuGnRhCBMuoGnHYAv1qCDsiHMtkCoGQ8BTDDgKwJjWEWZjUK9VgN3SPyrxvN8m1rTioAS5AkpS5A0oyrLWDo3L8o8XxIpK+Zmzsz84U5X9ij8pDkBQ0KekaHCQkadsYrALyCK9Srqt8erkDyrJyMWvAuA8VAWxMx08qvPzWP22o+xCeAWMmtimw-O5ep-XyAP4pqsTG8ce0iRZprkWKoJJTaUwAASceCZDUABlc5UHYQKsCU8T5DAEGaCqtRogqZAHHhqzxNOoxDoK3xNrvF6AGlkHOfGJ1CS6Jrw27uvumo+qeyyjOkn93q0GRWAcBwfsg-N4sS5LfBRsHIeh2HsYRpGJbRjH2CxnGJOpyBCdaspgHenAitvd7EnV866ZwVjbLaezmZZx6Bt8J8N3NUbwt8Q9QvYOJQJwQj+v-MpdgK7sfVO2SZEIRqAKx2rXuedd7FkTyvTdmT-UhINXxTqk0+ldX-UDaELUz8EA3TE5GSttourcKvnIWCInET9SfLtspPAQSJnHbEcx18ex-3bQh0DUNQ4moLQ9DoIZ203DA4hcRlICvTIoAySpO4Xycsa9qAYweKL0K7eDfFUDREFCjCqBCRYtE+jy2J6m3m79uV26qLvRz8wz4hG6fuFn36wA+yXr3Cob8N7AgcNvbMVw97tk7DII+ZQTBmBjo6NcrBwb02QO2GQ4QrpTR-BfJY18cC30WA-JuXI2ZQHgIFUIoVu5+VCCPdy59D7jjmlyAAxJMSYQwhh6E5lmLhyABgjBGEMMYIcuHWF4d8aRkjRGTFENIwRSIpiTAUWMeAkxRHSJGKIZAegew9mkaIsYyBJEdQKLXLkM90Bz29gvYBZRV5gKzJvSBkcKx7wchAWxkB0CeCNJwvqoRgRJV8E4WioVX5+XOHE0KDhMYOFWEPFhY8cAjC7o4ZAAAxWQeAIaMAAF4RQXtzXEEZOj7ygCUz2Xg+g5LwBZKAWQ1DsD2hQ7yXJwlVQUlAWGBA-6xPrn5NuYyGG5N8AALWQMwcOMhxKoKIrktJw9R5aFEM0pwBSkrFLKfPLMlSdDVMrn4sAATQZo0bj0pMMFuCSUQnQnKWJ7AtL8tEVG4N15YknPzZ5Dh6HTWWJEsosFzAD3SZs3ExJHS0JCPEEIAAlIejBMpbPbEENckkADCLzfBcPgMS0KVVaFqHKVmWA0tApinKr7T+3ypYw0CurOIM50DAUYNhM210ZKa0pbKCcU5NTlUdCcjsXZYCDwwpE-UaJ6ILAeZJAA6uoTQTihW1BOUqLVtSsTrk5cwKmf0tWAPlaZJoAzIDkScAglgK50joG2AAHW9EBECbqjhHDPBeT2TrXXuujlJN1SM3XvVDZedIN46DvRDGaqAJztAWoVSm81CajAnInkMM5eqLW2LLK5Q5mqzVhQcONKpegLVV0Zp1WskBknKw8kckk1CG1MqVljNlSUlicvsDysArF+UtUFWWQ18BjVCy1WKy1QReJ2uoA6pegbALBrUF6n154wD+oyCuqOwEQ0KDAOG8Kkb9axvCvG0tSa036uFhmstFawDZtzUKmtAIC0kiLaOoVj7xzaCrXm2U767i+NA-4lIkAMAhHErc78byP6+GoOgkK7YexrgHCWv5nLkADPpW25M6sXEr1Ab8kkyHuB5XYCag0PpmgW2ZliaDsGp0cS9G2r+tVEAoRWQhnuZROPGwwy2ssxHyyimsXWhaMhyU-qzAKkTv7PCKa1aSSZrdEmKq5J4qBu8E13qxDRmdSZ1Mv0mVpx0OnfDWlvRZg0yq5O-sSYpAldmjBWe0nRyTwG7OQHHZO01CbjOzutdsW1VVF2IEdRkHY+5V0HrUPub1vrt3gwDXF-dIF9xI33O9bLUbry3mTN66mxyXa4jTamjN6bquJvK8+ug4ZKtgBAx+6t+pWtVfvVmRhAEaW9BkuhkZWGSRicIx1mSZLuAUpU88BTI2yzKYW050zLxNPNcgB5neMD9O+aMxt5zZmO6le0xAqBNndtpv8oFewIVluFrcjySAwBj2QAhnRt1eto1Fbo2Gl4n2Csxo1H984n3z3yiNrZq7-zRUHdW7QoFryH1bfEysKHCbSSPc1M91773yQA-PcmP7ngCffboMD17oPsDg56EbXz-mRysenc19wVrfBhYXUup1sX4tZeS1undzqMseqkvl3L4V8uE7oyVtz2r6vJuqwZ7rD6s2NdfUBs1FdgMdYY24LXLWnIgESEAA

**Comment by jheer** [comment]
Thanks for sharing. Unfortunately, we can't really debug this outside the context of your specific app. As the example works in the editor, it looks like the problem stems from some kind of interaction between Vega and the app environment. As @roying points out, it looks like the x-axis scale domain is off in the embedded example. If the suggestions about the domainMin/Max don't solve your issue, you might try using the View API to examine the data set and scales to see if you can debug what might be happening differently within your web app.

As this issue does not appear to be contained within Vega itself, I'm closing it out for now. However, please do share if you figure out the problem. If the problem does reveal a Vega-specific bug we can always re-open the issue.

**Comment by crulplay** [comment]
Thank you for the analysis. I will try to narrow down my issue further.
Regarding the domainMin/domainMax properties: In the underlying app model, it is possible to manually define min/max values for quantitative scales + I added a feature, that dynamically resets the domainMin/domainMax if the values in the dataset are smaller/greater than the min/max values (hence the signals).
This logic seems to work fine for all the other charts I've seen so far, but I can not rule out that this is causing the issue, of course.
