### ISSUE TITLE
Support custom color name in the config 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1904]
We should be able to define:

```
config: {
  color: {
    "uw-purple": "#XXXXXX"
  }
}
```

and then use `"fill": {"value": "uw-purple"}` in the code. 

This will be especially useful to create a visualization that works across themes.  For example, one can name a color by role (such as "highlight") and then set the "highlight" color to be different color for different themes. 

cc: @Saba9

**Comment by domoritz** [comment]
Can't we use styles for this?

**Comment by kanitw** [comment]
> Can't we use styles for this?

Not for conditional encoding.

**Comment by domoritz** [comment]
Good point.

In general, I like to solve a single problem in a way that it solves other problems at the same time. It would be great not to add an ad-hoc solution for one problem.

In this case, I think named colors are a necessary extension given that CSS also introduced them despite the availability of styles.

**Comment by jheer** [comment]
Should color variables references be simple strings, or should they have a special prefix? That is, do you use `{"value": "uw-purple"}` or something like `{"value": "@uw-purple"}`. I ask because otherwise you can cause some major mischief by overriding existing colors. Consider:

```json
"config": {
  "colors": {
    "#000": "#f00",
    "#0000ff": "#00ff00",
    "black": "white",
    "white": "black"
  }
}
```

Also, if you allow lookup to be recursive (variables can be defined by pointing to another variable), you can more easily end up with accidental infinite loops if the syntax doesn't distinguish between CSS color strings and Vega color variable names.

So, we need to further flesh out any designs here. Thoughts?

**Comment by domoritz** [comment]
We could use the format that css variables use https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties.  Or the $ prefix as in scss https://sass-lang.com/documentation/variables.

**Comment by jheer** [comment]
So I thought about it some more, and I'm becoming increasingly uncomfortable with this request, as formulated. If we are going to add variables, what are all the different places in Vega in which they are usable? And why only for colors? Maybe someone wants to do this for shapes, or stroke dash patterns, or, ...

Quickly this expands o a global variable system. Fortunately, we already have a global, reactive variable system: signals. So, my counter-proposal would be to add a new `signals` entry to the config that allows one to define a set of signals in a reusable fashion. These would then be processed at parse time and otherwise act as normal signals.

Of course, that would mean that references to variables would need to be made in signal expressions (the `{value: "varname"}` syntax would not work). Note that you can use signals to defined mark config entries, so this could be used in conjunction with config-based templates.

Reactions? (@kanitw, @domoritz)

**Comment by kanitw** [comment]
> And why only for colors? Maybe someone wants to do this for shapes, or stroke dash patterns, or, ...

That's a great point.  I don't think variables in config should be only for colors.
While I can see that they would be the most useful for colors (esp. in the light/dark mode use cases), I can imagine this could be useful for other use cases .
For example, one may want to create a more accessible theme that has thicker strokeWidth for lines or something. 

> So, my counter-proposal would be to add a new signals entry to the config that allows one to define a set of signals in a reusable fashion. These would then be processed at parse time and otherwise act as normal signals.

This makes sense, however given the following statement:

> Of course, that would mean that references to variables would need to be made in signal expressions (the {value: "varname"} syntax would not work). 

We need to think about how we would surface this in Vega-Lite, which doesn't have a signal support yet.  

That said, I think there are many cases that signals/variables would be useful for plot parameterizations. 

(https://github.com/vega/vega-lite/issues/3338 is the issue for discussion about signals in Vega-Lite.)

**Comment by jheer** [comment]
Thanks @kanitw. I'm interpreting your comments above to state that you support this direction for Vega, but more work is needed to determine how to surface it in Vega-Lite. Is that correct, or should I wait on this issue for a while to see if there are other concerns that Vega might address? (If we want to keep config files interchangeable between Vega and VL, that means signal definitions might be present in VL config files... of course, I think this is already true in theory given Vega's existing support for signal-valued config entries.)

**Comment by kanitw** [comment]
@jheer  Yep, this seems like the right direction for Vega.
