### ISSUE TITLE
Vega-expressions undefined functions

### ISSUE THREAD

**Issue by martinRenou** [vega/vega#1939]
Some documented vega functions seem to not work inside of vega-expressions. Functions like `toDate` and `timeParse` are throwing: `Error: Unrecognized function: timeParse`. 

I see that, unlike other functions, they are not tested here: https://github.com/vega/vega/blob/master/packages/vega-expression/test/codegen-test.js.

Functions that do not seem to be tested are:
- Type Checking functions
- Type Coercion functions
- Formatting functions
- Color functions
- Scale functions

**Comment by martinRenou** [comment]
Should I be doing something special for having access to those functions? Or is it a bug? It seems to me that it's a bug as it is documented that those functions should be available.

**Comment by jheer** [comment]
Hi! The vega-expression package contains the expression parser and code generator, along with definitions for some basic functions corresponding to JavaScript built-ins. It does *not* contain all functions used by the full Vega language (which is what the documentation refers to). For all functions, please see the vega-functions package instead.

**Comment by martinRenou** [comment]
Thanks for your answer!

How can I tell to the vega-expression parser to use the vega-functions? Should I import vega-functions myself and provide them in the global scope during the parsing?

**Comment by jheer** [comment]
Here's where we instantiate the expression parser (within the vega-parser package): https://github.com/vega/vega/blob/master/packages/vega-parser/src/parsers/expression.js

And here's where we hand over the external function implementations to the runtime dataflow system so that they are accessible at runtime (in the vega-view package): https://github.com/vega/vega/blob/master/packages/vega-view/src/runtime.js

Hope that helps.

**Comment by martinRenou** [comment]
Sorry, it is a bit unclear to me how the Vega repo is separated.

I am trying to parse vega-expressions containing functions from vega-functions, in order to turn in into an executable JavaScript Function. Should my project depend on `vega-expression` and `vega-function` or should I use a higher-level package from Vega?

The code you linked to is super obscure to me. My code is currently the following:
```TypeScript
const expressions: any = require('vega-expression');

const codegen = expressions.codegen({
  whitelist: ['cell'],
  globalvar: 'cell'
});

// Here `code` is containing a vega-expression which potentially calls vega-functions 
const parsed_value = codegen(expressions.parse(code));

const function = Function('cell', '"use strict";return(' + parsed_value.code + ')');
```

I tried exposing the vega-functions to the scope of the codegen, without success...

**Comment by martinRenou** [comment]
I came up with a solution, please tell me if I'm doing something wrong.

```typescript
const vega_expressions: any = require('vega-expression');
const vega_functions: any = require('vega-functions');

const codegen_params = {
  whitelist: ['cell', 'functions'],
  globalvar: 'cell',
  functions: function(codegen: any) {
    const fn = vega_expressions.functions(codegen);
    for (let name in vega_functions.functionContext) { fn[name] = 'functions.' + name; }
    return fn;
  }
};

const codegen = vega_expressions.codegen(codegen_params);

// Here `code` is containing a vega-expression which potentially calls vega-functions
const parsed_value = this._codegen(vega_expressions.parse(code));

const function = Function('cell', 'functions', '"use strict";return(' + parsed_value.code + ')');

// Calling the function with the vega_functions as input
function(cell, vega_functions.functionContext);
  }
```

**Comment by jheer** [comment]
That looks like it is close to what we do in Vega. However, instead of passing the external function implementations as a parameter, we bind it to the `this` context of each parsed expression. This happens in the vega-runtime package (which is invoked by the view-view code I shared earlier). The vega-parser runs the expression parser to generate the JavaScript code; generated expression code is included within the fully parsed representation of an input Vega JSON specification, which the parser outputs. The vega-runtime library takes the code generated by the expression parser and uses the Function constructor to generate a callable function for each parsed expression.

Here's the code we use for that: https://github.com/vega/vega/blob/master/packages/vega-runtime/src/expression.js

Note that different parsed expressions may take different input arguments based on the context in which they are used in Vega (e.g., within data transforms, signal updates, encodings, etc). Common arguments include a `datum` object and the values of signals that the expression depends on (denoted as the `_` object). I do not know if these more detailed concerns affect you or not...

**Comment by martinRenou** [comment]
Thanks a lot for your answers! :) I will look at vega-parser and vega-runtime more closely.
