### ISSUE TITLE
Custom formatting function support?

### ISSUE THREAD

**Issue by stkiss** [vega/vega#194]
I would like to use a variation of the "s" format where "k" and "M" abbreviations are used for thousands and millions, but without using the "m" abbreviations for numbers lower than 1.

As far as I can tell I would need to define a custom formatting function. In d3, the .tickFormat() call allows a function to be passed in. I looked through the docs and haven't found a way to do this in vega.

This is a question, if it is valid I can put in a proper feature request.

**Comment by jheer** [comment]
Closing this issue now, as the `{"template": "..."}` form of data ref (added in Vega 1.5) covers this use case. See the [template documentation](https://github.com/vega/vega/wiki/Marks#templates) for more.

**Comment by floribon** [comment]
@jheer I am also looking for custom formatting for numbers. We are using `numeral.js` format syntax rather than `d3` for the rest of our interface.

I am no sure that the `template` feature can help me as is also relies on `d3-format` for numbers. Could you consider a way to pass a custom formatting function during vg config?

**Comment by boutils** [comment]
@floribon +1

**Comment by boutils** [comment]
@jheer any news on this?

**Comment by floribon** [comment]
In case people are interested, I managed to hack my way with these lines:

```
vg.util.getTickFormat = (function(gtf) {
  return function(scale, tickCount, tickFormatType, tickFormatString) {
    if (tickFormatString) {
      return function(value) {
        return formatValue(value, tickFormatString);
      };
    }
    return gtf(scale, tickCount, tickFormatType);
  };
})(vg.util.getTickFormat);
```

This will override `getTickFormat` by calling it only when there is no format specified, otherwise your custom `formatValue` function.

Of course a native and clean way to do so would be welcome in the future, but I can survive in the mean time.

(Side note: I was investigating `vg.util.format` first but doesn't seem to be involved for axes)

**Comment by jazzido** [comment]
Thanks, @floribon! 

I'll also throw in my +1 for this feature request. My use case involves displaying abbreviated currency amounts on the y-axis (eg, *1M*, *2.3B*), so I need a custom formatting function.

**Comment by domoritz** [comment]
> I'll also throw in my +1 for this feature request. My use case involves displaying abbreviated currency amounts on the y-axis (eg, 1M, 2.3B), so I need a custom formatting function.

If you only want to add a currency, you can use https://github.com/vega/vega/wiki/Marks#templates in many cases.
