### ISSUE TITLE
Ticks and labels do not show up when data is not part of the spec.

### ISSUE THREAD

**Issue by yurzo** [vega/vega#2078]
If I define
```
"data":
        {
            "name": "table",
        },
```
and then:

```
"scales": [
        {
            "name": "xscale",
            "type": "band",
            "domain": {
                "data": "table",
                "field": "_id"
            },
            "range": "width",
            "padding": 0.1,
            "round": true
        },
        {
            "name": "yscale",
            "domain": {
              "data": "table",
              "field": "count"
            },
            "nice": true,
            "range": "height"
        }
    ],
```
the resulting scales have no tick or labels.
As soon as I add:

```
 "data":
        {
            "name": "table",
            "values": {}
        },
```
the xscale produces perfect ticks and labels.
Nothing I've tried short of passing the complete dataset helps the yscale produce ticks and values.

Of course if I define the yscale domain to be ```"domain": [min, max]``` all works.

I'd think that the yscale should update as soon as the new data is passed.

**Comment by jheer** [comment]
I'm not sure I understand the issue. Both scales are defined with domains that are determined by the data set. If there is no data, there are no values to define the scale domain. Does the problem concern what happens if you add data after the initial View instantiation?

If you provide a complete spec as well any other necessary code (e.g., JS code that inserts new data values) that replicates the issue, I'd be happy to take a look!

(Also, the top-level `data` property should be an array of objects, not a single object.)

**Comment by yurzo** [comment]
hi @jheer:

So here's the spec:
```export const spec = {
  $schema: "https://vega.github.io/schema/vega/v5.json",
  width: 600,
  height: 300,
  data: [{
    name: "table",
    values: {}
  }],
  signals: [
    {
      name: "tooltip",
      value: {},
      on: [
        {
          events: "rect:mouseover",
          update: "datum"
        },
        {
          events: "rect:mouseout",
          update: "{}"
        }
      ]
    },
    {
      name: "dblclick",
      value: {},
      on: [
        {
          events: "rect:dblclick",
          update: "datum"
        }
      ]
    }
  ],
  scales: [
    {
      name: "xscale",
      type: "band",
      domain: {
        data: "table",
        field: "_id"
      },
      range: "width",
      padding: 0.1,
      round: true
    },
    {
      name: "yscale",
      //domain: [0, 500000],
      domain: {
        data: "table",
        field: "count"
      },
      nice: true,
      range: "height"
    }
  ],
  axes: [
    {
      orient: "bottom",
      scale: "xscale",
      grid: true
    },
    {
      orient: "left",
      scale: "yscale",
      grid: true
    }
  ],
  marks: [
    {
      type: "rect",
      from: {
        data: "table"
      },
      encode: {
        enter: {
          x: {
            scale: "xscale",
            field: "_id"
          },
          width: {
            scale: "xscale",
            band: 1
          },
          y: {
            scale: "yscale",
            field: "count"
          },
          y2: {
            scale: "yscale",
            value: 0
          }
        },
        update: {
          fill: {
            value: "#ff4e1b"
          }
        },
        hover: {
          fill: {
            value: "#3eb99e"
          }
        }
      }
    },
    {
      type: "text",
      encode: {
        enter: {
          align: {
            value: "center"
          },
          baseline: {
            value: "bottom"
          },
          fill: {
            value: "#333"
          }
        },
        update: {
          x: {
            scale: "xscale",
            signal: "tooltip._id",
            band: 0.5
          },
          y: {
            scale: "yscale",
            signal: "tooltip.count",
            offset: -1
          },
          text: {
            signal: "tooltip.count"
          },
          fillOpacity: [
            {
              test: "isNaN(tooltip.count)",
              value: 0
            },
            {
              value: 1
            }
          ]
        }
      }
    }
  ]
};
```

the data looks like:
```const entries = [
    {
        "_id": 0,
        "count": 615
    },
    {
        "_id": 5,
        "count": 746
    },
    {
        "_id": 10,
        "count": 523
    },
    {
        "_id": 15,
        "count": 986
    },
    {
        "_id": 20,
        "count": 951
    },
    {
        "_id": 25,
        "count": 337
    },
    {
        "_id": 30,
        "count": 273
    },
    {
        "_id": 35,
        "count": 313
    },
    {
        "_id": 40,
        "count": 555
    },
    {
        "_id": 45,
        "count": 769
    },
    {
        "_id": 50,
        "count": 557
    },
    {
        "_id": 55,
        "count": 754
    },
    {
        "_id": 60,
        "count": 815
    },
    {
        "_id": 65,
        "count": 2
    },
    {
        "_id": 70,
        "count": 721
    },
    {
        "_id": 75,
        "count": 262
    },
    {
        "_id": 80,
        "count": 247
    },
    {
        "_id": 85,
        "count": 417
    },
    {
        "_id": 90,
        "count": 77
    },
    {
        "_id": 95,
        "count": 867
    },
    {
        "_id": 100,
        "count": 195
    },
    {
        "_id": "n/a",
        "count": 675
    }
]
```
and the react-vega call looks like:
```
<Vega spec={spec} data={{ table: entries }} />
```
I get this
![image](https://user-images.githubusercontent.com/25695763/66667322-a04f7980-ec07-11e9-9413-e86f1401d0b0.png)

alternatively:
if i `spec.data[0].values = entries`
and then:
`<Vega spec={spec} />`
I get:

![image](https://user-images.githubusercontent.com/25695763/66667452-e4427e80-ec07-11e9-838a-ff3e3fee9c56.png)

Please notice that in both cases xscale.domain succeeded.

**Comment by jheer** [comment]
The issue here has to do with layout. The default layout (`"autosize": "pad"`) pads the view with additional pixels to accommodate axes and legends. In this case, when there is no data, the axes/legends are empty and so no extra padding is produced. The x-axis is visible in the case where you include an empty data object because Vega tries to generate an axis entry for that element and so adds some vertical padding prior to adding new external data.

There are a couple of solutions you might apply:

1. Call [`view.resize()`](https://vega.github.io/vega/docs/api/view/#view_resize) when you update the data. This tells the Vega view that it should re-calculate the layout and resize the chart as needed, for instance to include additional padding. Since you are already calling the view API I would recommend this approach.
2. Set the layout to automatically resize by default. For example: `"autosize": {"type": "pad", "resize": true}`. This option is more responsive; however, as it triggers re-layout upon all view updates (including mouse hover, etc), it can also result in unnecessary computation.

In addition, you might explore including some default data or changing the layout parameters (see the [autosize documentation](https://vega.github.io/vega/docs/specification/#autosize)) to get a desired default state when the chart is first instantiated.

**Comment by yurzo** [comment]
@jheer:  Thanks!!! this was extremely helpful!
