### ISSUE TITLE
Better handling of time ticks when domain falls between "nice" points

### ISSUE THREAD

**Issue by anagrius** [vega/vega#2084]
If you have an axis that uses the default "time" format, and have an domain that falls between two "nice" points in time, like e.g. a domain between 10:55:01 and 10:55:59 the time ticks will not include the "nice" points and therefor labels don't contain enough information for the reader to determine what range she is looking at (there is no point of reference):

Here is an example:

![image](https://user-images.githubusercontent.com/157210/66838410-e63c7280-ef64-11e9-8a60-80af806b001e.png)

As you can see the labels include the SECOND component in all ticks, but no information about the hour or minute of the day. Which makes it impossible to reference the time ticks.

Here is an example where it includes on of the nice ticks that can be used for reference:

![image](https://user-images.githubusercontent.com/157210/66838539-1b48c500-ef65-11e9-854b-b6f1ec9595bb.png)

The point is, that since we have so much screen space in this example, there is seaming no reason that Vega could have much more verbose/specific labels in these situations, or ensure that there is at least one tick that contains enough context.  

Alternatively, allow defining which time components should be included at different interval scales without having to defined a complicated custom label encoding.

**Comment by anagrius** [comment]
![image](https://user-images.githubusercontent.com/157210/66913849-cfa22400-f015-11e9-9f0f-255a99b1d153.png)

Everyone I have asked think that the ticks in this picture represent minutes (e.g :10) when in reality it is the seconds component. I am not exactly sure how to fix this.

**Comment by mattijn** [comment]
The success rate of receiving an answer to your question will probably increase if you include a minimal working example/url accessible through the [vega-editor](https://vega.github.io/editor/#/)

**Comment by jheer** [comment]
Thanks for raising the issue. This one is a bit indirect because it is not actually handled by Vega, but rather by the d3-scale library. If no explicit format is provided, the default format for a `time` scale is [D3's built-in multi-time-unit format function](https://github.com/d3/d3-scale/blob/master/src/time.js#L59), which is not exposed for customization.

One solution might be for Vega to override this behavior and provide it's own (customizable) multi-time-unit format string. I'm flagging this with "discussion" and "enhancement" tags for us to look at it more closely. If anyone has thoughts on what the corresponding customization syntax should be, please share in the comments below.

If you know that the desired units are seconds, you could of course put in a custom format string. In addition, the axis `format` parameter accepts signal values, so (though cumbersome) as a stop gap measure, you could manually set the format string based on the span of the axis domain.

**Comment by anagrius** [comment]
Hey, Thanks.

> If you know that the desired units are seconds, you could of course put in a custom format string. In addition, the axis format parameter accepts signal values, so (though cumbersome) as a stop gap measure, you could manually set the format string based on the span of the axis domain.

This is exactly what we plan on doing, or maybe add an expressionFunction that takes these things parameters to handle the heavy lifting in JS. But it is indeed cumbersome.

**Comment by jheer** [comment]
As part of our new support for time units, I'm adding functionality for specifying multi-format time formatting functions, effectively moving that out of D3 and into Vega, along with customization options. Look for this in the next minor version release!

**Comment by anagrius** [comment]
Awesome. Thank you
