### ISSUE TITLE
Vega fails webpack import

### ISSUE THREAD

**Issue by flowsipher** [vega/vega#2086]
I'm importing Vega into my Create React App based project with webpack and the line:

`import * as vega from 'vega';`

When I attempt to build the project, this error message is received:
 
```
Failed to compile.

./node_modules/vega-functions/src/codegen.js
Attempted import error: 'cumulativeLogNormal' is not exported from 'vega-statistics'.

```

I have checked version numbers and reinstalled the Vega package everything, including webpack is current.

**Comment by jheer** [comment]
There was a similar error reported here earlier, which in that case was due to a stale import of the vega-statistics module. You might try refreshing any package lock files and node_modules folders (e.g., delete them and re-run npm install or yarn). The most recent version of Vega lists vega-statistics 1.6.0 or higher as a required dependency.

**Comment by jheer** [comment]
However, it looks like the vega-functions package.json file was missing the 1.6.0 requirement. I've fixed that in our repo, and it will be included in the next release.

Thanks for raising the issue!

**Comment by jheer** [comment]
I just made a new release with the dependency version fixes. Hopefully that resolves your compile issue.
