### ISSUE TITLE
geoArea expression cannot compute planar area in combination with fit

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2100]
Using the `geoArea` function ([doc](https://vega.github.io/vega/docs/expressions/#geoArea)) it is possible to compute the area in steradian or projected planar area. 

This works OK for steradian using `null` for the `projection` variable in the `geoArea` expression:

```json
  "data": [
    {
      "name": "world",
      "url": "data/world-110m.json",
      "format": {"type": "topojson", "feature": "countries"},
      "transform": [
        {"type": "formula", "expr": "geoArea(null, datum)", "as": "SIZE"}
      ]
    }
  ]
```

<img width="442" alt="image" src="https://user-images.githubusercontent.com/5186265/67599103-85d0e080-f76f-11e9-8c73-d936263ed07c.png">

But when trying to compute the projected planar area using:
```json
{"type": "formula", "expr": "geoArea('projection', datum)", "as": "SIZE"}
```
It throws an: `Error: Cycle detected in dataflow graph.`:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/5186265/67599328-1d363380-f770-11e9-9da7-7a6a549bf9dd.png">
Editor [spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwogAw7FESCkbV8WgEy6DUQgCduE5PDw8ZsLQG0lEUBD9QZdFRkLUg7BycXWQVvP0g8AE9CEJxIZABHVnQAGwBRdFtNa39IWEYALxSwYFKTQOzQj1UNRHkwY1M8AF1IAF9iuIAzZi0asup60LV0PHQACgByZW5bbLUFgEo+2N6lLutIadnPWN9-AKCqyGXVtRjzqFZVqZmRG7WAWgBGL51USWkcgGhkGKwweFG8SSVzw3EIDkBCigg2QMyeV3g3FYMjwtkYyHc-Vihlx6DcoNsqBODx8UOSoQpqFY2UwbTSAA87KFqMhuABBWyoxbhRzOVwLNpHVioLZs9DuVIAZQAkgAtXLbB5dHZ7A4YWwAawVYC8-jOJUS9NSsEQ6HpwOR9ipOBqR0wqXedyJDzSMkxaiq5vOkFYhCOgeJwdguO4BsDkAoOVYVwAxOx030HSVhtkGi6E0nUz8fpnIxbuNxsi5CJDxpNUlL-ir1ZqabsHt7g6TyWDPDVLVcedwbXaQmyRZFXKEJ2Lor1tf522Btb0gA)

But instead of using `fit` in the `projection`
```json
    {
      "name": "projection",
      "type": "equalEarth",
      "size": {"signal": "[width, height]"},
      "fit": {"signal": "data('world')"}
    }
```

It works OK if when using:
```json
    {
      "name": "projection",
      "type": "equalEarth",
      "scale": 90,
      "rotate": [0,0,0],
      "center": [0,0],
      "translate": [
        {"signal": "width/2"},
        {"signal": "height/2"}
      ]
    }
```
See:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/5186265/67599737-f6c4c800-f770-11e9-97e7-ddc109734f8f.png">
Editor [spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwogAw7FESCkbV8WgEy6DUQgCduE5PDw8ZsLQG0lEUBD9QZdFRkLUg7BycXWQVvP0g8AE9CEJxIZABHVnQAGwBRdFtNa39IWEYALxSwYFKTQOzQj1UNRHkwY1M8AF1IAF9iuIQcqoBOfVjDezx0PCqPfQWugcN4ZBlZ209F5ag8W3Q3bJm5ib8asup60OaWUnM+nZ9ay5zQjvw7vtOu2N6lJaUkDUM0wOC8-l8-gCQSqkGU3Fs2TUMShUFYiNCwOmpHhiLUAFoAIyEnSoSTSOQ7SAAMwRGDwWhqiWSoTw3EIDgpCig1OQM3RsPg3FY61sjGQ7n6p3i+zctNsqE8pyezNh8tQrCO3LSAA87KFqMhuABBWx8gAUAHJwo5nK5LW0saxUABKbXodypADKAEkAFq5L6on7+P4QAGGDC2ADWnrA4LO0tVoVgiHQLKp1PsipwNSxoJUCKRD2layFaiqkNRkFYhCxleVgz23GjlcgFByrFhAGJ2H2S6iStTGNkGrn252e8TiQPB4Y2dxsi5CIznldUk6yb6A0HB2GoVLq3sDrB1Z4mUlYYbuKn0yE2mF7LaonJUjbIq4+iG-Pufr0gA)

Seems something going on between `geoArea` and `fit`.

Issue originate from: https://github.com/vega/vega-lite/issues/5490

**Comment by jheer** [comment]
As the error warning indicates, the spec is invalid because it induces a cycle: the projection `fit` is determined by the _output_ (post-transformation state) of the `world` dataset, and yet the transforms performed as part of the `world` dataset definition reference that same projection.

The solution here is to break up the spec into two data sources: one for the source GeoJSON data and another for the transformed output. The projection can then be unproblematically configured using the source data. [Here is an editor example.](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwogAw7FESCkbV8WgEy6DUQgCduE5PDw8ZsLQG0lEUBD9QZdFRkLUg7BycXWQVvP0g8AE9CEJxIZABHVnQAGwBRdFtNa39IWEYALxSwYFKTQOzQj1UNRHkwY1M8AF1IAF9iuIAzZi0asup60LV0PHQACgByaVZbeGQFgEo+2N6lLutIadnPWN9-AKCq0u4VtZjzqBWG1KORZW5bbLUAWgBGX50qEk0jkA0Mgw+GDwo3iSSueG4hAcIIUUEGyBmKyu8BuMjwtkYyHcu38-VOsUMgWCoXenzU93O11uV2WqxCYKg+PQbghtlQJwePlhyVCvNQrGymDaaQAHnZQtRkNwAIK2DGLcKOZyuBZtI6sVBbaXodypADKAEkAFq5bYPLo7PYHDC2ADWprAXn8ZxKiRFqVgiHQIo5kEG9n5OBqrxpHy+fVDyBkOLUVR9jNYhCOaYpjNg+O4rrTkAoOVYVwAxOxqwncyVhtlntUS2XK-9-rXBXEEdxsi5CDDxpMXpigZabXbBSTzmSHvFbNzYGLPDU-VdFdxA8H2TZ7FqonJUprIq4+g7SXsQL0gA)

**Comment by WouterDX** [comment]
I'm the originator for the referenced vega-lite issue, your example solves my problem as well. Thx!
