### ISSUE TITLE
Zooming into a timeline results in incorrect render (canvas only)

### ISSUE THREAD

**Issue by epicyclist** [vega/vega#2109]
### Versions

vega 5.7.3
vega-lite 3.4.0
vega-embed 5.1.3 

### Description

I have a timeline that renders showing years in the axis. If zoomed into a minutes/seconds view, there's a threshold where the circle jumps along the axis and the tooltip changes — it won't trigger over the circle's new position, but it will at its former position (where it should be).

If I change the renderer to SVG the problem goes away.

### Example

Open this [Vega Editor Example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMFAJ5mQBMADAIwCskANFAB6NWnALTtRbACosWyabJYAtSGAC+3KtVqQGqZi1Y9+g-S3HipMudKWr11GvWNMuvSAN2tnZ9hfnybKhpgALpUalSQxIS4hADG8ACWAPYAdmToGJAA5gBOCdDpQZjwdAAOhIwJKfCEOTi4PEVQAEZVBbrEsXgkkEGBEOGYALawOQDWjLEJObExjZiEKbFJ0FVZhdRuG-aQAGYJ0e1Gdjsl5Yw1Q6VJOXjzO53d2-ZQZxW6+PCxvS-9GIOZHRoJp7A64I7ae6bN6MG6rFJ3PonYpJJK4RKlMiUF4ZF6gw6MATI05ld6vQhXG53YmbXY3EbwRgAUgAmsImUN2dAwEyABLIJkAWShDy6c1QuJer1JjE+3yaAyafwgoUVKiAA), and zoom into the middle circle (on the 2020 Y axis) until you reach the bounds shown below.

<img width="314" alt="Screen Shot 2019-10-28 at 12 41 11 PM" src="https://user-images.githubusercontent.com/802575/67707524-41685f00-f980-11e9-8f58-4fcccb16c1fc.png">

Zoom in a smidge more and you'll see the circle jump to the left.

<img width="313" alt="Screen Shot 2019-10-28 at 12 41 55 PM" src="https://user-images.githubusercontent.com/802575/67707583-5ba23d00-f980-11e9-861b-283e131be8d4.png">

#### Example Spec
```json
{
  "data": {
    "values": [
      { "y": "2015", "x": "2015-01-01T00:00:00Z" },
      { "y": "2020", "x": "2020-01-01T00:00:00Z" },
      { "y": "2025", "x": "2025-01-01T00:00:00Z" }
    ]
  },
  "selection": {
    "grid": {
      "type": "interval",
      "bind": "scales"
    }
  },
  "mark": "circle",
  "encoding": {
    "x": {
      "field": "x",
      "type": "temporal",
      "scale": {
        "type": "utc"
      }
    },
    "y": {
      "field": "y",
      "type": "ordinal"
    },
    "tooltip": [
      {
        "field": "x",
        "type": "temporal",
        "format": "%Y-%m-%d %H:%M",
        "scale": {
          "type": "utc"
        }
      }
    ]
  }
}
```

**Comment by jheer** [comment]
Thank you for the bug report! After some digging I was able to isolate the issue: once you zoom in really deep, the off-screen elements can have extreme coordinates (e.g., 6 billion pixels to the left or right of the display). In some cases the internal rendering logic was still processing these marks, which should have had no effect. Nevertheless, in my tests on both Chrome and Firefox it appears that the Canvas rendering state was becoming subtly corrupted when the graphics context was translated to/from these extreme values, resulting in the incorrect point placement. Interestingly, this issue does not show up for me in Safari. Note that the issue was limited to the rendering sub-system: all the values calculated by Vega appear to be correct.

To workaround these browser limitations, I've updated the Canvas renderer to only process items whose bounds intersect the current view area, preventing this issue. In some cases this should also provide a performance boost by more efficiently avoiding unnecessary work.
