### ISSUE TITLE
Add ability to efficiently sort stacks

### ISSUE THREAD

**Issue by Timmmm** [vega/vega#2119]
If you have a `stack` transform with `groupBy` then the order of the groups is determined by the order in which they are first seen. This appears to be not by design, but just a side-effect of the fact that Javascript `Map`s are iterated in insertion order. (Though it's hard to tell the intent because [the code](https://github.com/vega/vega/blob/master/packages/vega-encode/src/Stack.js#L102-L136) is only lightly commented and written in a very convoluted way [cough](https://medium.com/@bluepnume/theres-no-need-to-define-all-javascript-vars-once-at-the-top-of-a-function-and-there-hasn-t-been-a66b31f21822), [cough](https://rules.sonarsource.com/javascript/RSPEC-878), [cough](https://rules.sonarsource.com/javascript/type/Code%20Smell/RSPEC-3504), [cough](https://rules.sonarsource.com/javascript/type/Code%20Smell/RSPEC-2392)).

You can work around this by sorting your entire dataset by the `groupBy` field first, but this is inefficient because you basically end up sorting it twice.

I would suggest adding a `sortGroups` option that is either `ascending`, `descending` or `insertion`. But what it is probably a fairly common requirement to fully control the order, e.g. if  ('Monday', 'Tuesday', etc.).

**Comment by jheer** [comment]
The stack transform is agnostic to the order of the groups. The order of the groups doesn't matter, as the computed stack values are written to the input data stream without changing the order of the data objects in that stream. If you would like to order the groups later in the visualization, you could perform sorting downstream, for example in a [scale domain definition](https://vega.github.io/vega/docs/scales/#scale-domains) or as part of a [mark definition](https://vega.github.io/vega/docs/marks/#top-level-mark-properties).

On the other hand, The order _within_ a group is of course of interest, which is why the stack transform includes a `sort` parameter.

That said, I'm not sure what the motivating use case is here, so it's hard to comment precisely.

**Comment by Timmmm** [comment]
Aha I see - it is really the `domain` that is in the order of the data, but it is easy to change.

Sorry for the noise!
