### ISSUE TITLE
Add isocontour affine transform support.

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2163]
I've had a similar issue (#1329) some time ago and thought I will revisit this with these new functionalities in version 5.8 (`heatmap`, `isocontour` and `kde2d` transforms).

Basically I like to combine the [isocontour-airports.vg.json](https://observablehq.com/@mattijn/contour-tests-using-projections) and [isocontour-volcano.vg.json](https://observablehq.com/@mattijn/isocontour-volcano-vg-json) (links are observable notebooks).

I think I need to combine the `kde2d` transform in combination with the `isocontour`, because of the `weight` within the `kde2d` transform. What I learned from #1329 is that the contours should be computed before I've screen coordinates.

But I'm just stuck again. My progress so far in this observable [notebook](https://observablehq.com/@mattijn/geo-contour-test). Its also hard debugging without the new 5.8 release in the editor.

**Comment by jheer** [comment]
Here is an [editor example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwogAw7FESCkbV8W3fqWR0rPN1iMAXsi2QZslwagPqM9ABtYLQBtJQhQCEioP1QXHEhqACd1BTDIyFZCNXQ8OKhsvHQACgByQkTkeEZCZhyeGRKASmCdAF1INIBfL3C0wxi8hLwAM1SowwoA1jyI8cMADwBlQsS8LQBaAEYADh06HQAmHvHIJdzCLU3jqMgAT2X0Va1tgHY6UW3r9Pvzjc2+sCdLrHWY3AaudjoGRqVQaRAKKCTfzTLQAFi+kHYjGhWmAkGxhFsrkSUOonigqGxf3kFPQ8y0B303l+OE2QKi3TSoPS4PiCACngBkCRKJwL0+QqxOJweIJRPiJJkZIRkEpchwonRtPpOEZR2ZyAuOG27MinKi3P66FirngsjsrESAH1hox-P4VSK8nhEtMMVK1Lj8TJCWsFeg1DwVdxCHh6kEcMEfX6wMMArBkK1TRBzZFLdFrYNEtxCrkdGMTl6tDpgVyhbyoMXS8hNhWblWcDWOSD64XiSWcsgDm30h2wF2zT25m4+-F4MgZLlEuWMWOJzmpycG5B54vkIlW6upnl14ClK0vJACphE3Xp9vypVqrU47IR4ZHR74vgiCRyCTlAYZg2HYVgM0SO090XOg7VQUgMAIRgJBkUhrwzPBYHg9BYCXUgoRkVgAnWR8qkIJ0dHWABmAA2HQXX8ap1lYNQnWLd11ioVZJGkORawtXsbTnbhuESNQggxH0oVgYYRNQEIAV6OYbjwW5CEGDMAEdphked3xOHDHjDccvhuHCYyDHw-C-KAknUOhYRYMAACowFstQ6GMUw1lzJSDSNMArgU9JsNcbE1GQekgp88Z82U1TBjJGNuGxNYTOChMwGCU4VVuSALyCwxXWQfwxPk3yLUgCLylcIpqBGOgzkMsAAGpXPqs5DTAUgwAORoWra4YGuWTqXKKApWFQLhoQisAAFJXOSdyHMQRpIGi3y8SqxIarqwafia1rdroH5Ou63r+qOk7CGc1N-GExIxpyCapvC+YuoWuzltW7MlPy8qoHKbgJEqV91QB4tgfgUGOl8n6IFaPi8wEhLFr0yBpEdXShJE0qJMVaTZLKpTYvSFS1NcABrcKDkDNLDAcZwQjxSyAlcZa1ppZmTCs1xPLMTo-vKzEoRhdRNBldHudZ+JgkhaFlppOXRbhdp1pOHUoHpOmoFy+Jcu1yBlGQEwzAlrbXDcugvVgYJxsmsKItVg27VYRcMuTZADZC+I3JhpS4bABHuzvLdZygSCHUScShQxiCUZSPGpJkxI5NvDaCqgMnBkYaQI+4R09JuIqSot1GDdgVBhPFsAPYN-xkCoQItGoqKASDycQ7BMPDZEkuMU-Vxr1IZRe7ULZNh0SapDfDFk4QoMs9cOxCCBniVWGZAnoqW188XZJkCCH7TUFyBAch0GMtCfj727s+QfqNHF-iWIIJyES0f5euLKl6z0fgAUOZCibIOJmktfDS0bAOMsHMwBc3Ab-YBuRWzdFgWAnmCooFDjWoLG4u4lygJZr-PB+5ywoLgeg8OC4lzIJwaTfG-gQGJnIRAw2YtECkGHGQtBLC+Z4A4dgro55LyfwPkTRSodBLh24HdbaEl4quE0tpOMrMMRqG4BgKkiYmSUT0G0DEiplQS34GgQY7BkSGkdIQL+R8hFWAwIkCml9O6k3kXyRA6ByYYngAxfytchTDGLKnVB142aj0AdOBcdpwq4iChkLIjDYEZ3Rj6bgFNkAAHU2FBjHGycuKS0nZOPK4AAxNkMpmA1ZFzdNZPEY5IDFPgI08JQtHAOw1rUopnZKnpEIDkeEEti6BniL0zQAccwAjVpASSMgCYpzETFJJT8bLIHsO4zxSS75QwfsMiG983ytzmO3DczjDBLPRmswU05vHVC0H46cAT1G4nyDkG8UjFz5yjs0m4kTuDRJlLEzIBQZhJJwsWNJmS4SFPMdWd43T6b5JmMKTpUBim6K+UpSArp3TzI2lMg+Rkdz2g+S6apKoRE7xkevRgxUhlvMjlbIpcK8xIuhTgAi7oxmRFofc6pAB5XpVQVJQtFOOOgqJOUB0mdM2ZQSr7E0Wa45ZqyPGXKFoMweT1Jp5wLgc8YRyzzw0vPXMk0InHXxOHGPAX94gAEEZAEQCGAAAChUUiL56hgCKKgVAq0MQiWpYuJeMZ1j12GKlIUZzYC3FQOwaRaMsVEOke-WeskciuH2KMLxPiAASxsvKXGoqoxgrroZYCMP6xw9oVH+OqQAYSTdteIxSN4tuon7cZ8MQCdCAA) (the editor has been updated!) that I _think_ accomplishes what you are trying to do. The idea is to take your gridded data, re-grid it according to the current projection, and then generate contours. This sort-of works, but not without some caveats...

The re-gridding is accomplished by projecting the data into a new grid, using a combination of a geopoint transform (to project the points) and a kde2d transform (to create the grid, and smooth it as desired). Key bits here include using the kde2d `weight` parameter (to copy the original grid value to the new grid) and the `counts` parameter (to avoid normalizing the gridded values). However the result is quite sensitive to the view dimensions and kde bandwidth: data values on the original grid might get projected further apart in the new scheme, or could be projected on top of each other... In addition, we can end up shifting the value range of the original grid values, due to the re-projection and smoothing.

I think a better approach might be to compute the contours first, directly on the input grid, then transform the contour coordinates from grid indices to lon/lat. This would have the benefit of stable contours (the base contours won't change with projection changes) defined over the original input value range. I need to update Vega to apply an affine transform to the contour polygon coordinates, while also ensuring the appropriate winding order is respected.

I've started testing these additions as new parameters that can either be defined on the grid data structure itself or as parameters to `isocontour`, and so far they are looking good! (Note that I changed the projection to equalEarth as the polar distortions under mercator looked terrible...)

![image](https://user-images.githubusercontent.com/202799/69345298-32b85380-0c71-11ea-8d12-652dd1f5eda1.png)

I will rename this issue and use it to track these transformation capabilities. Also, do I have permission to use your precipitation data in a new example once I'm done? I would credit you along with the source of the data. If so, let me know, along with any other information about where the data is from! Thanks!

**Comment by mattijn** [comment]
The result you link to in the Vega-editor is providing incorrect results. 
The original data points are equidistant from each other. If these coordinates are firstly projected to screen coordinates given a certain scale/rotation/projection, then the computed contours on these projected coordinates will be different for any change in scale/rotation/projection. This is especially clear around the polars with a non-polar focussed projection where the number of projected coordinates are denser. Something that cannot be possible with precipitation.

So I agree with your second approach. The contours should be generated on the original data points and these contours should be projected to the scale/rotation/projection in use.

I think this is wat you show in the embedded picture. But the pattern of the precipitation is wrongly placed on the globe. I struggled with this in #1329. Upon quick visual inspection I think you have to use the data as prepared in https://raw.githubusercontent.com/mattijn/datasets/master/annual-precip_-180-180.json. 

Which makes much more sense instead of the current used dataset (my bad) that goes from 0 to 360 in longitude, which is placed upside down and vertically rolled by half the height of the array (that I had to use with the obsolete `contour` transform)

Sure you have permission to use this prepared dataset for an example. The precipitation data is from the CFSv2 product (year 2016).
