### ISSUE TITLE
Incorrect font size for custom font

### ISSUE THREAD

**Issue by Zylatis** [vega/vega#2215]
I am using the following code (link to Vega Lite editor, code generated with the help of Altair)

https://tinyurl.com/w4ob663

which uses the non-standard font Museo Sans 300. The font appears to display correctly but the font size doesn't seem to work - rather than scaling the font it seems to just adjust the surrounding padding.

I have successfully used this font in D3.js code, importing the font info from an external css sheet. However even importing this css sheet in the html used to render this chart doesn't help.

It seems potentially related to the issue here
https://github.com/vega/vega-lite/issues/4657

but i'm not sure how to leverage that (react-focused) solution here.

Any/all help appreciated

**Comment by Zylatis** [comment]
Okay, thank you for your help @domoritz. One last, possibly stupid question: how do I point to externally installed fonts? As noted the font we use on the website is imported via CSS which works fine for the D3.js part (seemed to just pick it up automatically), but the same didn't seem to work for this?

**Comment by domoritz** [comment]
Vega will pick up the font if it's available in the browser context. You don't have to do anything special. Can you share the website where you have the font loaded and the chart embedded?

**Comment by jheer** [comment]
Vega simply uses the fonts defined in the browser. It performs no font management of its own. One issue may be asynchronous font loading: if Vega executes before the font has been loaded, the font will not be available during processing and rendering. This will be particularly noticeable when using the Canvas renderer, as the replacement for the not-yet-loaded font will be drawn as pixels. Still, even SVG output can suffer as the font metrics (e.g., width of a rendered string) can be incorrect if calculated prior to the font being loaded.

This issue has arisen before, see the earlier issue for more information: https://github.com/vega/vega/issues/1671

**Comment by romankaravia** [comment]
I also just ran into this issue, maybe this is relevant for others as well:

_Font loading is hard!_

The usual "recommended" way of loading a custom font is using `font-display: swap` ([detailed explanation here](https://css-tricks.com/font-display-masses/)), which means that the browser first shows another font, then switches when the custom font is loaded. This is generally considered better for paragraphs of text because it's better to see something with a slightly wrong font than to see nothing at all while the font is loading.

This can be problematic if you are already using a custom font for paragraphs of text and you want to use that same lazy-loaded font for your vega chart. Because, as mentioned above, the font needs to be loaded *before* labels are measured, no matter if Canvas or SVG output is used.

One way to make sure that a font is loaded is to use [FontFaceObserver](https://github.com/bramstein/fontfaceobserver), if you don't care about legacy browsers, you can also use the [CSS Font Loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSSFontLoading_API).
