### ISSUE TITLE
Use "to" instead of dash in bin legend?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#2231]
Using dash would be bad for [negative values](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMHcWMHYPJWQw9Hh4ZCjda2MwZTB4bgddOjUNSE1rTBxgSFZdMWwtRtJ4dF95RRUAX3UISDwipIAzbl1UToBtFt6xeFYxa2ROyBEGvFZUOjM8gtti5TUodFht4-zC8+GAXVGoDF0Aa22AjzxaseQSgqmg81E6oAgYwAHuDIFNGAVNNsABKzPwBVy2S7jACesW2AEdWCEjHhilRICMNGMcbD4YjtgBZSI6AD6sV0rIA4ugEhdVFA8HitqYiSTmOStlTIVBYIwAF4isAtDImMATVjIAVwhFiJGmO6nIpGfmC4WE4lKUmSykaIYgIZAA): 

![image](https://user-images.githubusercontent.com/111269/70182973-c0e10080-1699-11ea-9967-354a494bfcbb.png)

Note that I just realize that the Vega default and ones that VL generate for ordinal scales are inconsistent (https://github.com/vega/vega-lite/issues/5622), so I would like to make them consistent. 
But then I realize that the Vega default isn't great for negative numbers.

**Comment by domoritz** [comment]
If we use "to", we should also have a simple way to support localization.

**Comment by kanitw** [comment]
Perhaps the easiest would be to add `config.legend.rangeDelimiter` so it's customizable?

**Comment by domoritz** [comment]
Then we would need to support localization in Vega-Lite and Vega, though.

**Comment by jheer** [comment]
I've added spacing to legend range labels for v5.9.0, so that should help legibility (e.g., "1 – 10" rather than "1–10"). I wouldn't want to switch to `" to "` as a default due to internationalization issues. There is also a technical annoyance that the range label formatting functions are part of utility methods that don't (currently) have access to config information.
