### ISSUE TITLE
Could not expose or access marks data from group subitems

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2339]
When a mark is named, it exposes its data as a table that can be accessed by other marks.
This is really usefull to deal with relative positionning.
When using a group, the feature doesn't work:
- A child mark of a group cannot access to a first level mark (dataset is not found)
- A named child mark won't expose any dataset

**Comment by jheer** [comment]
Child marks are scoped to their parent group (as are scales, signals, datasets, etc). So you should be able to reference them from other definitions so long as they are within the same group. (If not, please share an example!) By design, you should *not* be able to access a child mark outside the scope of it's parent group.
