### ISSUE TITLE
Inconsistent gradient output between SVG and Canvas renderer for bar

### ISSUE THREAD

**Issue by marcprux** [vega/vega#2365]
Take the following gradient-filled rectangle spec (v5.9.1):

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 200,
  "height": 200,
  "padding": 5,
  "marks": [
    {
      "type": "rect",
      "encode": {
        "enter": {
          "x": {"value": 0},
          "x2": {"value": 100},
          "y": {"value": 0},
          "y2": {"value": 400},
          "fill": {
            "value": {
              "gradient": "linear",
              "stops": [
                {"color": "red", "offset": 0},
                {"color": "white", "offset": 0.5},
                {"color": "blue", "offset": 1}
              ],
              "x1": 1,
              "x2": 0,
              "y1": 1,
              "y2": 0
            }
          }
        }
      }
    }
  ]
}
```

The SVG renderer looks like:

<img width="234" alt="Screen Shot 2020-02-03 at 16 29 48" src="https://user-images.githubusercontent.com/659086/73692483-674d8000-46a2-11ea-8f40-83e0da121ed8.png">

But the canvas renderer (and exporting to a PNG) looks like:

![visualization-12](https://user-images.githubusercontent.com/659086/73692419-4422d080-46a2-11ea-9912-8dc53ce55eb6.png)

This is similar to the bug reported at https://github.com/vega/vega/issues/2052 – the only difference seems to be that this only affects non-equilateral marks.

**Comment by jheer** [comment]
Thanks for the issue! The SVG gradient here uses object bounding box coordinates, and these are _normalized_: SVG treats the rect as a square, then interpolates the result into the actual screen coordinates. The Canvas gradient, on the other hand, is defined directly in terms of pixel coordinates. (The inconsistency arises due to our not realizing that the SVG coordinates are normalized...)

We need to update scenegraph rendering to get consistent results, most likely by defaulting to what canvas produces (though both interpretations could be "valid" depending on what one wants to achieve).

**Comment by marcprux** [comment]
That makes sense. FTR, I think that the SVG behavior is more "correct". In my example above, I feel that a user specifying a gradient going from the top-left to the bottom-right would expect that the middle color would bisect the opposite diagonal, rather than the diagonal of some normalized-to-equilateral internal shape.

**Comment by jheer** [comment]
I dug into this issue more, but so far have been unable to find an acceptable solution. After some thought, I agree with you that the SVG behavior is more "correct".

Unfortunately, canvas does not have a separate transform space for gradients (they inherit the current transform when the `fill` or `stroke` method is invoked). I am able to replicate SVG gradient behavior in Canvas, but only when I transform not just the gradient, but the entire shape along with it. In short, the item geometry and the gradient geometry are intertwined, and I haven't found a way to decouple them. Without that, making this work in Vega is infeasible: it would involve significant re-engineering, likely performance degradation, and probably won't even work correctly for all mark types.

On the other hand, I haven't found a good way to make SVG emulate Canvas, either. One option would be to change how we handle gradients entirely, and use a [`gradientUnits`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientUnits) value of `userSpaceOnUse` (avoiding bounding box normalization). However, that would also mean that we would need to generate separate SVG linear gradient definitions separately for *every* item, rather than reuse a single definition. This would severely bloat the generated SVG and possibly hurt performance, too.

So I'm stuck for now. If anyone else has ideas, please share. Otherwise, I might have to put this issue in the icebox. Fortunately, the main use of gradients in Vega (at least so far) tends to be axis aligned...

**Comment by marcprux** [comment]
I agree that non-axis-aligned gradients will generally be rare, so I think this can be put on ice.

**Comment by jheer** [comment]
After further thought I found a potential solution: for non-axis-aligned gradients, we can instead render the gradient into an offscreen canvas (for which we can apply whatever transforms we like) and use that to generate a [`CanvasPattern`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern) that serves as an item's fill / stroke. This is more costly (especially for large images or when using many gradient-filled objects) but perhaps that is OK given that this is a rare use case.
