### ISSUE TITLE
Default signal values cannot be set to an array of signals

### ISSUE THREAD

**Issue by khanguslee** [vega/vega#2371]
## Description
Using the Overview Plus Detail example, I am trying to set the default brush values to start from half of the width until the end of the width. Currently, this can be implemented by hardcoding the brush signal's value property to an array. If the width of the overview chart is 720px, then the value property will be set to `[360, 720]` to achieve the desired effect.

To write clean code, I would like to instead use signals to achieve this. From the examples in https://vega.github.io/vega/docs/types/#Array I should be able to input `[{"signal": "width / 2"}, {"signal": "width"}]` into the value property of the brush signal. 

## Expected Result

``` json
{
	"width": 720,
	"height": 480,
	"marks": [{
		{
			"name": "overview",
			...,
			"signals": [
				{
					"name": "brush",
					"value": [360, 720],
					"on": [...]
				},
				...
			]
		},
		...
	}],
	...
}
```

![Screen Shot 2020-02-10 at 3 37 30 pm](https://user-images.githubusercontent.com/18709969/74121339-45f91080-4c1b-11ea-886a-fd40cf55b4f1.png)

See [Overview Plus Detail Example (Hardcoded values)](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAdgBMABkURIKRtXxaALAA5DSyIXRq1jGdS2jF9tejyYcANpKEKAQYVAy6KjIWpCwhKL6+grBYZCsAE4ANrE+fnwJSXTwsBQp4cYAZtwZGHhawJB4AJ6EMTiQJWXyUI4ZsO1gjYQZjPCDkDKsqOzIGQpQeRNLkAC+q6kbEAC6XsawZpFZsFpB4aEVk1HLyH6MWQAi3BiukJtKuyD2GBkA1ieBVIXcJNVoTagZbisQjlS6RaK5W7oe6wkHIGTwbhqQbAy7ovBzBqpCq4ZBmCw4RoUdBZViDADMAE59KsjCS0qoNIgGpBqbTBnoWcSwlsKqzhXF4DTkACwGd2biSVcER0AB4PJEotnsqAtNqxPCMBHa9mQDLoNwTTmaE1KtTPZFySmQPL+KDxRLJHqQSqMZBZNS5XwxcU64z2l4yABK6GUPIO1COiLujwdr1FJNDCuFIPhE2aGpTqNNeomWVcyHQ81tl3NltOTMMYH0nzDizTTqGLt8brihS9UF9-sDHRGYxDNdz460eAydO9AC85twZ3PkDmwBmwq3LuhVTLThvGjU-TJ6h12NwCM8FpLpbF1ZqclmScfRvjYllkJV6t6EPeOgLJ81mFHcQR+f5Dx1RVLlLWIIShGFJzSdFMWxIk22MfFCUpDclVMcxzy7IcAx5BDoViAiLHWZClWtblnRIkcu3ImEOnotYX0wzpyzYrs+TpVc6S3HURLFWioAg2V5TbGCdVBfUOirStizbH1IVQHlXViD0kjWCS0QxLEcTw01oRWXDMNNVV4ylL8H0LZEcm9JigwJfTTPk5pbIAqAgKLFy-VI0dRnGDyrKVZpdB8+zAMcrUoAEwYWQM01fSyHJnSSnSCX9dh+RAiKRU84qrLE8Jtg3MTKvCcUgQlOCOlY1SImuWJuCoDIKD9OMa0gVDjIw01sPmSyw0gGysppQScBS0zIG8qaCpwSx6TmtSqKIqlpoFdbxo4paZp0AwuKVdLMv4naDTreJlLPQr2TE073UOGlpKPea81idg51gblvWywJ6QANkMQUwNNWQoMwuThqoM9ZUgAABDq5m65BlCwVAoQGe1lDkVLjHM4NYgCVUAAoAEoegpyntjeMrUthpVkHhvBEYCFHOvRzHsdYXHuHxnpVBkPGsZx5BoW2MAAD4wBFsW+YGbGqAAQha+TifcjoAh+-nEACFsengLIokIcnaZ6Jt6LphnMOe18SqwtnZUaBMkw6bEsj8cKIvSQgLKgE2zZjS1yYCC0kBqQ3pYAajAL2-B6SPEGjgBGOOE-9PxdmbYX1BYSm7bbcrtyq5DmdalUoBTmpb0BsApgyiTIChwJGlZ-FEaRvW-vF-nkDxgmoC1iZYHLcZyd7xAi9WGrHorz62rVIf66u2aW7buUO5d2Ie9+xB+4F-Hb1Hh8qbWefM0XtSvs97PMAB9e8-mreZLDSu0V3nX9-1o-B8FjIfOotBb-ylrLeWrhFYSxVsgdWhMR4BxJmqKmYAAC0YBVSrxKqXHY5cPq32XosJ8TxIwazSIQfW7VWAEmrK-Ts79oJOygJ3BG8ZXoXUgNPX2Vl-aBz7BaKeB9KZgAAPxgFcJ1PA5MADkqoADy3MeoyJ6NPEROAm45BwaZK+YpQJ9X-F+d6TDCHVwmootGPVyHGEarqI0MQW51moFaAu-15oRkdFpHsOl+y3lcp7EmpcHZDCXmY5oFiupWJbrYyA5YZCVjoWpJxgwAjaCbEbdxHYvE+w6LpAcPogrMQcKFCcn1pw4FnPOKAS5IRCXXKJfREo9wHkBNBVu757oXivHgG8f47ITAUUojGD0Kp9SktDR2akYnKUfvNVwtD0DwENFQLQlQ3rIBbpUDS2Tex5J4cNIy6ExpqTPsc7ik0uyGIGREnmfjCluVKUVBaMV8w3KiYOe5IVpzBMitFZ0VzYjhKGb1RKz89q8POjyBucRcpZHyoJXBpUwxBJvuNGJGRkBLOsVXCY3CW4DSOSE3hI0hq8MWpdZazYfmXE2lC5+aTqUgkhYdCYABiekHL9lqXOvIxw8BmDku2pS-QdBdCIogIyxBgdP5pAuW7Dh30D4xy5eNVUfzLkKovEqjOIzkWmRRQQtFYJYgYqxS3eZcxFnLMGGs44Gz5oEpMsSs8OEiV+0FbyMFkrjC0pZVoBlCDIAHQpUdNO3qPkZTpZSgpGKfpjF+Lq0SqU+HILdbwuVcRNVQGnsq8Vm59X4JMUaxSUBTW-jmS680SzGArJwLagY+LDlOu4iSs5akPUN3BdxX1IbdrhqDa4qNob+3Mt7bEX0sbQoJrzZKlN2s03nPYYmGkir9YBB1TOgtDSSS6NFJVDYQA)

## Actual Result

``` json
{
	"width": 720,
	"height": 480,
	"marks": [{
		{
			"name": "overview",
			...,
			"signals": [
				{
					"name": "brush",
					"value": [{"signal": "width / 2"}, {"signal": "width"}],
					"on": [...]
				},
				...
			]
		},
		...
	}],
	...
}
```
![Screen Shot 2020-02-10 at 3 37 15 pm](https://user-images.githubusercontent.com/18709969/74121360-51e4d280-4c1b-11ea-978f-f5e7d27cdecc.png)

See [Overview Plus Detail Example (Width Signal values)](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAdgBMABkURIKRtXxaALAA5DSyIXRq1jGdS2jF9tejyYcANpKEKAQYVAy6KjIWpCwhKL6+grBYZCsAE4ANrE+fnwJSXTwsBQp4cYAZtwZGHhawJB4AJ6EMTiQJWXyUI4ZsO1gjYQZjPCDkDKsqOzIGQpQeRNLkAC+q6kbEAC6XsawZpFZsFpB4aEVk1HLyH6MWQAi3BiukJtKuyD2GBkA1ieBVIXcJNVoTagZbisQjlS6RaK5W7oe6wkHIGTwbhqQbAy7ovBzBqpCq4ZBmCw4RoUdBZViDADMAE59KsjCS0qoNIgGpBqbTBnoWcSwlsKqzhXF4DTkACwGd2biSVcER0AB4PJEotnsqAtNqxPCMBHa9mQDLoNwTTmaE1KtTPZFySmQPL+KDxRLJHqQSqMZBZNS5XwxcU64z2l4yABK6GUPIO1COiLujwdr1FJNDCuFIPhE2aGpTqNNeomWVcyHQ81tl3NltOTMMYH0nzDizTTqGLt8brihS9UF9-sDHRGYxDNdz460eAydO9AC85twZ3PkDmwBmwq3LuhVTLThvGjU-TJ6h12NwCM8FpLpbF1ZqclmScfRvjYllkJV6t6EPeOgLJ81mFHcQR+f5Dx1RVLlLWIIShGFJzSdFMWxIk22MfFCUpDclVMcxzy7IcAx5BDoViAiLHWZClWtblnRIkcu3ImEOnotYX0wzpyzYrs+TpVc6S3HURLFWioAg2V5TbGCdVBfUOirStizbH1IVQHlXViD0kjWCS0QxLEcTw01oRWXDMNNVV4ylL8H0LZEcm9JigwJfTTPk5pbIAqAgKLFy-VI0dRnGDyrKVZpdB8+zAMcrUoAEwYWQM01fSyHJnSSnSCX9dh+RAiKRU84qrLE8Jtg3MTKvCcUgQlOCOlY1SImuWJuCoDIKD9OMa0gVDjIw01sPmSyw0gGysppQScBS0zIG8qaCpwSx6TmtSqKIqlpoFdbxo4paZp0AwuKVdLMv4naDTreJlLPQr2TE073UOGlpKPea81idg51gblvWywJGgTJN2PUFgwFIMBotZLsQZpWIONWMDTVkKDMLk4aqDPWVIAAAQ6uZuuQZQsFQKEBntZQ5FS4xzODWIAlVAAKABKHoWdZ7Y3jK1LMaVZBsbwXGAgJzridJ8nWEp7hqZ6VQZCpsmKeQaFtjAAA+MAFaVqWBnJqgAEIWvk+n3I6AIfulxAAhbHp4CyKJCGZzmeibeiuZ5zDntfEqsKF2Vgdei6XX9Pxwoi9JCAsqAHadmNLWZgILSQGpbfVgBqMBsSyPwehTxA04ARkz7Ow-QXZm3l8HEFZr223K7cquQ-nWpVKAC5qW9AbAKYMokyA0aB-qA9iPGrb+5XpeQKmaagM2JlgctxmZifa7WGrHpbz62rVWfu6u2aB6HuVGkF-FcfH37ECnmXqdvBeHzZjfm4+tSvo6HPw4Bw+q-mk+ZJhlbmiUeFsr7W1vjPWWMhq6K1lpAtWmttauF1irA2yBja03ntHBmao2ZgAALRgFVPvEqjcdiv2gjvduocUxPEjCbNIhBrbtVYASas-9OyAKoUVEeF94zB2+tfCOVko4xz7BaVe19WZgAAPxgFcJ1PAzMADkqoADy4seoqJ6GvGROA+45DIaZTemZQJ9X-F+d6PDxofygBorRJNGHGEarqI0MQB51moFaGuzj2wMOdNpDoukBw+iCsxbs7lG4+yGNQ-MmiiY9T8QpMsFYqzJK8YMAI2gmx23mhGR0Wkew6X7LeVyIVpwxOMDIacOBZzzigEuSEQl1yiXMRKPcB5ATQUHu+e6F4rx4BvH+OyEwHGJKcdVPqUl0a+zUq4yAylMAD1cOw9A8BDRUC0JUN6yAB6VA0kU8OwTSlVKgANdCY01KPyudxSacNRkPgSV1JJgVhxuQnH7PyMV4mON6oOcJsQxxhTOSCKKPzYjNGeRLA+y1mygrSOdHkPc4i5SyPlQS5DSphmidveZYJYgZGQBs5JdjIBr2SRckyoiRpDVEYtS6cK9qiM2si3+OSEVVHuBdbacLIAAGJ6RCpEdxc66jHDwGYAy3lR19B0F0FiiACKxG4Nibw+5QdEwIwvNfdOIq1Kqmis6eGIc14BBLg9BuplcVv3GgsolJKVlnjmOszZgwdnHD2fNKldLxq0tuWpaVvJf7Mu4qyw6u1OUqF8RGrQRco1hIymyvlvoiU-TGL8S1OLUoqvNmqyOGq4iCJ1dbPVirNzWsodmfFikoAOt-PNVZLqNmMC2TgD1AwB4+oDcNZ1o1830uTbKhN4bGVHQ5VgyAB0x2DHjZOpFsaOipuQOm+Amby3KpuQOu5AitWmt1Rajdla2kklMRWihGwgA)

**Comment by roying** [comment]
Instead of:
```
  "signals": [
        {
          "name": "brush", 
          "value": [{"signal": "width / 2"}, {"signal": "width"}],
...
```
try:
```
  "signals": [
         {
           "name": "brush", 
           "update": "[width / 2, width]",
...
```
![screenshot_vega5_overview_detail](https://user-images.githubusercontent.com/37225856/74673468-3d558c80-517d-11ea-8035-8a594c2c5900.png)

Vega [editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAdgBMABkURIKRtXxaALAA5DSyIXRq1jGdS2jF9tejyYcANpKEKAQYVAy6KjIWpCwhKL6+grBYZCsAE4ANrE+fnwJSXTwsBQp4cYAZtwZGHhawJB4AJ6EMTiQJWXyUI4ZsO1gjYQZjPCDkDKsqOzIGQpQeRNLkAC+q6kbEAC6XsawZpFZsFpB4aEVk1HLyH6MWQAi3BiukJtKuyD2GBkA1ieBVIXcJNVoTagZbisQjlS6RaK5W7oe6wkHIGTwbhqQbAy7ovBzBqpCq4ZBmCw4RoUdBZViDADMAE59KsjCS0qoNIgGpBqbTBnoWcSwlsKqzhXF4DTkACwGd2biSVcER0AB4PJEotnsqAtNqxPCMBHa9mQDLoNwTTmaE1KtTPZFySmQPL+KDxRLJHqQSqMZBZNS5XwxcU64z2l4yABK6GUPIO1COiLujwdr1FJNDCuFIPhE2aGpTqNNeomWVcyHQ81tl3NltOTMMYH0nzDizTTqGLt8brihS9UF9-sDHRGYxDNdz460eAydO9AC85twZ3PkDmwBmwq3LuhVTLThvGjU-TJ6h12NwCM8FpLpbF1ZqclmScfRvjYllkJV6t6EPeOgLJ81mFHcQR+f5Dx1RVLlLWIIShGFJzSdFMWxIk22MfFCUpDclVMcxzy7IcAx5BDoViAiLHWZClWtblnRIkcu3ImEOnotYX0wzpyzYrs+TpVc6S3HURLFWioAg2V5TbGCdVBfUOirStizbH1IVQHlXViD0kjWCS0QxLEcTw01oRWXDMNNVV4ylL8H0LZEcm9JigwJfTTPk5pbIAqAgKLFy-VI0dRnGDyrKVZpdB8+zAMcrUoAEwYWQM01fSyHJnSSnSCX9dh+RAiKRU84qrLE8Jtg3MTKvCcUgQlOCOlY1SImuWJuCoDIKD9OMa0gVDjIw01sPmSyw0gGysppQScBS0zIG8qaCpwSx6TmtSqKIqlpoFdbxo4paZp0AwuKVdLMv4naDTreJlLPQr2TE073UOGlpKPea81idg51gbkenm8zg1iAJ6LAUgwF0Hp6O2FqQVkKDMLk4aqDPWVIAAAQ6uZuuQZQsFQKEBntZQ5FS4wgfcjoAlVAAKABKHo6fp2GSue18Sqw1G8HRgIsc63H8cJ1hie4UnodcEmCaJ5BoW2MAAD4wFUGQpeFgZCaoABCOGzMICyoACH6RcQAIWx6eAsiiQhaeZnom3olm3jK1LkaVZBudlRoEyTDpsSyPxwoi9J9eBjpLetmNLVpgILSQGozflgBqMB-b8Ho48QBOAEZk9T-0-F2ZsJa5enncw8rtyq5C3dalUoEzmpb2ynApgyiTIARwJGg9-F0Yx42-ulkXkBJsmoEpiZYHLcZacHxAy9WGrHprz62rVMfm6u2aO67uUe892IB9+xBh9F0nb0nh8GbWZfM1XtSvr9gvMG9Fvi-mveZLDWu0UP6nj4mzPqPMWMgJaqzFsAuWitlaS0gerNA2MdbkwnqHKmUBmZgAALRgFVJvNmpk77iQ+o-deiwnxPEjLrYwhATbtVYASasn9Ozf2gpzKAvc0bxlehdSA88g5WRDgbPsFo54n3pmAAA-GAVwnU8C0wAOSqgAPICx6gono88JGt1YBlcubZK47CqqBPq-4vzvTYaQ+uE1VE4x6tQ3UYIDRGhiB3Os1ArTqBtPNCMjotI9h0v2W8rk-bA0ruzIYa9rHNFsV1exHdGpQHLDISsTC1LuMGAEbQTZzY+I7P4wOHRdIDh9EFZiDhQoTk+tOHAs55xQCXJCIS65RImIlHuA8gJoKd3fPdC8V48A3j-HZCYKi1F4wehVPqUlEYczUokyAylX7zVcIw9A8BDRUC0JUN6yAO6VA0gU3sxSBHDSMuhMaakr6XO4pNLsZjRmxMFsEspbkqlFQWjFfMTz4mDleSFacETIrRWdA82IMTxm9UStvZsQLLjnR5O-OIuUsj5UEoY0qYZwkP3GgsjIyANkOOVBMfhHcBoXMiYIkaQ1BGLUustWFKCTBkkIoimF2S4UggRYdCYABiekArTlqXOsoxw8BmB0u2gy-QdBdAYogJy1BBtf5pDud7Hh30T6JyFeNVUIL7kaovFq3OkysWmWxSQ3FTiOj4sJR3VZcx1mbMGDs44ez5rkpMlSs8OFKXB0lbyGFe1BGbTZQyjlTKDr0qOtnRVVR7gXSlUdUp+KfpjF+Ka0SqUhFhz9YItVcRDVQHntq+Vm5zXV0tfJPFBLfwrJ9eaDZjAtk4FdQMMl5yvXcWpTctSAb37Bu4qGnlWgI3sMgFGpNgxY1Mu5dGiYvpU2hQzWWxVOb0EquMAWn2NJNUmwCCa1dFbWkkiIaKSqGwgA)
