### ISSUE TITLE
numerical instability for exponential regressions

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2378]
First mentioned in #2198. 
Upon having x-axis values as date-time and quantitative y-axis values I cannot apply an exponential regression transform. Because of, I guess, numerical overflow.

I could solve it as follow:

1. First format the date-time strings to ms since unix epoch 
2. Then normalising the input variables (both!) to the range 0 and 1 + MIN_VALUE
3. Applying the exponential regression
4. Denormalise both variables and apply timeunit transform.

Especially step 2 is required for applying the exponential regression. 

I'm not sure if this normalisation method can supersede the improvement of numerical stability for regression in #2202. But it would be nice if this was not needed to do manually (for Vega-lite/Altair purposes)

<img width="393" alt="image" src="https://user-images.githubusercontent.com/5186265/74384837-7050f680-4df2-11ea-8d14-d0ef80602f22.png">

Editor-specs [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KIXQATVYxnVsYUYoiQA7o1UsdAFgAMl-bmSNq+HQGZrtyLDwBPADbIdkPDIPj4KSpCq6HiYOADaShCgEMlQMuio-jiQmoSseGEpBhToPqzIsDrxhcnAEVGZUABMls0AtJYAjK2NHQAq1lgD1gBaClDFpQ2NAOyWAL621bWReA2QzW2d3Y39loN7I2OQE2UW5uYLCYXL9QEblu1djc67+-uj8uMlpzjnF4vXOqrO4tB5bRrmV5DSwfL6THSicwATku1USQLW90e3VEUIOMKOJwaHUsokaqLRN2BWSx4IAbHj3oTvsTzM8KUsMSDNk9pozDp9jiydDMOv8rikqZjQdjGgAOfkEwVElyiREcwEraU87pIxWwoXw36iOV0jWSrk0mVbVz65lG3RyyxmgEWrXcsGNR525XCnAdAPTabmmqWprWr2WSHQpm+h0dOl06ZykPo91WzaR3ExgVwn5gBNJlOu0Pp8OZ9oMnNKvNTHodckltO3DOe9oK6sGlU4CFI0TOVNgKUe9qRvWd+35xpIunODpzCVgAC6Vw1SUKkDSGQC0lYACcggB9VAVEsebj7oIBHJ5AobvB79AyWAAM24e9QlUX6O8hDWb4-VgfEwQVkAAD0IPcAjwbgABF6gAChWVhUDoLUAEojnQCosndQdal-NZwNWGR8kFF9GGCVQAndQVYAcNJQiyMDj00Y90DAyB8MgQiAmI5BSKOCiqICFU6IYkoAi8ViZHYzj8O-ZJIGEnxqNw24myU3isjwRgMlYGRmDvNEoAM5gcLAWJIC8ZB0CgwVUFkMxBVo3ALz3Col00gxsMqDFD08OyyKgLVDwE6iVxMhdqki5I10XTd0jWGR30-M9dwPNYMqPE9jK0x9nwAz84kU9cTJ4rw-wCIqgJAxSDHAyCAiQqIULQ+owFaMAWNQNiMDA2JLCXdCwFIMAEJ6vqONiDol067qZLkwbhrAABqMAAFkAEkADlDwANQAQQAGQAVQAUTy6pIF89TgUUhSTIMbSoBq4Cro3RqoKyFq8Daol5uk3rZP65aRrGhCgamgbZsBxbQaGkb1u2vajrOy7vKgW7a0gB7F1iiB4uurdktSw89xoeyEuy0mPw+niCtfVKvxMsq0Qqqqsgp6gKdgejZA+lJIE4u7-Ex6zROFcWMhYbg1KgRrBaU7GrNYQlIAJwposKTWiY3EnoIpmRqPS9yryyFKP3Jyn6YfJ8mbpkrWfqqAXuU1LaqVhqIO+kLWtQ1gwAAKnGyaQem2GurDpbEbWhbgZjuaupRg6Tour2sYsyA1YezS2eut23rqp6FZ9mj-boChg-GqHw5hpOwFrxOkcb+HpqG+aU7R9Pxex45caivOXeUyjVICNXxbd3T9MMsjh7MvALKsmy7KORzSMQI5XMgRB3M83ul+zo5Dw1vGYtXJQvPCBASnKFmagSg3mNtyq1mnsWEoK6g1mMUxN7PVQ3AMCaB0PnJSKlVBLxdlSGIUAabHlPK9Ue8t-KBT3PkQczZoiG3CkJZB48uKKU1oTVcAIwGJW3FkLwL9OZQB8JoWyVNrpfzWCgBwTgzyGXNmAB8ZQAFAPQCAnAYCDAQKgSXGBO4zbIAQXgkSWQVSYKHECWBDNcHkXwQowhJliFgG1iQiAV8fJgTvk7UM75KKCSyOwbgBAgFHBvn4AInFBTAXYMEAA8lQPcwFCA6F4cgQUPMTD+L3GUNckALECXyFkPwL5goeHgLfKSRxgnywCdrIxUAMB7gANbiIfgXV+AR6EyA-tdF8e57HCJUTg42XEzwCXgHLBoIiFakWQL7NpBhPBVNya0w0+ZIAU2oko4WoDEnJOfho+RpkGnD2oTUxxaxqEzLHlosZvTuD9IAOomDMDU7sYByRny1qQq45C3awC8KgGxoQzyVOqcolYqj4G5RDJAJpLTQGKU+R0rpw8RbKOWc4uR6y-arACtEdB8yS4SyWUkpxVCwUoMUeLLZuz9mb0OX6Y5+iznVHxZkkAcwgA)

**Comment by roying** [comment]
An alternative workaround is to use the x- and y- coordinates (pixels) of the points for Vega transform "regression". The regression result is a set of coordinates (pixels) that can be plotted directly by mark "line" without scaling.  

By the way, the data shows the rapidly increasing number of confirmed cases of  **Corona virus (COVID-19) in Hubei Province, China** (Jan-Feb 2020).
Johns Hopkins University data visualization dashboard: https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
Data download (csv file updated daily) : https://github.com/CSSEGISandData/COVID-19

![screenshot_vega5_regression](https://user-images.githubusercontent.com/37225856/74665864-76d2cb80-516e-11ea-8697-fb8962135f1c.png)

Vega [editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KIXQATVYxnVsYUYoiQA7o1UsdAFgAMl-bmSNq+HQGZrtyLDwBPADbIdkPDIPj4KSpCq6HiYOADaShCgEMlQMuio-jiQmoSseGEpBhToPqzIsDrxhcnAEVGZUABMls0AtJYAjK2NHQAq1lgD1gBaClDFpQ2NAOyWAL621bWReA2QzW2d3Y39loN7I2OQE2UW5uYLCYXL9QEblu1djc67+-uj8uMlpzjnF4vXOqrO4tB5bRrmV5DSwfL6THSicwATku1USQLW90e3VEUIOMKOJwaHUsokaqLRN2BWSx4IAbHj3oTvsTzM8KUsMSDNk9pozDp9jiydDMOv8rikqZjQdjGgAOfkEwVElyiREcwEraU87pIxWwoXw36iOV0jWSrk0mVbVz65lG3RyyxmgEWrXcsGNR525XCnAdAPTabmmqWprWr2WSHQpm+h0dOl06ZykPo91WzaR3ExgVwn5gBNJlOu0Pp8OZ9oMnNKvNTHodckltO3DOe9oK6sGlU4CFI0TOVNgKUe9qRvWd+35xpIunODpzCVgAC6Vw1SUKkDSGQC0lYACcggB9VAVEsebj7oIBHJ5AobvB79AyWAAM24e9QlUXiSg3kIazfD9WB8TBPm-ZJIGQAAPQg9wCPBuAAEXqAAKFZWFQOgtQASjGcCDHQCosndQd1zRKAX0YYJVACd0mwgv81jwRgMlYGRmDvcjIDY5giLAWJIC8ZB0DgwVUFkMxBTo3ALz3Col3ogi+IErVD08ET8ik+pD2QGQaJXciF2qAzkjXVJ0jWFZ0EPPcaFs2BYB4OQz13A81lco8T04hjH2fQDPzicDgF-Lx-2wSB-OA0D8KgQiAngbh31UQ8oO86pIJguCsgQEpkBQgByHK-BS-LPnQ1BYny1T1L3PB8qXXCIHA0iQrCrAIvfVAorSjc4qyBKksPLwepSDLYICFAHHwMBWjAIq8sK+BcqG0qwHKyqiXqxqwGa+jgsgRiAls6h7Mc2QRogjIWG4GismgwgLoMVL+sSvdktSxSoGGl7BuGz7ID6-jAle5LWCOAa3sPChIBM6ojMKWGwHhhTwgwPcAGtlKuMiGNCtYfE0fwzxfPduACocgRiKArJsuzyjOuQQ0gmQEtUBocdG3TViyocYsgZ6Kcc6g0lCYiogwyqIdB+rIEHAxvsFhwRfikDUEIFDJscPAZrW8WKvyqWofqz4bDATX8FwuWoE8Un0fZw180gWyaKtjwH24O2AHUTDMHBam7MByWaxd4YgNdFwOvGdy8VB2G4UJidJ8mqSp89L2QY8KiZ3TWfZ8Dme5nQOY3AXanmncluKj6KKonxbup7SavyV2FbLyv3Pboajko6iAhVV2bY95BvdMRAi4dqZQ8KKew9XJQUdG+asclCOtw75aPojw6smY7cz186g1mMUeeoiMn0E0Iv857uvl-IimrJ3WTPNPGve7F1Y1OiWrZfAxHZ5SOHdKa8K7LT+lvKOWQCYyGEqJCOB81jm00qvRgV4cAPjKGeVQ59L5+2vrXVQd9yIpyfunTO3cCF92FDPZI-8kZzwgAvWKUFyhfgtO+KiMh8hZDjgQMmRxy7ZU7tXSAIF2DBAAPJUD3CBB66C9yYKgCdEwOgMHIDXJADhXMAh+BfJpa27dQHFT+kovcKj5FlGRiAOYQA)

**Comment by roying** [comment]
Note on the workaround using x- and y- pixel coordinates for regression.
For regression method "**linear**", do not use clamp() when plotting the regression line because for straight line Vega only generates two points and clamp() may result in drawing the regression line with wrong slope. Without clamp() however, the regression line may extend outside of the plot area.
```
    "x": {"signal": "datum['coord_u']"},
    "y": {"signal": "height - datum['coord_v']"},
```

**Comment by mattijn** [comment]
Thanks @roying! Interesting approach and numerical stable! But since the regression line is not anymore part of the scale domain it is also sensitive to above mentioned itches..

Good detective work regarding the data as well:) 
Not relevant for the issue, but at the end of January I tried to compare the exponential growth rates of the confirmed cases between the provinces in China after one week of Hubei-lockdown. 
Conclusion _at that time_: The Hubei lockdown seems to provide a reduction in exponential growth for the surrounding provinces, where it remains exponential in Hubei.

**Comment by roying** [comment]
It turns out that for the workaround approach for regression involving datetime, 
it is only necessary to use the pixel coordinate for X-axis (linear time scale).

For regression transform, the original data values and scale should be used for the Y-axis
so that the regression result will be correct for non-linear Y-axis scale (such as "log" or "pow").

Here is a revised version in the [Vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KIXQATVYxnVsYUYoiQA7o1UsdAFgAMl-bmSNq+HQGZrtyLDwBPADbIdkPDIPj4KSpCq6HiYOADaShCgEMlQMuio-jiQmoSseGEpBhToPqzIsDrxhcnAEVGZUABMls0AtJYAjK2NHQAq1lgD1gBaClDFpQ2NAOyWAL621bWReA2QzW2d3Y39loN7I2OQE2UW5uYLCYXL9QEblu1djc67+-uj8uMlpzjnF4vXOqrO4tB5bRrmV5DSwfL6THSicwATku1USQLW90e3VEUIOMKOJwaHUsokaqLRN2BWSx4IAbHj3oTvsTzM8KUsMSDNk9pozDp9jiydDMOv8rikqZjQdjGgAOfkEwVElyiREcwEraU87pIxWwoXw36iOV0jWSrk0mVbVz65lG3RyyxmgEWrXcsGNR525XCnAdAPTabmmqWprWr2WSHQpm+h0dOl06ZykPo91WzaR3ExgVwn5gBNJlOu0Pp8OZ9oMnNKvNTHodckltO3DOe9oK6sGlU4CFI0TOVNgKUe9qRvWd+35xpIunODpzCVgAC6Vw1SUKkDSGQC0lYACcggB9VAVEsebj7oIBHJ5AobvB79AyWAAM24e9QlUXiSg3kIazfD9WB8TBPm-ZJIGQAAPQg9wCPBuAAEXqAAKFZWFQOgtQASjGcCDHQCosndQd1zRKAX0YYJVACd0mwgv81jwRgMlYGRmDvcjIDY5giLAWJIC8ZB0DgwVUFkMxBTo3ALz3Col3ogi+IErVD08ET8ik+pD2QGQaJXciF2qAzkjXVJ0jWFZ0EPPcaFs2BYB4OQz13A81lco8T04hjH2fQDPzicDgF-Lx-2wSB-OA0D8KgQiAngbh31UQ8oO86pIJguCsgQEpkBQgByHK-BS-LPnQ1BYny1T1L3PB8qXXCIHA0iQrCrJbOoezHNkNKNwyFhuBorJoMIXqUkgVKsgSpKUrGiCvACFVFNi5TAkSvdktYI4Or3Q8KEgEzqiMwpDrAY6FPCDA9wAa2Uq4yIY0K1h8TR-DPF8924AKhyBGIoCsmy7PKbq5BDSCZAS1QGge8bdNWLKhxiiadFqRzqDSUJiKiDDKumjbD1YerIEHAwFpwVH4FyndKeKhbBUo6iAh2vbieWjwH24a7ocNfNIFsmiSagTxPq5gB1EwzHJnmpmOo7F1ls6ARh1r3K8VB2G4UJ3s+76qT+89L2QY8KjB3TIeh8DwfhlGkcmn6ivcmmjdS+mqJ8Ib-u0mr8kFwSUY8J3qdyw86Yot2Pel1mkeFznkHF0xEH97swHJZr5dXJQLvGh27slRdNwsoPipd-PGPgli3vz3zqDWYwE96iIvvQTQba4hn3dz8ifqsndZM808w8ZrHVjU6JauJ8DTogBW13zrdHeDunS6egIXpkYTRKrp8a4CFAHCcM92KvHAHzKM9VCblvyct9vVE78i9d7w3jaOW-FuFQXH+H6yduBpzX-DkzOyLMFYpCnmdDOEAs6xSguUL8Fp3xURkPkLIGsCBfSOA7IuzsjggXYMEAA8lQPcIFRonz3GfKAnUTA6FPsgNckBEFw1XsgF8mkhaB2yk7EORxqEezoedEAcwgA). 

![screenshot_vega5_regression](https://user-images.githubusercontent.com/37225856/74951978-10e47f00-53ce-11ea-8442-5796196d9960.png)

**Comment by jheer** [comment]
Thanks! For other non-linear regression methods we mean-center the data prior to calculating ordinary least squares to improve robustness. This one was complicated by the fact that while we can mean-center the x-values, we can't do that for the y-values (as they must be strictly positive). I've updated the code to use mean-centered x-values alongside the untransformed y-values. The provided example now works without external transformation.
