### ISSUE TITLE
Webcola as alternative layout for force-directed networks

### ISSUE THREAD

**Issue by jandot** [vega/vega#2382]
For some applications, network layouts that are different from the default force-directed layout from D3 are important. It would be good if it were possible to choose from different algorithms. Force-directed leads to very poor layout when investigating topology; the webcola algorithm is superior for this application.

As webcola provides a simple plug-in replacement for force-directed in D3, would it be possible to include this into vega as well?

From the cola.js website: replace
```javascript
var force = d3.layout.force()
    .charge(-120)
    .linkDistance(30)
    .size([width, height]);
```
with
```javascript
var force = cola.d3adaptor()
    .linkDistance(30)
    .size([width, height]);
```
to change the algorithm.

Thank you.

**Comment by domoritz** [comment]
@jhoffs

**Comment by jhoffswell** [comment]
I agree that it would be interesting to include other graph layout options in Vega. However, my current understanding of WebCoLa is that the original unconstrained layout is quite similar to a force directed layout. Are there other features of WebCoLa that would be of particular interest for the use cases you are looking at? What particular advantages does the WebCoLa force layout have over the d3-force layout?

On the Vega side of things, what are the stepping stones for simply swapping out d3-force for WebCoLa? Are there current concerns or additional considerations regarding other graph layout options in Vega?

**Comment by roying** [comment]
WebCola (cola.js) offers "constraint-based" force layout functionality that is currently lacking in Vega (v5.9.1).
     https://ialab.it.monash.edu/webcola/

WebCola features would enable Vega to create:
- nested grouped nodes
- hierarchical nodes
- alignment of nodes

The automated force-directed layout with alignment and constraints allow automated positioning of nodes and edges.

WebCola can add new capabilites to Vega and enhance existing features including:
- diagrams and flowcharts (such as UML diagrams)
- organization charts 
- annotations for charts and timelines

A real world example use case of WebCola:
      https://stackoverflow.com/questions/25856530/cola-js-d3-js-force-directed-network-constraining-nodes-during-after-force-s

Other javascript libraries and software for creating flowcharts and diagrams:
      https://modeling-languages.com/javascript-drawing-libraries-diagrams/

The Vega team is already very familiar with WebCola: 
      https://github.com/uwdata/setcola
      http://idl.cs.washington.edu/papers/setcola/
      https://idl.cs.washington.edu/files/2018-SetCoLa-EuroVis.pdf

Suggestion: Instead of replacing the current Vega "force" transform, 
perhaps Vega can add new transforms built on capabilities of WebCola.

**Comment by jhoffswell** [comment]
I think that extending Vega with new layout transforms is a good idea and WebCoLa is a good alternative graph layout option, so I'm mainly trying to tease apart how this might fit into the existing Vega mindset and workflow and what such an extension would look like. 

Comparing to the [existing force layout example](https://vega.github.io/vega/examples/force-directed-layout/), I could imagine a WebCoLa extension that uses a similar specification style to connect links and constraints to the nodes in the transform (e.g., `{"force": "link", "links": "link-data"}` and `{"force": "constraint", "constraints": "constraint-data"}`). I think this approach would similarly require a separate dataset dedicated to the constraints as an input to the specification. This approach would provide the type of functionality you suggest, though would also require additional familiarity with WebCoLa itself in order to produce the graph structure and constraints needed for the layout.

I think SetCoLa would be an awesome direction to think about since the style may be more approachable for users without prior experience with WebCoLa. This option would also allow users to explore and generate constraints from within the specification without adding a separate dataset. I think the main concern here is that SetCoLa itself is a research prototype and has a variety of limitations that might make it hard to directly incorporate into Vega at this point. A couple limitations include: (1) the SetCoLa compiler generates constraints in WebCoLa, but has not been optimized to reduce the number of constraints generated and (2) not all constraints proposed in SetCoLa are directly expressible in WebCoLa, so the results may not be up to the caliber that we want to support. Both these limitations will have an impact on how practical this approach would be to include, and would likely require more work on the original system or in the context of Vega. That being said, I still think SetCoLa would be an awesome way to support constraint based layouts in the context of Vega and is worth considering more.

**Comment by domoritz** [comment]
Vega transforms can actually be added without modifying Vega (https://vega.github.io/vega/docs/api/extensibility/#transform). Maybe it would be good to create a webcola transform as an extension and if it gains tractions, send a pull request to Vega to add it to the core extensions.

As an example of a transform that is outside of Vega, check out https://github.com/omnisci/vega-transform-omnisci-core.

**Comment by jheer** [comment]
Thanks! This is a great case for an external transform, as @domoritz notes. One could copy the vega-force package as a starting point and create a new external package (e.g., vega-cola). I would expect such a package would also provide parameters for defining additional layout constraints. I'd be happy to help review that if someone would like to implement it.

However, as this is not part of "core" Vega, I'm closing the issue here.

**Comment by roying** [comment]
See question by user:
https://stackoverflow.com/questions/60424470/how-to-render-class-org-flow-state-chart-diagrams-with-vega-vega-lite
