### ISSUE TITLE
Guide titles should come before other elements

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2392]
Screen readers read elements in the order of the dom nodes. Vega right now generates the guide titles after guide labels and other elements. This means that a screen reader reads labels before the title. We should move titles to the beginning to give screen reader users context.

**Comment by jheer** [comment]
The order is intentional and not a "bug" (at least in the traditional sense). They are intentionally included later so that they are drawn on top of other items. We should start a separate, larger discussion on accessibility. We can of course consider re-ordering elements, but perhaps there are other cues / attributes we can generate to work better with screen readers?

**Comment by domoritz** [comment]
Ahh, I didn't think about that titles should be drawn on top of other axis elements. Let's close this for now. I agree this issue warrants a broader discussion.
