### ISSUE TITLE
Create new named color scales in config section

### ISSUE THREAD

**Issue by gabvet** [vega/vega#2521]
Is it possible to add new named color scales in config section?
Like this example:
```
"config":{
  . . .
    "newColorScaleName":["#800000","#FF0000","#FFA07A"]
  . . .
}
```

**Comment by domoritz** [comment]
You can set default color schemes in https://vega.github.io/vega/docs/config/#scale-range and register additional schemes with Vega (https://vega.github.io/vega/docs/schemes/).

**Comment by domoritz** [comment]
Ahh, you can define your own range as well. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlU3Co2Sx5ilQF91ESHiPolsAGbcjVDMAbVAId19GMTxkIzMDb00QjXCwA0jkMSScSABJAFkAEQAhAH0AJR1GJWo1KAp0CWywT1ZkVxTw9Lsss0hy7gJkJVKAFW4MPG57CqqausgGprNW9s6AXWcNZ3W3KAwjAGs+o2R4PDUNSAB3Rk0WMwBmAAZnvcgURmp8MwAmV-ew3g3E01Vq+k6kAAHvFOu52NV4pAMFCET5sAA2Z4dVIRHrNPJFMqVPBgy64qB4ACehGQfQAjqxvKTdKSqJBOjjwpAqbCKZA0UiUWjYGZpNi9qlIBlejkBkMRuNJtNYLNSfNJdzqbSGUylCyquzOZrIMCxAE+bjIOhqNRTrQYn1gax9eSrdq6TlGczmIa6Zr3AhGp60nDuV4aiHkVSzQFRWGtqlE2AuablJFwaGpbZkNdLVLYJ5uIco55vLBCOhTq7jZCI9QQ2EragY9xzUZRThgpBTklVFB2GI2pB1pztiAtkA). Does this work for you?

**Comment by domoritz** [comment]
We can reopen the issue if not.

**Comment by gabvet** [comment]
Yes, but i can't put the new color scheme in a select  box in signal. 
[See this example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmBTo8GQmFiJuAd0YzqYdFXXpqyMMvSMANgE8wPDRCZFc8VnU1MHswAGVkUzwfDwAzbnUwBKRjbgiwbhTAlE90PzoFJUg7ZRZsMAAOAAZGxQhIFEZqfDrRZtaoQnRlZXtqHsVK+FkUzuxQCDbXB2Q6+YW21D8pn3TYOoBtSEjlBSh2H1YVgF0lCABfJTuJtp0klZw1l+QADzw6yHiiWSYAMMhkrHQPjAABVgqFTBE1BV1pB0DIkOl-qhGMNksiFpA0jI8LFGAAvd5gACMADZ+m0Uq5UJTINR1LlCPi2gUUrBkH8cAAWR7PKCwToySF7HD7W5gT4EyXM-6DZIEFbyKAUSGXA6QPzIHw7GwKSDnXVXekE9j2E4fOUo+yEVgCsWG5DwP5WlHcbS6aVgWXrYNQTbbXZckOB-WG42m83XB0LG4hh7rJ5yhVtJUsyIuPmnSDai6UlJS5Cas221aQJ0u-5ID0Aa3Y3G+kDTC07lpAlS8eEwMszScgOf+QVQITCiMjbQiPn+-ZEfKByAAtBPiHR4LAKLOoGl1BhXcBIHg-CEG7vC4N1AWPmfgv9wah2KFC-2WZ+OxmQ2elrAh6oAcSYQKe56XvoQGsD4mCVugAbtLk6iFj8hAofo1gRLAAAU-asKgdCfgAlB23oLMAUAQSy0GwYWCGLqU+4omhGEqKY-KMMyOEGug6h4QihEkZqqCyCwAnhEJHHEZqn4SQRRHSaRnbrCmXZKD2lQIJCSJDusWZQGO+jtuRZ4XiyOjKqZyjcBg9g1ku45wtOkSFjMhp2uxfhkSOSzuP81S1HKv4USORlQN5pnUf87Boic1m2d4eiBqBYB0mAADsmr1JqACcmpUi01JUgVABMBUAMwFYKBWiAV6VUll1I5dS+VgKVRWlSV7Xle1VWpUV3W9VVYA1WAohJj2f5+SyHRdH8wVWgZo7oMq+jhihUXmf8Pj2Akm2+Wi-kPuK1CSgu+iqvyQQ+X+Nl2clp6Ofom7wuErmVu5PieY+k63cGRzIPmlKnqd53-HmoQFiFKIUuydRlj4fKVjIjDwJSeDqJcwUaaKqLfLpKX6ZA6SMMgxIxdwBC2YW2l4sZH6JfZOCI8jVHMPTUAALJiYgbnpMe-wAKTsP9YEjqT5OupAyQpF6YrwDp-yRSoTPJazFbs28-wABLIfukDk1MqirKlMvoG+SOm1GBKsIQ372jbKJBL8NZg5CjGSXQxaXGAAC8AdgI0YAAPxgAA5FzOKo-N4dgDg+GET7HgB371KlaHEcAHLcLIccJ4J3s6h4AA86eZ4nRclmAADUEdYM0TioPnYDyUnxdgGu6fEbX9eN4Qzcdql9ypSp6nprjvZtMk7gyMoAZBqFf4zEaDbcDsB1-tF+hskMZMU1FHMsgYFDUHQMLBK3AANABipGH28N9iaSFJ1FS5Ujq8yQAApDCMDh1BqiOXeIwpYABlybUFqCdCUHtMLIE6PgTu1IaRDwnhATSGw+JNgXsOLe219CRE9AbRkNMHzPSos5BErkYYEiNtwE2jsoyG2JO+JhNtIDthOorTmnC3Jk2+oxbytC-zeW4UrfQKtCQCJ+lhFCIiAaBT5g+ZOPQFEojmt0cRvCpGxTnm-dRBI8C5x8DoTkMCzpwPZsyJ+R5TBt0UkETU4cRZgCFsoNxABJBuwchaEHDj3Ou4ccBxzrpXTcvdw5X3DmgqMhjIB2wdvKYeB5fAXXlJAOmLINr8I8k5P6Y90HBjHt2EADwgA), when i select "mycolors" nothing changes.

**Comment by gabvet** [comment]
> You can set default color schemes in https://vega.github.io/vega/docs/config/#scale-range and register additional schemes with Vega (https://vega.github.io/vega/docs/schemes/). I know it doesn't fully address your question but it may be a start.

I can't to this in Kibana, from what i know.

**Comment by domoritz** [comment]
Hmm, maybe there is a bug then. Can you boil this issue down to a minimal example so we can debug it?

**Comment by gabvet** [comment]
This is another minimal [example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmHbpYjeMfTqwSK3jDIAHulSEANsnlgA7s0RgKdDdWZDA3dHZkN1gwWERubxkwVkJZMFRuVlhQ+Kp1OgUlSF9lFmwwABYABirFCEgURmp8coAmGrqoQnRlZUYZanLRRSLldDxMHABtJQhQCAWoGRdkcsgJ9g9CxfrA4LVymZ2F4Eh4cZpudQBPNYMFKBdMmTw2gA4AX07j0-O8S5uawAQg9IE9WC8hqIvrMdr8LtQrrd9ABhUHgyE4CoAZhhxzmZwRSLWABF0RkIa8cABOACMePx8P+iMB+gAouTnlSwG96bCIABdWEfJQCkb1eCyABmTWw8wWkHU6AGqxw8sWkFQ10lbiusEOiuQylB1yiuu8oM2IUgQsWIogMKKZmoy2ih1h6oVy1Qqq6QWQBFWXkge2t02KiGYQag1HUyFuYHkkE26HgAGsbd8Fex+sa1fyFf1CKxuZBsh54K8sxruNpdPrpgWNVqdXrtviIFMI1HQbH45BE8nwunM02Fl248bg6a3ObLfsbWPbTt7QtV2KQE7zh4G2AjicC5Bvb7II4EP72xq8NdCCeTDIp4flNwMP1yqcxhM1hstsGZVE8ygP4AVuBkNSVFU1hKMpqz9Xp+kGHAqjoKphkPdRnkAvB1BCYUs09epjzWa5z1-J8X3QN81UgT9JigH9o0gf83EAsEKUhMCvXMX1sJCWDFWVagT0aZpXjwj1DyI-RW3US8FWvW81jcfpkCsOT6ggoT3zLJpXTWboPEDSBOPqZ9Xz0MAP3GOj1giX8oGY1iMVeEyoAAL2QDDyilIJsmDGRuPKXjkGFUVxUeRwDkbRZgCgK5GGQTEoHYbgCBfUFSJPM9t1WMBONiyB4sS0sPClKsoEy4jKrysLN3qDB1DTXd9zmQ8FJPONK3UhyMNQbTaOwWzNlWVzIESyVVHfMcxpeTypo7epHG0yr9Gyi8-wSli1mAllQNgjVoMQZacrWNb7OTZVAPpfaFWRSyyxO-QSJOjaALWZzjJu+prlaY6Lyeyrg1DX0qlXY5XPqFJP19AidiYxhZz+rZpO4XVZNerb9A+sGVwLHH1xAEUgA).

**Comment by domoritz** [comment]
Can you add `category10` (one of the official schemes from https://vega.github.io/vega/docs/schemes/) to the dropdown?

**Comment by gabvet** [comment]
Yes, i need to transform this code `"range": {"signal": "palette"},` in this one `"range": {"scheme":{"signal": "palette"}},`, [this is the example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmHbpYjeMfTqwSK3jDIAHulSEANsnlgA7s0RgKdDdWZDA3dHZkN1gwWERubxkwVkJZMFRuVlhQ+Kp1OgUlSF9lFmwwABYABirFCEgURmp8coAmGrqoQnRlZUYZanLRRSLldDxMHABtJQhQCAWoGRdkcsgJ9g9CxfrA4LVymZ2F4Eh4cZpudQBPNYMFKBdMmTw2gA4AX07j0-O8S5uawAQg9IE9WC8hqIvrMdr8LtQrrd9ABhUHgyE4CoAZhhxzmZwRSLWABF0RkIa8cABOACMePx8P+iMB+gAouTnlSwG96bCIABdWEfJQCkb1eCyABmTWw8wWkHU6AGqxw8sWkFQ10lbiusEOiuQylB1yiuu8oM2IUgQsWIogMKKZmoy2ih1h6oVy1Qqq6QWQBFWXkge2t02KiGYQag1HUyFuYHkkE26HgAGsbd8Fex+sa1fyFf1CKxuZBsh54K8sxruNpdPrpgWNVqdXrtviIFMI1HQbH45BE8nwunM02Fl248bg6a3ObLftRx2JUSbrSqpAx7advaFjuxSAnecPA2wEcTgXIN7fZBHAh-e2NXhroRryYZFOL8puBh+uVTmMJjWDYtmDGUojzKA-gBW4GQ1JUVTWEoymrP1en6QYcCqOgqmGC91GeCC8HUEJhSzT16ivNZrjvEDP2-dBfzVSAAMmKBgOjSAwLcCCwQpSFYK9cxfSIkIUMVZVqGvRpmleUiPQvSj9FbdQHwVJ8XzWNx+mQKxVPqeDJL-MskDQVVTmdV01m6DxA0gD4BPqL8fz0MB-3GVj1giECoC4niMVeByoAAL2QfDyilIJsmDGQhPKETkGFUVxUeRwDkbRZgCgK5GGQTEoHYbgCG-UEaOvW8j1WMABMyyBsty0sPClKsoFKqjWqqpKD3qDB1DTE8zzmC91OvONKz0nz8NQIyWOwTzNlWQLIFyyVVD-MclpeUK1qXKBHCM1r9HK+9QJy7i1iglkYJQjUkMQfaKrWI7vOTZUIPpa6FWRVzjPvfRqIek7wLWfy7I++prlae7fqgf7jqgUNfSqHdjkC+oUgA31yJ2TjGFnKGtiU7hdRUwGzv0EHke3AtKb3EARSAA). But my named color scale still doesn't work.

**Comment by domoritz** [comment]
As far as I understand the issue is that

```json
  "config":{
    "range": {
      "mycolors": ["red", "yellow", "blue"]
    }
  },
```

does not create a new color scale but instead sets the default range. I marked this issue as a feature request since I don't know whether we support what you are asking for right now.

**Comment by jheer** [comment]
I believe the issue is that here the spec is defining new named scale ranges and then trying to look them up dynamically. However, named ranges like `"category10"` are added to the specification at _parse_ time, and so can not be accessed at _runtime_ using signals.

While schemes can be dynamically added (via the Vega API) we do not currently support defining new scheme entries directly in the config. In general this would be difficult to do, as schemes are not defined per-view but rather for the entire Vega library. So if multiple specifications were used on the same page, they might conflict in their use of schemes. We'd have to invent a tiered approach that allowed schemes to be name-spaced within a View only.

As a way of avoiding all of this, I would recommend defining your custom color palettes as individual signals instead, and then setting them to be the scale range. [Here is an example spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmHbpYjeMfTqwSK3jDIAHulSEANsnlgA7s0RgKdDdWZDA3dHZkN1gwWERubxkwVkJZMFRuVlhQ+Kp1OgUlSF9lFmwwABYABirFCEgURmp8coAmGrqoQnRlZUYZanLRRSLldDxMHABtJQhQCAWoGRdkcsgJ9g9CxfrA4LVymZ2F4Eh4cZpudQBPNYMFKBdMmTw2gA4AX07j0-O8S5uawAQg9IE9WC8hqIvrMdr8LtQrrd9ABhUHgyE4CoAZhhxzmZwRSLWABF0RkIa8cABOACMePx8P+iMB+gAouTnlSwG96bCIABdWEfJQCkb1MzUZbRQ6w+Y7SDLVCrfTqdADA7fBaQPYhcry47FRDMZAAWmo6mQ11Nm3Q8AA1ocjSbQRaraDbQ7IGL+drLcpTdcom4Ejb9k7-aCg24Q94PeGffioP7zZbkDIw3rppBI15IG70-G9ULjiLFgy5r7FSs1t0PARVlrdkEs1BvMb-qmrWG7Y6m1B2P1lPrffV+oRWNzINkPPBXv36txtLpYLKk-UUwWM5s9Qvte2TV3rZ6+6O-cgA9HY5nVmeSzsywtHz6iggggdpnKq0qVVBHG+tn7dZrkIX9IBMGRhyA5RuAwfp9UgMYJjWDZAKgAAzRgomHfQ-gBW4Kz9dVqDAkoyiA7pen6QYcCqOgqmGKt1GeHCwDwdQQmFLUDW1H81muADGyrGC4L0MBTiQyYoFQxsMKwtxWLBClIUI+oZHMX92JCIC1Q1NZGmaV4uK-Q0+Nw7gQ3UbYFTwECwLcfpkCsazFhzYjf1OSVpTWXSSNgKY62QBsBUgVSVFg9B4JwCTxik9YIjQyBMOwtYMVeMLIAAL2QZjynQoJsjzdT4E0jjkGFUVxUeRwPzAI4TigK4sMxAduAIWDQUEtZ-3OLYwEI4BGs0dMpw8dD5ygLr9AE3rVn6yqQCKDB1HtVdP0WHj6ls0CfOQOcXO1dDmNQBDJOweLNlWDL03gbhVBHJNIBGnKHvXSBHAQqa-y6vNkoUtY8JZAi93qMjEE+2bup+gd1VY+kQagZFxOnSHpuhpL5MUtLQoRyBrlaCH3349HdV-KpH1LPdIBSJCPLPepMJjQmtnMyzQT+rHlPSs8KafCrBRAEUgA)
