### ISSUE TITLE
domainMin only works if less than min(domain)

### ISSUE THREAD

**Issue by ianhoolihan** [vega/vega#257]
E.g. if I add `"domainMin": 50` to the scale `y` of the bar example in the Vega Live Editor, the minimum of the y-axis is still 0. However, `"domainMin": -50` works as expected, and sets y-axis minimum to -50.

Is this the intended behaviour? If so, how would I do what I'm trying to (e.g. set the axis limits to (50, 200))?

**Comment by arvind** [comment]
Hi @ianhoolihan, you're seeing this issue because quantitative scales (like the linear y-scale in the bar example) default to having a zero baseline. This can be disabled by setting `"zero": false`. On doing so, the `domainMin` is respected, and overrides the minimum value extracted from the data set.
