### ISSUE TITLE
Ignore key-value pairs in spec if value is null or empty.

### ISSUE THREAD

**Issue by ianhoolihan** [vega/vega#258]
By this I mean I mean setting e.g. `"domainMin": ""` would be equivalent to not having `domainMin` inside the spec. For this example, at least, this is not the case. Two reasons for looking at why one might want to do this:

1. It would mean you could have a default spec prepared with all the options listed for each of the properties, with ignored ones being set to `""` and hence not being used in the rendering. Users might find it easier if they can see all the options before changing them, instead of having to figure out the option they're looking for first. Hopefully that makes sense.

2. Following on from that, if you're writing a GUI on top of Vega, this would make it easier -- you can just ignore e.g. `domainMin` by setting it to `""`. Currently, you'd have to remove the `domainMin` key, and then add it back in again later if you want to edit it. (Maybe this isn't too valid, as you could get your GUI to e.g. parse the spec and remove all empties first. It would make testing harder though, as you couldn't then just paste the original spec into e.g. the Live Editor.)

I don't think it's a big job to implement (just recurse through all key-value pairs and remove those with value = "") and something I might even be able to manage (not that I've done a PR etc before ...). @jheer, do you think it's a worthwhile addition?

**Comment by arvind** [comment]
Hi @ianhoolihan, I'm closing this issue out because I think such a feature is best implemented within the higher-level tools that require it. My concern with implementing it within Vega is that `""` is not always an invalid value (e.g., it is valid for the `text` property of text marks, and can be a useful valid expression to use with signals/formula). It's also difficult to predict what future properties we might add to the Vega syntax, and what their valid values might be. 

For the two use cases you've described though, Vega 2.0's new [JSON Schema](https://github.com/vega/vega#build-process) might be more useful.
