### ISSUE TITLE
Removing data using View component when data comes an URL

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2597]
The following issue is a bit of a nuisance, and difficult to reproduce, since it is based on the View component.
Please move to the right repo if this not belongs to Vega-Lite. But since its a Vega-Lite spec, I start here.

When trying to remove the data from the View object there are arising a few problems. Not sure exactly when it happens, but it seems to happen when the data comes from an **URL** with a nested data object where the vega-lite spec applies some transformation to this data.

This observable notebook shows GOOD results (data comes from a **`values`** object):
- https://observablehq.com/@mattijn/untitled/2

This observable notebook shows BAD results (data comes from a **`url`** object):
- https://observablehq.com/@mattijn/untitled/3

For both options (data from `values` or data from `url`) the following function are tried:

| function | `values` | `URL` |
|----------------------------------------------------------------------------------------------------------------|----------|--------|
| `view.remove('SOURCE', view.data('SOURCE')).run()` | OK | NOT OK |
|  `view.change('SOURCE', embed.vega.changeset().insert([]).remove(view.data('SOURCE'))).run()` | OK | NOT OK |
|  `view.remove('SOURCE', function() { return true; }).run()` | OK | OK |

Only the last function is able to remove the data in both situations. Its this intended?

---

_Question behind the question:_ 
This issue describes only the data removal part. A correct change of URL in the data object seems not possible. Data seems to be inserted, but no rerendering of the VL-object takes place.

What is the suggested approach to change an URL with data object within a Vega-Lite specification?
Currently the workflow is to compile the Vega-Lite to Vega first, then define the data-URL component as `signal` and last apply a `view.signal(name[, value])` function on the View component to insert a new URL.

**Comment by jheer** [comment]
It looks like Vega is working as intended. The view.remove (and changeset.remove) semantics are to take the data provided and remove it if it exists as _input_ data for that data stream. In your example you are using the transformed _output_ as the argument to remove. Since the data has gone through a flatten transform, the output objects are not the same as the input objects.

If you want to remove data from a dataset, in general I recommend using a function argument (e.g., a truthy-valued function to remove all the input data).

As for your other question, Vega supports signal-valued URLs in data definitions. Changing that signal should remove the old data and load the new data. I don't think Vega-Lite supports this currently.

**Comment by mattijn** [comment]
Thanks for the comment. This explains at least one confusing behaviour in Vega-Lite.

There is no difference in Vega if the data is parsed by `values` or by `url`. Since the data can be removed by console using this Vega spec:
```json
{
  "data": [
    {
      "name": "SOURCE",
      "url": "https://tsws.hkvservices.nl/mangrove.ws/data.ashx?function=dataportal.db.getdata&parameters={database:%27vega%27,key:%27nested_data%27}&contentType=application/json",
      "format": {"property": "nested"}
    },
    {
      "name": "data_0",
      "source": "SOURCE",
      "transform": [
        {"type": "flatten", "fields": ["foo", "bar"], "as": ["foo", "bar"]}
      ]
    }
  ]
}
```
 But in Vega-Lite the compiled Vega is different when data is referenced by `values` or by `url`.
