### ISSUE TITLE
Support signals for descriptions

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2638]
I would like this to work: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaTUoCDTLikAGzQgA5AAk4+-WwAEAdTaL9s4yAC+MgO41Z9NABYABgCZeB0sNAAmIJkcJFlZGnEyNAEZWSRMFFQAbVA9BDgjTKZ9QpliAwYFNFyQKAzyBwBPIwBBaRAkBDYGcUxIgA53UHrMRsUW9AAhDq6evpSBYbqGsmajAGFZ7t7+1D8AZmXR8cmQABFt+b2ATgBGY9X19ABRK920AYepEaeJowAYu8FqgBEcfisxmt-ugAOLAvZ3G6PKHPECmBGfADsrgAuniZNADNUcnkuoV0AAPImlDqYJo4CkgJhIcSyDqyNjIRJoUDpTJFJAlMogABmNAs7PQJ2hLXcIEUrLITK8PhgHVi8USyVQAUoAVSCvmUswiiqy3yTKaNJFnO5Gj5GSyIGKtJk4slRjmH3l4hoUAppqqMkVSSZoTI4QJnUpJNqDglIOZbGwXI6NqM1PqtOWCbgSdKov6hOzVoz0eQigA1hAaqB6YyjIo4FBi2LFGnNHInYLhW40gooMpVOpeSBtLoDEYzBYrNYAGp8Fzy-NQNjyMf5saKMeUscZqkZ90SpxGGXreWq3xdg8gLPEjostlob4gSZaUtGa2f4+e9DehZ5SaCJ90-dBvwfcpKgpAJXHlBgcH5ClQHFSwxwqfQqiMCAxgsEosLgkI2FIHcu1QwwuwwrD0Gbdk4Lg-EgA).

The workaround is to use the encode block.

**Comment by jheer** [comment]
This is doable, but I chose not to do it because (a) I wasn't sure it was needed (can you motivate the use case?) and (b) it can require adding another named signal to the namespace, which could potentially conflict with existing specifications.

Also, using the encoding block is not equivalent: as I'm sure you know, using the top-level encode block adds ARIA annotations to the root scenegraph group element, not to the View container DOM element (which is what description targets).

**Comment by domoritz** [comment]
I see. I think it makes sense for top-level description to not be a signal but what about description on the rect mark in the example above? That description is used for the mark container and can be useful to summarize/group multiple marks (https://github.com/vega/vega/issues/2583). Would it be difficult to support signals there as well?

Having signals enables custom descriptions that depend on the data as well as customization while not changing the spec such as localization.

**Comment by domoritz** [comment]
I guess we can add a group mark around the marks to achieve what I am suggesting.

**Comment by jheer** [comment]
Yes, or use a custom encode block. There is nothing wrong with that!
