### ISSUE TITLE
Update SVG output to play nice with SVG optimizers?

### ISSUE THREAD

**Issue by moltar** [vega/vega#2640]
Sorry for a vague subject, but I am just not too intimately familiar with `vega` and just use it in one context only.

As you can see the graph is blank.

Inspecting the SVG markup the columns are still there, they are just not painted and thus blend in with the background.

Script that generates the graph: https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/graph.ts

Generated SVG Diff: https://github.com/moltar/typescript-runtime-type-benchmarks/commit/09db33972f1f6e1f87d1db4a72b5c9e4cd88ee08#diff-a9316fd460d64045bb8190f11727bcd9

Visual Diff: https://github.com/moltar/typescript-runtime-type-benchmarks/commit/13cc94a74312eff42f980a9f2e7fe5a30a00230a?short_path=a9316fd#diff-a9316fd460d64045bb8190f11727bcd9

Any ideas?

Thanks.

**Comment by jheer** [comment]
Do you still have issues if you upgrade to Vega 5.12.1? That release fixes an SVG issue.

**Comment by moltar** [comment]
Still shooting blanks:

https://github.com/moltar/typescript-runtime-type-benchmarks/commit/09db33972f1f6e1f87d1db4a72b5c9e4cd88ee08?short_path=a9316fd#diff-a9316fd460d64045bb8190f11727bcd9

**Comment by jheer** [comment]
It looks like your SVG file is not the SVG exported by Vega, but a modified version run through an SVG optimizer (I see SVGO being used in your script). It looks like SVGO is stripping out the fill color from text marks. Apparently it is assuming that since black is normally the default fill color it is safe to remove, but in this case that is not true due to conflicts with the internal stylesheet. For the bar marks, it looks like it is moving the fill color to the parent group element, but the path elements for the bars no longer inherit this value, again due to the stylesheet.

We can consider modifying the internal stylesheet further to help avoid issues like this. Nevertheless this looks like a possible bug in the optimizer, as it appears to be oblivious to the existence of an internal stylesheet.

**Comment by moltar** [comment]
@jheer thanks for looking into this. I'll open an issue with SVGO repo then also.

**Comment by moltar** [comment]
@jheer wow Jeff, this is a huge fix. Thank you!
