### ISSUE TITLE
Wind example does not generate correct image in node

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2662]
Running this script generates an image where all marks are at the same x. 

```sh
packages/vega-cli/bin/vg2svg docs/examples/wind-vectors.vg.json -b docs > wind.svg
```

<img width="801" alt="Screen Shot 2020-05-27 at 15 54 14" src="https://user-images.githubusercontent.com/589034/83080136-526e7100-a032-11ea-89a2-8e44f285c532.png">

**Comment by jheer** [comment]
Update: using the SVGStringRenderer in the browser produces the correct result, using `vg2png` at the command line produces the same incorrect result. So the problem indeed seems runtime-specific and arising at the evaluation layer, not the rendering layer.

**Comment by jheer** [comment]
Ah, the problem is due to the windvectors.csv file encoding, which had a byte order mark (BOM). In node (but not Chrome) this results in the BOM being included in the field name of the first column of the parsed CSV header. I updated vega-datasets and released a new patch version to resolve the issue.

**Comment by domoritz** [comment]
🤦‍♂️ oh wow. Thanks for finding that.
