### ISSUE TITLE
Should be possible to configure a bin-ordinal scale to interpolate the range before discretizing

### ISSUE THREAD

**Issue by willium** [vega/vega#2692]
Consider [this](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SsjqANblXk6YeXCyUGzKTmRooAAeIyBxNHCCyuUAEokeXvbmeZgAnuHlAI4MfjqVOqQgTSAbE1Mzc+gAssFqAPrh6o8A4khRcutbcLv7skOphoJzO-Ss6ku01m5X0UCgM3MwO+Sk223QewOdGBJyUTCcaEw6gYcCUJhCEy65i8glMf3QMCgZSU6j8ZHpAG0QExBCS8uo4HMALoNUUNIA) Vega-Lite spec.

It creates this scale for color:
```
    {
      "name": "color",
      "type": "bin-ordinal",
      "range": ["blue", "red"],
      "interpolate": "hcl",
      "bins": {"signal": "bin_maxbins_6_Acceleration_bins"}
    },
```

From the Vega documentation, bin-ordinal discretizing the provided range (in this case, it's provided as a color array).
> Input domain values are discretized to the appropriate bin, which is then treated as a standard ordinal scale input.
This of course makes sense for a user who wants to provide colors for each bin-step. 

However, my actual intention here is for the the range to be first interpolated as a continuous scheme, _then_ discretized for the bin ordinal scheme as it when you provide a scheme as a range, rather than a color array:
```
 {
      "name": "color",
      "type": "bin-ordinal",
      "range": {"scheme": "blues"},
      "interpolate": "hcl",
      "bins": {"signal": "bin_maxbins_6_Acceleration_bins"}
    }
```

In accordance with the same pattern afforded by the Scheme definition:
> For Vega 5.0 and higher, if a color array is provided, the colors will be interpolated to form a new scheme

**Comment by domoritz** [comment]
It looks like we can already so this but we don't allow it in Vega-Lite. [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEzjQATjRyZ289AEEABNCTY46nILaZjMNgHcassobvqIcHA-OGks5YYINIJqhjg+FIJWshCGAGZs6obESJpsDLFQqRCUiiqmKKigDOqCaPmYSARZ7lIy8gC+SsjqANblXk6YeXCyUGzKTmRooAAeIyBxNHCCyuUAEokeXvbmeZgAnuHlAI4MfjqVOqQgTSAbE1Mzc+gAssFqAPrh6o8A4khRcutbcLv7skOphoJzO-Ss6ku01m5X0UCgM3MwO+Sk223QewOdGBJyUTCcaEw6gYcCUJhCEy65i8glMf3QMCgZTJsEQ9IA2iAmIISXl1HA5gBdBoihpAA)

**Comment by domoritz** [comment]
Closing since it works: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhA4kAE3k1xZNAJnykmFKgDaocUgRw0IbUwA2JmcSQWGcCGn0goW8mwBOAT1MBBaRAjNgZxTDQAJgAOAF8pUDdMDx9TACFA4NDw1AEBOIT3Mi9fdABhDIQQsLQAFgBmfNdC4tMAEQqq7IBOAEZGxOSSkABRDqy0KL74pqSilPQAMTHqnIbpgbmhgHFl7J6u-ub5kAAJXYmAdhiAXRlMTyRxCAAzLwRnUExvHBN0JmVAs8aHALPJTJlqjIkE49EFKlkAPoQbSecJQ+FhBFwcRg24gZAAD3+TzUMggNDIhgspmJThkcAJSRWugADFIeiyWdcbjcyW4rDCXIZjKYoGwLF4mIEvj8acoALReJRUwIPFS-UBcRC-XQgTxwMEySwOEDcmTKJKeHDi9ymGBQalG5QwzUUlV-Z0gGK8kBWMjY+SC0BAizU9BiiWeKU8oA).
