### ISSUE TITLE
Canvas renderer does not size symbols correctly

### ISSUE THREAD

**Issue by armsp** [vega/vega#2738]
I noticed a peculiar bug while trying to solve [this problem](https://stackoverflow.com/questions/62606655/how-to-make-a-chart-with-svg-marker-whose-size-increases-in-only-one-aspect-or-s). The graph that the editor renders is different from what is getting exported. The rendered graph is correct and the exported graph is wrong.

**Vega Spec**

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A simple bar chart with embedded data.",
  "background": "white",
  "padding": 5,
  "height": 400,
  "style": "cell",
  "data": [
    {
      "name": "source_0",
      "values": [
        {"a": "A", "b": 1.5, "c": 0},
        {"a": "B", "b": 0.5, "c": 0},
        {"a": "C", "b": 10, "c": 0},
        {"a": "D", "b": 1, "c": 0}
      ]
    },
    {
      "name": "data_0",
      "source": "source_0",
      "transform": [
        {
          "type": "filter",
          "expr": "isValid(datum[\"b\"]) && isFinite(+datum[\"b\"])"
        }
      ]
    }
  ],
  "signals": [
    {"name": "x_step", "value": 20},
    {
      "name": "width",
      "update": "bandspace(domain('x').length, 1, 0.5) * x_step"
    }
  ],
  "marks": [
    {
      "name": "marks",
      "type": "symbol",
      "style": ["path"],
      "from": {"data": "data_0"},
      "encode": {
        "update": {
          "opacity": {"value": 0.7},
          "fill": {"value": "red"},
          "stroke": {"value": "black"},
          "strokeOpacity": {"value": 1},
          "strokeWidth": {"value": 1},
          "shape": {"value": "M -1 0 L0 -10 L1 0"},
          "ariaRoleDescription": {"value": "point"},
          "description": {
            "signal": "\"a\" + \": \" + (isValid(datum[\"a\"]) ? datum[\"a\"] : \"\"+datum[\"a\"]) + \"; \" + \"b\" + \": \" + (format(datum[\"b\"], \"\"))"
          },
          "x": {"scale": "x", "field": "a"},
          "y": {"scale": "y", "field": "c"},
          "scaleY": {"field": "b", "type": "quantitative"}
        },
        "fill": {"signal": "gradient('red', [0,0], [1,0])"}
      }
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "point",
      "domain": {"data": "data_0", "field": "a", "sort": true},
      "range": {"step": {"signal": "x_step"}},
      "padding": 0.5
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {"data": "data_0", "field": "b"},
      "range": [{"signal": "height"}, 0],
      "nice": true,
      "zero": true
    },
    {
      "name": "size",
      "type": "linear",
      "domain": {"data": "data_0", "field": "b"},
      "range": [0, 361],
      "zero": true
    }
  ],
  "axes": [
    {
      "scale": "y",
      "orient": "left",
      "gridScale": "x",
      "grid": true,
      "tickCount": {"signal": "ceil(height/40)"},
      "domain": false,
      "labels": false,
      "aria": false,
      "maxExtent": 0,
      "minExtent": 0,
      "ticks": false,
      "zindex": 0
    },
    {
      "scale": "x",
      "orient": "bottom",
      "grid": false,
      "title": "a",
      "labelAlign": "right",
      "labelAngle": 270,
      "labelBaseline": "middle",
      "labelOverlap": true,
      "zindex": 0
    },
    {
      "scale": "y",
      "orient": "left",
      "grid": false,
      "title": "b",
      "labelOverlap": true,
      "tickCount": {"signal": "ceil(height/40)"},
      "zindex": 0
    }
  ]
}
```
In the editor it looks like so -
![image](https://user-images.githubusercontent.com/12681262/85921131-7a522e00-b897-11ea-95ee-96a0a7f1bad5.png)
However, when I export it OR see it as a preview via VSCode Extension, then I get the following -
 
![visualization](https://user-images.githubusercontent.com/12681262/85921156-abcaf980-b897-11ea-9525-59624a98fa86.png)

**Comment by domoritz** [comment]
How do you export the graph?

**Comment by armsp** [comment]
I used the Export button in the editor itself.

**Comment by domoritz** [comment]
Which option did you pick? The PDF render uses a service while the other options use the Vega view directly in the browser.

**Comment by armsp** [comment]
The PNG option

**Comment by armsp** [comment]
You can try [here](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAEEGghwAbONqZJF22OczaA7nRjbETOLPmztspJirSQZqABrMkU2BnFZNBBbGDo4PxwkNxpxMjQBGXgaMiw0ABYABgKZCEwAT2MoqDhDQz8vHzQAbVBxJAR49DEGRWqAfQK-YiRDBgVm0BQtPyY0AEZKDJAoNAKAXylJqIAhGdXFmRXUdc2QKZAAYT3UOeLl1Y2t9AARa7nDh4BdR5A2jqiGkgBn5ur1OiBQf1BjJMIokOIIAAzNiKBATEDlHDgxE0QyYOCKPxwAAeOEJ6BoEAAaiMaLIABQNBgIJoAHX87M+AEptAAyXnaSkAMRScXpAGomSz2UxOVyQGtvp8Stk2oYIOi-uDiX1SnAcEMRmM0AAmE6tdrg+yyeh+Bg4BrgswRCCJaqMtjIFL0gDkxJ9XMoxlS9Ck2ne2gKix5ACptDq9QbFTJkIpAhrUC1fpaoqn035MeCIGUEEw2HUSuVKpmQIlbcqQIjQmjUKBAQDvEDBhsQHBxFA2PI0KB7Y7hyA2G66GVx8NRp0owB2Hs42qzo3gxSuBWV0KBTqgOfG9BMQxIII7iGwtj7gDyU-K6-n8x7pT3cAA6nTba2QEfOnMr4wEgWJPseIAALLaAAtHMkbaAAMgUMG3IhcHdjI5g0EgABK5ZwM8ChQMoqjqGB4I4GwKSYJe8hKCoagSOOehkGqUTskg7LaOK2jsqgvEgNx2j0pSNKGHSjLeMybJnHK2gAPyeFJ0qySAnzaPx7LspKykyZxak8jx7IANwCUJMpcUZaBmTx9LIqi3iSZg0kWWpYZaSAXLyj2xLMVAIzan4OI1JE6AoD2M6-tAAVRDOMjBYYoX3K+-nGAAmuOCVJbMMJlKB6AAI4MPCag+GopAKiuuJ1FFqojFEIRJDQfaYL6W6yD6YZNMUBTKtoTTvL13lrMmEKpeMmYWv86C+bl+W1lR4g0TIsiekgKTju26CAsC8XNYlUQoCUKI0agsJjD2cKpAeV76sxdU1SACb4kmPaJMkqT7AIPxarFBZ5eC4niHA5j1GtG2-ltcidrtjb7dll5XWQnRZixbHoFkOQ0RsvUyOINDVGg51wDIABeBJsETigXacv1dDQ5P-fNQMg4SK3gxobadh2Piw1lUSzJd8LI80xQAMwAGxzA25OhFTF0NkgxITaj41-TIKLNUtUTGIiy0gCEdIAMpqzNfiG6FxMwgTgQXGE2u1ax9XoNUuL0pjWAEIU3ns16GiIiMEAkyAZ4uOqaAB+qwdYVMkdBymSsAKLEviDt3AgKTJ6np13GoQQZnHwekyk8i+ccPzRdWT1+JrLUC2w2CeubyihYX1uYFXR0h0gYeaOJrFRMoWN+KHNSaKk1Ymoudyj4Y2xIEHLO5nSsiVDIs+3qQihngaZ3U0XJckg8pyV+CcUTsodfoLr+sWxHgfB6VVc5d3YebwSO-y4-Nt2+Ep2gGjZ2yw4Buw9pgL2BQfYgGLhEI+5dvhAA)

**Comment by domoritz** [comment]
Ahh, the bug is in fact the renderer.

<img width="1023" alt="Screen Shot 2020-06-27 at 12 48 10" src="https://user-images.githubusercontent.com/589034/85930852-7cef5c00-b874-11ea-9be8-bde47c903366.png">
<img width="1010" alt="Screen Shot 2020-06-27 at 12 48 05" src="https://user-images.githubusercontent.com/589034/85930853-8082e300-b874-11ea-92d0-9071944dc803.png">

**Comment by jheer** [comment]
This is funny because symbol marks are not supposed to support scaleX and scaleY properties. So the problem is actually reversed: the Canvas renderer is correct and the SVG renderer is wrong, despite the design intention. Symbols should be uniformly sized using the `size` attribute. One should use the `path` mark (not the `symbol` mark) to use arbitrary x/y scaling.

The bug in Vega is that the parent logic for items drawn as paths supports scaleX/Y as part of the SVG transformation, but provides specialized logic for Canvas for the `path` mark only. I need to look at this more closely and decide whether to limit the functionality to the specification or to add more general Canvas support.

In any case, [here is a modified spec that uses the path mark to achieve the scaled triangles.](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAEEGghwAbONqZJF22OczaA7nRjbETOLPmztspJirSQZqABrMkU2BnFZNBBbGDo4PxwkNxpxMjQBGXgaMiw0ABYABgKZCEwAT2MoqDhDQz8vHzQAbVBxJAR49DEGRWqAfQK-YiRDBgVm0BQtPyY0AEZKDJAoNAKAXylJqIAhGdXFmRXUdc2QKZAAYT3UOeLl1Y2t9AARa7nDh4BdR5A2jqiGkgBn5ur1OiBQf1BjJMIokOIIAAzNiKBATEDlHDgxE0QyYOCKPxwAAeOEJ6BoEAAaiMaLIABQNBgIJoAHX87M+AEptAAyXnaSkAMRScXpAGomSz2UxOVyQGtvp8Stk2oYIOi-uDiX1SnAcEMRmM0AAmE6tdrg+yyeh+Bg4BrgswRCCJaqMtjIFL0gDkxJ9XMoxlS9Ck2ne2gKix5ACptDq9QbFTJkIpAhrUC1fpaoqn035MeDEraSuVKpmQMWYCBlSBEaE0ahQICAd4gYMNiA4OIoGx5GhQPbHQO67i6k2QMNRuDFK4FaXQoFOqAp8b0ExDEggvOIbC2EuAOp020T1edOadqsjs9RACy2gAtHlI9oADIFR9zN-Pj8ALR35g0EgABKbDGM8ChQMoqjqNeRpFmwKSYDu8hKCoagSCOehkGqUTskg7LaOK2jsqgJEgER2j0pSNKGHSjLeMybJnHK2gAPyeIx0osTW2hkey7KSlxzEETWPLEeyADc5GUTKhESWgMnEfSyKot4DGYExck1mGAkgFy8qdsSWFQCM2p+DiNSROgKCdmUJlmVE9kyJZhjWfcnbQGZACaWGqiMURecYvplD6YYFDyD66KZwU+qFYZSpQTCGWsqW1kF4yZha-zoMZMJlFiUQ4Ih4jITIsiekgKQji26CAsCLk0FZUQoCUKLIagsJjJ2cKpMuu76n5OEBblur4kml5JLIKRpMciw-FqTkFgV4J0eIcDmPUlXVROtVyG2DWjs1647r1ZCdFm2G4egWQ5MhGwFLW4g0NUaBdXAMgAF4Emwb2KN1pyLV0NDfcthXoGtG2EuV20aM2batj4h2ue5sw9fC53NMUADMABscy1t9oR-d1tZIMSmWXTF4LOSAKJNaVUTGIiZUgCEdIAMrU1EeVs8o1nvTCL2BBcYSMxOV0jcscC4vSt1YAQhSGTDXoaIiIwQB9ICbi46poOr6pa4BUwG5rKbkwAosS+Li3cCApFbNsdXcahBBmpta59KTyMZxw-BlPN+PT3Ydf4bDYJ6fjs9ZHtC5g5ZnH4Os1JodE4VEyh3UnSC65oqTliaADsdzJ4Y2xIJrkO5nSsiVDIpcAPKkIom4Gp1-2e97JIPKcAfoLTwfi9rcAs1H-P6xrWtqPHTrZ7rTcEq3JNT8LovhB1oCS+O0uy-LmCKxFO5exE3d+98QA) (There were also some errors in the example spec that I removed: a fill encoding not housed in an enter/update block, a lingering VL type property, etc.)
