### ISSUE TITLE
CSS grid: containerSize() returns incorrect value

### ISSUE THREAD

**Issue by nbjgi1** [vega/vega#2789]
I am using signals in this fashion to resize a chart to fill an entire cell within a 2-column CSS grid. 

`signals: [
        {
          name: 'width',
          init: 'isFinite(containerSize()[0]) ? containerSize()[0] : 200',
          on: [
            {
              update: 'isFinite(containerSize()[0]) ? containerSize()[0] : 200',
              events: 'window:resize'
            }
          ]
        },
        {
          name: 'height',
          init: 'isFinite(containerSize()[1]) ? containerSize()[1] : 200',
          on: [
            {
              update: 'isFinite(containerSize()[1]) ? containerSize()[1] : 200',
              events: 'window:resize'
            }
          ]
        }
      ]`

At initialization, the chart fills the cell as expected. As the window gets resized larger, the chart follows and keeps filling the cell. So far, so good. The issue arises when I resize the window smaller. Instead of shrinking, the chart grows and overflows the cell, and disrupts the "1fr 1fr" horizontal ruling on my CSS grid. I have no idea what is going on. I have tried quite a few combinations of CSS hacks to no success. I am having a hard time debugging Vega as I am using Angular on top of that, but I can only suggest that containerSize() is not behaving well for CSS grids.

**Comment by domoritz** [comment]
What happens if you set overflow to hidden?

**Comment by nbjgi1** [comment]
Not much. It seems I have issues as soon as I use % or 'fr' in my CSS grid sizings. If I instruct fixed values in px, no problems, but that limits the use-cases for CSS grids heavily.

**Comment by domoritz** [comment]
I suspect this is a problem with CSS, not Vega. Can you provide a minimal working example?

**Comment by jheer** [comment]
The Vega [`containerSize`](https://github.com/vega/vega/blob/master/packages/vega-functions/src/functions/window.js#L19) implementation is very simple: it reads the container element's `clientWidth` and `clientHeight` properties. To debug on your end you can use the browser debugging tools to check those values and see if they are being set appropriately (via CSS or whatever other layout mechanism you might use). I expect the issue lies outside of Vega and am closing this out, but I will re-open the issue if there is a minimal example that reveals a Vega bug.
