### ISSUE TITLE
How much data transformation is vega expected to handle?

### ISSUE THREAD

**Issue by timelyportfolio** [vega/vega#29]
Most of the issues that I have submitted all deal with data transformation. Before I submit more, I want to make sure I have a sense of how much data transformation or complex calculation should we expect to happen within vega.  In some ways it seems the design and intent of vega inherently limit this ability.  By that I mean, when I work with ggplot2, I do not expect ggplot2 to do much data work.  Rather, I hand it a transformed data object ready for graphical rendering.  I wonder if extensive or difficult calculations should occur outside of vega and then passed to vega in the parse function.  I am very comfortable performing these through R or javascript, but after vega was released I thought I would explore how I might replicate these inside of vega.

For instance, in this [bl.ocks extension of barley](https://gist.github.com/timelyportfolio/5351448), I wanted to compare yield, yield - site average, and yield - total average.  Nothing complicated but maybe outside of scope.  Does trying to squeeze all this functionality into vega impair the ability to make it simple?

As another example that I have so far been unable to accomplish within vega, what if we want to draw a cumulative growth line chart of the stocks example like what I did [here in d3](http://timelyportfolio.blogspot.com/2013/03/building-ractives-is-so-addictive-it.html).  This would require the ability to access the price on the first date for each stock.  I tried multiple failed methods, but this got me closest.  

```
"data": [
    {
      "name": "stocks",
      "url": "data/stocks.csv",
      "format": {"type": "csv", "parse": {"price": "number"}}
    },
    {
        "name" : "first",
        "source" : "stocks",
        "transform": [ 
            { "type" : "filter","test" : "d.data.date === data[0].data.date;" }
        ]
    }
```

I really like the [clickme ractive](https://github.com/clickme) integration with vega which allows for R parse, transform, and calculate of data that we can just drop into the vega spec.  This feels very intuitive but with this approach we lose the ability to dynamically change the data within the browser, which is one of d3's biggest talents.

I really want to make sure that I'm not a distraction.  Thanks so much for all the great work you have done.

**Comment by sanand0** [comment]
@jheer and @arvind -- a few questions on extending Vega's data transforms in Vega 2.0.

How would we extend the data transforms? Do we set `vg.transforms.new_transform` in a manner compatible with the other transforms?

This feels like monkey-patching. Is this the recommended approach? Or should we modify the source? Or is there a plugin mechanism that is planned or recommended?

**Comment by arvind** [comment]
Hi @sanand0,

Indeed, if you follow the construction of the other transforms and add your new transform to `vg.transforms`, you should be able to instantiate it within the specification... I realize now that we do not expose the `Transform` superclass as part of the Vega API, so this may be a little tricky currently. I'll go ahead and fix this for a subsequent patch release of Vega. 

We have talked about a more robust plugin mechanism but that's at least a few minor releases away. If such a feature is of interest to you, I'd recommend starting a discussion on the [vega-js google group](http://groups.google.com/forum/#!forum/vega-js) so that we can begin to spec it out (and perhaps someone might even step up to track a first crack at it!).
