### ISSUE TITLE
Incoherent behavior of the area mark: x2 undefined works. y2 undefined doesn't.

### ISSUE THREAD

**Issue by jonasoesch** [vega/vega#3088]
I was trying to create a vertically oriented streamgraph and was stumbling over this odd behavior. I would expect the behavior to be the same for the `x2` and the `y2`-channel. Or is there a reason it isn't?

Three examples to illustrate what I mean:

Chart works with `x2` and `y2` defined. [Example](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtSRXCTbYJzNrgAPJAhwAbOJWkgA7jVn00AgAz+MvA0ZFh+gTKySJgoqADaoOIOcGggsUwu7sRITgwKaIkgDGgAjDLEaABMABwAvlKgJahVFX4CDU1oAMxtqAAs3Z3FaP19AJylw80CfTVTjSOoAGx9AkOLzQDsfaXj02g1c1sHqONrVaelQSCVA-WbZeW31f1XrS8D+4+opb2fNROP1KY0+y2WV1mn1KQK6v1WnyqsKWML6ywecNKR2hEOB50+-W+cKqNzupQ6AF06hSZNBcgUEkkUmliHSsjJMABPHCpdBOGjiMyKdyKJDiMi8zzeXxRNjIAVoUDRWJpDLskAAMxocCcshZIDqw2SCElDDZqQ53Ml-MFJhFYolaRCYUw7lkcqQCtQSpicXSSEyFs12t1aRKhppIGQigA1hBCqAuTy0iYzO4NYo5Yq5L7VQGsg0QHBxFA2PJs8XMHBhd6QJyqtmtTq9egSrSoPSw+aDTJOdmcnleTdu63u4XbI2Qy2Xu3O+hWR2CzJbA3awP8mhh4vJQvO4aI3UgA)

Chart doesn't work with `x2` defined but `y2` not defined. [Example](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtSRXCTbYJzNrgAPJAhwAbOJWkgA7jVn00AgAz+MvA0ZFh+gTKySJgoqADaoOIOcGggsUwu7sRITgwKaIkgDGgAjDLEaABMABwAvlKgJahVFX4CDU1oAMxtqAAs3Z3FaP19AJylw80CfTVTjSOoAGx9AkOLzQDsfaXj02g1c1sHqONrVaelQSCVA-WbZeW31f1XrS8D+4+opb2fNROP1KY0+y2WV1mn1KQK6v1WnyqsKWML6ywecNKR2hEOB50+-W+cKqNzupQ6AF06hSZNBcgUEkkUmliHSsjJMABPHCpdBOGjiMyKdyKJDiMi8zzeXxRNjIAVoUDRWJpDLskAAMxocCcshZIDqw2SCElDDZqQ53Ml-MFJhFYolaRCYUw7lkcqQCtQSpicXSSEyFs12t1aRKhppIGQigA1hBCqAuTy0iYzO4NYo5Yq5L7VQGsg0QHBxFA2PJs8XMHBhd6QJzs1qdXr0CVaVB6WHzQaZLYGyHmy82x30Kz2wWe1Vszk8rybl2R13DRG6kA).

But the chart does work with `y2` defined but `x2` not defined. [Example](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtSRXCTbYJzNrgAPJAhwAbOJWkgA7jVn00AgAz+MvA0ZFh+gTKySJgoqADaoOIOcGggsUwu7sRITgwKaIkgDGgAjDLEaABMABwAvlKgJahVFX4CDU1oAMxtqAAs3Z3FaP19AJylw80CfTVTjSOoAGx9AkOLzQDsfaXj02g1c1sHqONrVaelQSCVA-WbZeW31f1XrS8D+4+opb2fNROP1KY0+y2WV1mn1KQK6v1WnyqsKWML6ywecNKR2hEOB50+-W+cKqNzupQ6AF06hSZNBcgUEkkUmliHSsjJMABPHCpdBOGjiMyKdyKJDiMi8zzeXxRNjIAVoUDRWJpDLskAAMxocCcshZIDqw2SCElDDZqQ53Ml-MFJhFYolaRCYUw7lkcqQCtQSpicXSSEyFs12t1aRKhppIGQigA1hBCqAuTy0iYzO4NYo5Yq5L7VQGsg0QHBxFA2PJs8XMHBhd6QLZs1qdXr0CVaVB6WHzQaZJyqg2Q82Xm2O+hWe2Cz3szk8rybl3R13DRG6kA).

**Comment by jheer** [comment]
Did you try setting the desired `Orient` property alongside the position properties? (See https://vega.github.io/vega/docs/marks/area/ for more)

Thanks!

**Comment by jheer** [comment]
I had more time (and on desktop rather than phone), so I took a deeper look at the linked examples. The solution is indeed to use the `orient` property to indicate if the area has a horizontal or vertical orientation.

Here is an updated [example 2](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtSRXCTbYJzNrgAPJAhwAbOJWkgA7jVn00AgAz+MvA0ZFh+gTKySJgoqADaoOIOcGggsUwu7sRITgwKaIkgDGgAjDLEaABMABwAvlKgJahVFX4CDU1oAMxtqAAs3Z3FaP19AJylw80CfTVTjSOoAGx9AkOLzQDsfaXj02g1c1sHqONrVaelQSCVA-WbZeW31f1XrS8D+4+opb2fNROP1KY0+y2WV1mn1KQK6v1WnyqsKWML6ywecNKR2hEOB50+-W+cKqNzupQ6AF06hSZNBcgUEkkUmliHSsjJMABPHCpdBOGjiMyKdyKJDiMi8zzeXxRNjIAVoUDRWJpDLskAAMxocCcshZIDqw2SCElDDZqQ53Ml-MFJhFYolaRCYUw7lkcqQCtQSpicXSSEyFs12t1aRKhppIGQigA1hBCqAuTy0iYzO4NYo5Yq5L7VQGsg0QHBxFA2PJs8XMHBhd6QGxlJXszk8pKYPWaAAvCSxJwGmSc7NanV69AlWlQelh819kC2QchkcvceT9CsicFmS2KpN3L5NA3aer6eGiN1IA).

**Comment by jonasoesch** [comment]
That was it, indeed. Thank you very much for the quick reply!
