### ISSUE TITLE
Error with i8n in wordcloud

### ISSUE THREAD

**Issue by eeyshen** [vega/vega#3099]
I found Wordcloud failed with non english string,  such as
```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A word cloud visualization depicting Vega research paper abstracts.",
  "width": 800,
  "height": 400,
  "padding": 0,

  "data": [
    {
      "name": "table",
      "values": [
        "übergeordnete"
      ],
      "transform": [
        {
          "type": "countpattern",
          "field": "data",
          "pattern": "[\\w']{3,}",
          "stopwords": "(i|me|my|myself|we|us|our|ours|ourselves|you|your|yours|yourself|yourselves|he|him|his|himself|she|her|hers|herself|it|its|itself|they|them|their|theirs|themselves|what|which|who|whom|whose|this|that|these|those|am|is|are|was|were|be|been|being|have|has|had|having|do|does|did|doing|will|would|should|can|could|ought|i'm|you're|he's|she's|it's|we're|they're|i've|you've|we've|they've|i'd|you'd|he'd|she'd|we'd|they'd|i'll|you'll|he'll|she'll|we'll|they'll|isn't|aren't|wasn't|weren't|hasn't|haven't|hadn't|doesn't|don't|didn't|won't|wouldn't|shan't|shouldn't|can't|cannot|couldn't|mustn't|let's|that's|who's|what's|here's|there's|when's|where's|why's|how's|a|an|the|and|but|if|or|because|as|until|while|of|at|by|for|with|about|against|between|into|through|during|before|after|above|below|to|from|up|upon|down|in|out|on|off|over|under|again|further|then|once|here|there|when|where|why|how|all|any|both|each|few|more|most|other|some|such|no|nor|not|only|own|same|so|than|too|very|say|says|said|shall)"
        },
        {
          "type": "formula", "as": "angle",
          "expr": "[-45, 0, 45][~~(random() * 3)]"
        },
        {
          "type": "formula", "as": "weight",
          "expr": "if(datum.text=='VEGA', 600, 300)"
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "table", "field": "text"},
      "range": ["#d5a928", "#652c90", "#939597"]
    }
  ],

  "marks": [
    {
      "type": "text",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "text": {"field": "text"},
          "align": {"value": "center"},
          "baseline": {"value": "alphabetic"},
          "fill": {"scale": "color", "field": "text"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      },
      "transform": [
        {
          "type": "wordcloud",
          "size": [800, 400],
          "text": {"field": "text"},
          "rotate": {"field": "datum.angle"},
          "font": "Helvetica Neue, Arial",
          "fontSize": {"field": "datum.count"},
          "fontWeight": {"field": "datum.weight"},
          "fontSizeRange": [12, 56],
          "padding": 2
        }
      ]
    }
  ]
}
```
The result is

<img width="561" alt="截屏2021-02-26 下午9 43 03" src="https://user-images.githubusercontent.com/31716017/109307448-a33e1f00-787b-11eb-9bf0-718d1994b509.png">

**Comment by jheer** [comment]
The issue is not with the `wordcloud` transform itself, but rather with the `countpattern` transform. That transform uses a default matching regexp of [`[\\w\']+`](https://github.com/vega/vega/blob/master/packages/vega-transforms/src/CountPattern.js#L74) which leaves it subject to how JavaScript regular expressions interpret the "word" character class. This class [excludes a number of other unicode ranges](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes): "Matches any alphanumeric character from the _basic Latin alphabet_, including the underscore".

The solution is to use a custom `pattern` parameter for the `countpattern` transform. For example to match all non-whitespace text, use `[\\S]+`, as in [this example](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAEAdzaLZ2qABs2DI8RoQGSEzQBeSNRO3ycNKGvFltANT5tRQU4JEVYbRwkHDhFbSQmCExFJC8ISmkQXRpZejQADgAGQpl4GjIsNAAWYpko2VkaHzQSuWcUVABtUHEkBDg0EEwEkwGZYjsGBTROkAAfpliyOANZcThMAYBdGWSkcQgAMwMEGdBMAE8YwahzcVxnTcVJGUOaOBNZQdl2zKjsWIaECdAA6IIAygByLbAADMUgAvpkkmwcPpDBBBgAKGgAH36+IuhIgH0OuN0cFxDAguPMilpDEUNLpJJMpBpF3MuM5jO5LL5jNZZJ5TI+7Nx8AlNAQUppMGlQtxEEl8HpqrlsUVdFxdBputJuPocCJRplRpo9PNTMN3FZ4t0MGc5PlsGdbDdModbBJNusNqdRp99G9lL6OppYUpuiQNIpwVxiwTcDg4iTTTIEqQpEzcqQskzVh8uNk7pLCmLOWLbHT5JoJhM5PMnyVMCb+ag+1xtwYzfMFUwOshMp5kPj8EhNOVcAnOswM4po8pRoui8H2ZH2YX2eXkOzNEh+ZH+fH+anB-J0-zO-z+-rAshd-Hd7Pd4Xd53d+s4khA8j34H0YQP+F7BMBjpAT+BYppBjprJBZYQQOJbAY0cEARIkH6D2aEtvskHKm2wEdkR+ziGwA7dp8wEINSmDAaMc40vQzjzq2rEsRqwQzkaXGxvA358bE058SucpsLoM5ILinZGtJ4j5kwDADjQZIGEmHbUqGNIMPcdbOnWlJsGSTpMESxz0tk9DSUw5i-hQTRJEmmAUimOr3O69CKH2MDFoyNaLOZoaHE81lsNmixmLohruocXkygwOBUjgEhVroqZNAyA4pUZqmkPSOnyPSSD2amhyMjxNquRIUCUqqS51c6rkOkJzpEq2UV2A2+xEjZVmhK6hxwFFCAGJSI2OeRqpKmwBI2K6ZG4mR9JkVl4gmES4mphAfSUmI-qppgbDunlRLbadSAXJOSCVsqnUAJQgAiUjnFcAzoOZNEmCgMgxoM+xkKMmRwAAHjgiiDJ0AC0VQCFI2glNoMNbJ0AB+KNYik8kzVid3aAAVNosJ3Vsj3PUMr2DB9PbfSAv3oBS5SVDIINg4MKlYj8mAMAglCbMDmAALwC5CfgAKIAOKaJCcMAGy1ITxQPQiWzKzI0B2NMXQ9DtNxsGY4O7BT6CrE0diZCWyBNGgoCcx0QwjGMIBvB8XzoHzmCkyAmPLDMIAAMSyAISAAJwAEz5JkfsywIodQMHhSR8HsLBwIwcAOwgCrOwgMgigANaYlr5PXG7IMe68cXW20wyDMMTCA09IAprc8hVymTxV+7VfO58tdl57djlBooATCYUw3O3sSe0wMYfE0b0j5Mb20yYOCOosahQJ7bz1lX6uA+gtz65kPeu0M-cIo3CWcwvTt1iYADyURQHQFxV6P4+oAAjJfpRhVPqBQA70fs-V+78l4tEoAIS+jc9gHA+mcYuy90SyFMOYL4atHBvU6EUEoNRCjZy7oAu+Ls+7809l5YYmxu7vF7ugTm3NKD-Qbq8CQHt0AAAkxQbE8EgbQAA5OAUw4aaGUGbVh9xwRYJoaQ+hzhGHdnuNvNhAB1OAjN2FANoWfBhPMGb9mUZIrBAAlf62Cv6hykAIGW2d6iNGaKgUOytnFAA).

**Comment by eeyshen** [comment]
Thank you very much.
