### ISSUE TITLE
Floating point issues with large enough bin thresholds

### ISSUE THREAD

**Issue by mattdeitke** [vega/vega#3151]
Bin ticks are occasionally formatted with floating point issues by default. Empirically, it appears to be an issue only when using many bins. Ideally, the vertical bin ticks would be formatted here to something cleaner automatically, like `".1f"` in this case.

[Open in a Vega Editor](https://vega.github.io/editor/?#/url/vega-lite/N4IgLgTghgdgzgMwPYQLYgFwG1QCMCWMmoqUAHgfJgCwCsAvgDQgL4CmANgCaYj4jMwATwAObXgEUBIKHF6UYbLgAJ+TPIWIhSFQnIzUADExbtu86cLGTps+YUUrcIegF1mAd3xcwACxqGhsykEADWWlbiGCC4UBCWSEgcYPgimJAArmwmbDAAxkhchADmWmRarJw80QpKqpaiUSAA8i7MQhVm1TEOdc6CjbytJgUcKFpQxcUQbMVQYE0FGTBgLiZc81BaGRAcvL5gYCJwGAD0p8X4cGAAdJd+GbgZcGwQBSu5twWop6SHXGx8GBQmxTgA2ADMAHZaBDqABOKDQ2iGKC4BAQiEARloAA4AExgvK4qAIfG4sFQLi0U7QDynai4XHwth5eHwsFYiG0MFsNhg6hcTm4rhYzn4-FKWhcXF5MEIeG4Qk0gBusygAFonsUNRswJr3qxijc8nAVWsgA).

![image](https://user-images.githubusercontent.com/28768645/113496170-d6438600-94ab-11eb-9522-24b02d324a92.png)

Perhaps related to https://github.com/vega/vega/issues/1395, although the issue still persists.

**Comment by jheer** [comment]
Looks like this is due to use of an ordinal scale, which does not provide automatic formatting. The “standard” way in Vega(-Lite) of plotting binned quantitative fields along an axis is to use a continuous (eg linear) scale and plot both x/x2 or y/y2 for the binned interval. Using a continuous axis will invoke logic to calculate the numeric precision and format the labels accordingly - and also ensures any gaps (empty bins) stay visible. For an ordinal or nominal axis (for which the input could be an arbitrary data type) you currently need to specify the desired axis format (such as “.1f”).

In Vega-Lite the use of continuous scales is invoked automatically when using the bin transform as part of a visual encoding specification. However in this case the binning is being performed earlier via explicit transforms and an ordinal axis is explicitly specified. There may be some Vega-Lite docs or examples about using pre-binned data? (cc @domoritz)

**Comment by jheer** [comment]
p.s. @domoritz, VL doesn’t need to see the data here in order to know that the inputs are binned quantities. In this case that info is in the spec transformation lineage.

**Comment by jheer** [comment]
Also, here is an [alternative example](https://vega.github.io/editor/?#/url/vega-lite/N4IgLgTghgdgzgMwPYQLYgFwG1QCMCWMmoqUAHgfJgCwCsAvgDQgL4CmANgCaYj4jMocTFhAEAjALH4ATCAC6TPIWIhSFQsIzUADExbtuvXFKEixuSc1y45i+cwDu+LmAAWNHTuZu2+AOZuYJ7ealAQANaqYACeAA5sxuFSYEhIHGD4cZiQAK5s+mwwAMZIXIT+qmSqrJw8GNJW4PGJDQCKKfhgHK3SMDBsXAAE-PpkchigtUYNBHLMsQm8HfoxNYb1Fk2LvR0LXT3GhAPDJqsTUxvGtiktyyD6pRwoqlD+-hBs-lBgvaW5MGC9H0XB+UFUuQgHF4QTAcTgGAA9Ij-Pg4GAAHSo9y5XC5OBsCClQFFTGlVCI0hgMBcPxgCJsREANgAzAB2Wgs6gATig7NoOiguAQLJZ4loAA4ZEzihKoAgZBKmVAuLREdBHIjqLgJdy2MVudymeIWbQmWw2EzqFxjRKuOJjTIZINaFwJcUmQhubYmWqAG5fKAAWjx-iDoLAweJrH8GOKcD9D3oQA) using quantitative scales for the binned intervals.
