### ISSUE TITLE
rename data 'transform' property to 'transforms' (plural)

### ISSUE THREAD

**Issue by espinielli** [vega/vega#329]
Morphing array property names to plural has already taken place from vega 1.x to 2.0, i.e. `<signal>.stream` is now `<signal>.streams`.
It could be meaningful to apply it consistently to all vega API and do it also for `<data>.transform`

(other missing? I haven't checked: sorry ;-)

**Comment by arvind** [comment]
Streams were not present in Vega 1.x. If you're referring to the code examples found in our UIST 2014 research paper, I would note that while those are certainly good reference material, we only offered a proof-of-concept system. So code snippets and provided supplementary materials should not be treated as canonical with respect to official Vega releases. 

While making `transform` plural would increase consistency in the language, such a change would break backwards compatibility for debatable advantages. Moreover, `transform` (signular) arguably makes more in this context as we mean it to be a verb, rather than a noun (unlike the other array definitions such as `streams`, `scales`, `marks`, etc.).
