### ISSUE TITLE
Transforms don't update on signal change

### ISSUE THREAD

**Issue by raystubbs** [vega/vega#3299]
Here's a working example: https://vega.github.io/editor/#/gist/da9c6924cdd94e6a4635e7bb23a355ff/spec.json.

The intent here is to allow toggling a category by clicking its legend.  But what seems to be happening is the `filter` transform gets updated (ig because it explicitly depends on the `hiddenSeries` signal?)  but the `stack` transform after it doesn't.  So when the `0` legend is clicked the `1` columns keep their old stack position instead of dropping down.
![chrome_kBjG6SNEDs](https://user-images.githubusercontent.com/7083791/134406169-62353822-4c7d-413f-993f-7a7619cd9b8a.png)
![chrome_lWvrAqnPzX](https://user-images.githubusercontent.com/7083791/134406190-17710632-bf61-48f4-a8b7-60af63387b41.png)

**Comment by jheer** [comment]
Turns out the issue here is not with Vega's stack transform. The `rect` mark definition in the provided specification uses the `enter` set for all positional properties (`x`, `y`, `y1`, etc). As a result, the spec indicates that those properties should be set once and then left constant. If you move them to the `update` set your example should work as intended.

**Comment by raystubbs** [comment]
Ah, I see.  Thanks for catching that.
