### ISSUE TITLE
Nest Transform Returning undefined

### ISSUE THREAD

**Issue by PBI-David** [vega/vega#3406]
I'm trying to use the nest transform to feed into a tree transform and using the data and documentation here: https://vega.github.io/vega/docs/transforms/nest/

The problem is the transform seems to return the first 8 rows fine but the remaining 7 rows are all undefined which then cause downstream problems for encoding a label. See below.

![04-02-2022 20-16-59](https://user-images.githubusercontent.com/86846675/152598097-a6379feb-6d5b-4f8e-b302-d46a2b95883e.jpg)

Using this data, if I use id for the labels, I only get the 8 corrects ones as below.

[Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQXEACOAA8kCHABs4OtgDMdAYSSLMCmkl0mkATzYNMEHZbaKOkg64mzyALQmNOIA1jqyzmSKRhbWMDRwyYqwNFBIJvFImFTSIADuNLL0aABsAAx1MvA0ZFhoAMwNMjhIsgniZGgCMrJFKKgA2qDiRnBoIJiKcHMyxPkMCmhTIJXzmqXCbEzzACJsUJgBpUu0EvMAokgQmCAAvlKgu+gAQgdHp+dLopruR1A8ni93p9ZPMbH9jugADJIMruTIg24aECPZ5vD47GHoE7w+bI1HomQ3MHoHGQ-FfbEkomAq6U0F3dAAdQUdOh8wAYkyQGcLqyQFSOSBubioQT5gBxIVktHAtmY+bS3ly9AACSVKJVGOpUp5bwAujJFi4IP5FAgtqBMO4cHN0OJTTIYnB3BAtiBDsc1WCLSAyHB3clHGhFhtZU6XfNFstSgg4PQwonKu5ShAaAAvV0TTqNep1EMQOA9SPUmNwGRPP3ZmT6UryVQwUo5EyyJaSM2vfv4map+ZRWK+mRiBjZV0LJYrOfW232yaO52zpNwMcxX1x9ej6IxHrVGQBDLiF7oGBnvMSYomHMwJAJ9ABdNkCT5c0Dyd5My+1cQGHWcoDYEwxXjWcAn6L9KRcMM-SWGEZCYEwNlKJJlkkU9kgGOYQ1kNhkGiNBQFGYpE3nUpLAybt5gDN4fxAZBFB3B0Fn3dBjw7GRLEUIjSLkMYD3HPEQHDUD5EEhgcHI11QG4wSaK3QkQEU94QGefivUEtY0NnABiKBjMY149xfTT3AQJgwOo-iVzI4T0E3MSJLCeTxIvdFUFAXMC109ZXQARgaDStLYHSfJAPT0PQAzLASxiZBkuTBJbKLlLo9AWw07MMto1Tsw0miTAfKLoHyECwLFTLVIYsyzPxSDEwMF5ePswTyPGOdkw0typKi8NHGBKLHH0S9QFq+ZdmKu8AGV8w8mLXQATg0pgni3aIlsC+YEEqWQzCSkAUqKDz0smgr5hymQ8sulT5iKkYLs0loZjKoTMAYBBKC7Htwx0AB+HRwgAdh0VAdFBsT8jewTczId75nI77fvSbteyBnQAHJlFaTBsYhnGzEsAnTIHV4gA)

![04-02-2022 20-19-00](https://user-images.githubusercontent.com/86846675/152598093-bed89574-b443-493c-af0a-88c497df1ef3.jpg)

If I use key instead for the labels, I get the 7 labels below. 

[Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQXEACOAA8kCHABs4OtgDMdAYSSLMCmkl0mkATzYNMEHZbaKOkg64mzyALQmNOIA1jqyzmSKRhbWMDRwyYqwNFBIJvFImFTSIADuNLL0aABsAAx1MvA0ZFhoAMwNMjhIsgniZGgCMrJFKKgA2qDiRnBoIJiKcHMyxPkMCmhTIJXzmqXCbEzzACJsUJgBpUu0EvMAokgQmCAAvlKgu+gAQgdHp+dLopruR1A8ni93p9ZPMbH9jugADJIMruTIg24aECPZ5vD47GHoE7w+bI1HomQ3MHoHGQ-FfbEkomAq6U0F3dAAdQUdOh8wAYkyQGcLqyQFSOSBubioQT5gBxIVktHAtmY+bS3ly9AACSVKJVGOpUp5bwAujJFi4IP5FAgtqBMO4cHN0OJTTIYnB3BAtiBDsc1WCLSAyHB3clHGhFhtZU6XfNFstSgg4PQwonKu5ShAaAAvV0TTqNep1EMQOA9SPUmNwGRPP3ZmT6UryVQwUo5EyyJaSM2vfv4map+ZRWK+mRiBjZV0LJYrOfW232yaO52zpNwMcxX1x9ej6IxHrVGQBDLiF7oGBnvMSYomHMwJAJ9ABdNkCT5c0Dyd5My+1cQGHWcoDYEwxXjWcAn6L9KRcMM-SWGEZCYEwNlKJJlkkU9kgGOYQ1kNhkGiNBQFGYpE3nUpLAybt5gDN4fxAZBFB3B0Fn3dBjw7GRLEUIjSLkMYD3HPEQHDUD5EEhgcHI11QG4wSaK3QkQEU94QGefivUEtY0NnABiKBjMY149xfTT3AQJgwOo-iVzI4T0E3MSJLCeTxIvdFUFAXMC109ZXQARgaDStLYHSfJAPT0PQAzLASxiZBkuTBJbKLlLo9AWw07MMto1Tsw0miTAfKLoHyECwLFTLVIYsyzPxSDEwMF5ePswTyPGOdkw0typKi8NHGBKLHH0S9QFq+YvSK3i7wAZXzDyYtdABODSmCeLdomWwL5gQSpZDMJKQBSooPPSyaCvmHKZDyq6VPmWa5EuzSWhmMqhMwBgEEoLse3DHQAH4dHCAB2HRUB0MGxPyd7BNzMgPvmcifr+9Ju17YGdAAcmUVpMBxyHcbMSxCdMgdXiAA)

![04-02-2022 20-19-31](https://user-images.githubusercontent.com/86846675/152598095-142ecb8c-6619-4da3-83e9-2d663ef73902.jpg)

This obviously causes issues with the color encoding too which as you can see is not working. 

Is nest supposed to work like this or is it a bug? Is there some documentation or example I can refer to better understand what is going on and fix the undefined rows?

**Comment by jheer** [comment]
Thanks, though technically I don't think this is a bug. The `nest` transform generates new internal nodes and, as the documentation warns, these nodes do not in general have the same properties as the original leaf nodes. It is up to you to handle this as you see fit.

For example, one option is to add a transform that sets desired properties or use signal expressions in your visual encodings so that you pull from the desired attributes across the different node types (internal vs. leaf).

Here is a [revised Vega editor example](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQXEACOAA8kCHABs4OtgDMdAYSSLMCmkl0mkATzYNMEHZbaKOkg64mzyALQmNOIA1jqyzmSKRhbWMDRwyYqwNFBIJvFImFTSIADuNLL0aABsAAx1MvA0ZFhoAMwNMjhIsgniZGgCMrJFKKgA2qDiRnBoIJiKcHMyxPkMCmhTIJXzmqXCbEzzACJsUJgBpUu0EvMAokgQmCAAvlKgu+gAQgdHp+dLopruR1A8ni93p9ZPMbH9jugADJIMruTIg24aECPZ5vD47GHoE7w+bI1HomQ3MHoHGQ-FfbEkomAq6U0F3dAAdQUdOh8wAYkyQGcLqyQFSOSBubioQT5gBxIVktHAtmY+bS3ly9AACSVKJVGOpUp5bwAujJFi4IP5FAgtqBMO4cHN0OJTTIYnB3BAtiBDsc1WCLSAyHB3clHGhFhtZU6XfNFstSgg4PQwonKu5ShAaAAvV0TTqNep1EMQOA9SPUmNwGRPP3ZmT6UryVQwUo5EyyJaSM1x52ukC2hAMNylAw4YHoUaYBgIShe9w6AA+K8Kc4XlVX64A5LvSg30G4mHATObZTNU-MorFfTIxAxskOkysFslxDaAvbJo7B4mljPaIYl9AcE2PYCemqGQAgycQXnQGBYLzCRinPB8YCQcCQACdMyAkfIL3LPIzF9X8QCvIcoDYEwxXjIcAn6QjKRcMM-SWGEZCYEwNlKJJlkkGCPzYkNZDYZBojQUBZ3Gd9kxkSwMm7eYAzeV4Q2QRQQIdBZ-3QKCOwUxRxKkuQxhvYDQJkcNqPkUyGBwWdXVAAzTMUs9CRAVz3hAZ5jK9Uy1h4ocAGIoHCtTXjAocIHcBAmBo0pLGMn9pPM9BXzxEAbLCZzsvg9FUFAXMC0C9ZXQARgaHy-LYAKipAILePQELLDatSZAcpzTJbBr3OU9AWx87M+qUzzsx8xSTHPBroHyKiaLFfrPNUqKovxejEwMF4jJMhqZIA5MfJyuyGvDRxp0dba3LGm8kFPc9JtQgBlfM8qa10AE4fKYJ4gPdMrgvmBBKlkMwOpALqijy3rQGW+YhpkEa4du9AJpGWHfJaGYZrMzdKC7Htwx0AB+HRwgAdh0VAdAprL8mx0zczIHH5lnecCfSbte1JnRd2UVpMF3am+bMSwhci9TXiAA) that uses a `formula` transform to create a standardized label property.

```json
{
  "type": "formula",
  "expr": "datum.key || datum.id || ''",
  "as": "label"
}
```
