### ISSUE TITLE
Support Background Color in Text Marks

### ISSUE THREAD

**Issue by PBI-David** [vega/vega#3418]
To aid readability, I was wondering if it would be possible to add a background to text marks. Picture attached to illustrate. 

![03-02-2022 15-28-05](https://user-images.githubusercontent.com/86846675/152373647-2e376aba-7810-40e4-a4c3-6071eed06b47.jpg)

**Comment by PBI-David** [comment]
If anyone looks at implementing this, please also add options for padding as this will come in really useful for doing annotations like the ones found here: https://d3-annotation.susielu.com/

**Comment by jheer** [comment]
At the moment I do not have any plans to add special features for text backgrounds. However, this can already be done in Vega (though admittedly with a bit more overhead than one might like) by using two marks:

- First create a text mark as usual.
- Then create a rect mark that uses the text mark as its backing data (aka [reactive geometry](https://vega.github.io/vega/docs/marks/#reactive-geometry)). The rect mark properties could be configured with reference to the text mark "bounds" property (though note this will break for rotated text).
- Set the rendering order so that the text is drawn on top of the rect marks.

Here is an [example in the editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtZRWwY44s3UkXbYNzNrgAPJAhwAbOJWkgA7jSy9GgAzAAMYTLwNGRYaABMACyRIDhIsrI04mRoAjKySJgoqADaoOJucGggRUxevsRIHgwKaGUgUIXkbIoAntWavjhsBmoSaCmNzVWoYZQAjAC+UqCdmN19A0MjdOpo8zJTLROUAGzLq11kPf1a26N7qPGHTcezlACcFx1XN1sywwe41QIRe0xOiW+aw2txAACF7rtgZNXjM5gB2KG-TboBEAnZjDQHEBHNGUeJY9bXHHwxGEhJgt7zBaUmHVPGpAmPUEk1EnAAcrOpsIAwnTHijwe9zisflS-ugxfigUTGWSlrLocLqkrOSqGbypXMKZrsaLxcCeaSTpiALqLW0yaBNVqlcqVaq9Z31GSYXoWap6cSyXyyNjILJoUAFIrVWo+kAAMxocA8IfQWr+yxAiiQ2RmGDgMTiAPSmWyJxN7oQBec3qqvv9BY8WTgNlD4aQkdQ0cKxRqSDqDaTKbT1Wt2dz+eqASCMF8pgYwbQmEULRkAC84KYV2u4DJxIYZquWt8KjXqlA2B4er4-QH0D1y00OxGNL3Y+h48Pk6n03qkUkSc8zIGZQC4RAC0zPp4jCEBFgdGQkGcV12h6FNxEwaovETLCnU6ep0C9AjhzUKAAGsAGUaC3CYZA8QdUwABTLLIclQRJNyyeRnH2b50LgTDAzYbBw18etqjrEj4MdEBkEUciIDaUB7wLEwzBwXxE1MBAoyTJAoDgLCezkPs40HBNzwLRMDKM3x1PMJhYWg-oEJkQSr3kPTBPWRQ9NucDpKIiSZF-McMzNeC3JAAwyAqDwlLdEArOqaJYjwkBzBjAsg1kWd6AACgAcmIl0ioAShk-CXUS9oUvQQE7ybQM8xDGQp1A1Ki3S18u3fUzP30wyMrC-9AUAqLZPkxTlOSj10D0RQlNCnS9JjfsbOG+DGwfHM4CgDKPLYLyTJ87d-L0iSGpGLTRzGrlxmzNK4hMq69V8XK+JkXjXqCkApJdW6-3HPls2ceJLr+gGE2tWZs2TDwPEhwGM2vW9Qru6pxvpBC3OrZtGISprdvWZwRtWkz1papbtpADduJcfZ3PETywJAM6-JMn7QFGySIZkNhE0TCA7NQABaARswCkdgaI3xBeF0Wecx9BnoyhAGA8Yy5kl+GaERvTYZAOoDPI2mmhifqjeUHrsz0EWW3ENmjYQQJZHqbNSeM5XZYGhgEEoCdcdlVTqkUfbybEymzPQBimFTJTsyOk7QCyro9O5mXwuNsxgwgShnHmeWhZF4yxZNf6IZM3mFtz2R8-B4vFeMivpZrnOl3ryheiLgWS9F8uparn3s6YOv896fmQAV0uEj1g2TKNnAsjN3GHXXoA).

Vega-Lite could possibly consider adding support for this as a composite mark type.

**Comment by PBI-David** [comment]
Awesome

**Comment by legszesz** [comment]
Hi,
Thanks for the hint on how to set the background color for a text mark.
Is it possible somehow to change the background color based on a field's value?
For example in this [example](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtZRWwY44s3UkXbYNzNrgAPJAhwAbOJWkgA7jSy9GgAzAAMYTLwNGRYaABMACyRIDhIsrI04mRoAjKySJgoqADaoOJucGggRUxevsRIHgwKaGUgUIXkbIoAntWavjhsBmoSaCmNzVWoYZQAjAC+UqCdmN19A0MjdOpo8zJTLROUAGzLq11kPf1a26N7qPGHTcezlACcFx1XN1sywwe41QIRe0xOiW+aw2txAACF7rtgZNXjM5gB2KG-TboBEAnZjDQHEBHNGUeJY9bXHHwxGEhJgt7zBaUmHVPGpAmPUEk1EnAAcrOpsIAwnTHijwe9zisflS-ugxfigUTGWSlrLocLqkrOSqGbypXMKZrsaLxcCeaSTpiALqLW0yaBNVqlcqVaq9Z31GSYXoWap6cSyXyyNjILJoUAFIrVWo+kAAMxocA8IfQWr+yxAiiQ2RmGDgMTiAPSmWyJxN7oQBec3qqvv9BY8WTgNlD4aQkdQ0cKxRqSDqDaTKbT1Wt2dz+eqASCMF8pgYwbQmEULRkAC84KYV2u4DJxIYZquWt8KjXqlA2B4er4-QH0D1y00OxGNL3Y+h48Pk6n03qkUkSc8zIGZQC4RAC0zPp4jCEBFgdGQkGcV12h6FNxEwaovETLCnU6ep0C9AjhzUKAAGsAGUaC3CYZA8QdUwABTLLIclQRJNyyeRnH2b50LgTDAzYbBw18etqjrEj4MdEBkEUciIDaUB7wLEwzBwXxE1MBAoyTJAoDgLCezkPs40HBNzwLRMDKM3x1PMJhYWg-oEJkQSr3kPTBPWRQ9NucDpKIiSZF-McMzNeC3JAAwyAqDwlLdEArOqaJYjwkBzBjAsg1kWd6AACgAcmIl0ioAShk-CXUS9oUvQQE7ybQM8xDGQp1A1Ki3S18u3fUzP30wyMrC-9AUAqLZPkxTlOSj10D0RQlNCnS9JjfsbOG+DGwfHM4CgDKPLYLyTJ87d-L0iSGpGLTRzGrlxmzNK4hMq69V8XK+JkXjXqCkApJdW6-3HPls2ceJLr+gGE2tWZs2TDwPEhwGM2vW9Qru6pxvpBC3OrZtGISprdvWZwRtWkz1papbtpADduJcfZ3PETywJAM6-JMn7QFGySIZkNhE0TCA7NQABaARswCkdgaI3xBeF0Wecx9BnoyhAGA8Yy5kl+GaERvTYZAOoDPI2mmhifqjeUHrsz0EWW3ENmjYQQJZHqbNSeM5XZYGhgEEoCdcdlVTqkUfbybEymzPQBimFTJTsyOk7QCyro9O5mXwuNsxgwgShnHmeWhZF4yxZNf6IZM3mFtz2R8-B4vFeMivpZrnOl3ryheiLgWS9F8uparn3s6YOv896fmQAV0uEj1g2TKNnAsjN3GHXXoA) give different colors for each Category: A-blue, B-green, C-yellow.
