### ISSUE TITLE
Vega v5.22.0 ERROR TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by roying** [vega/vega#3441]
Here is an[ example Vega spec](https://codepen.io/RoyIng/pen/GROOJPZ?editors=1010) that works with Vega v5.21.0:

![screenshot_vega_5_21_0](https://user-images.githubusercontent.com/37225856/158226441-0d397f92-711f-4eda-b5c2-dbf2a7e861e6.png)

With [Vega v5.22.0](https://github.com/vega/vega/releases), however, it throws an error: 
_ERROR TypeError: Cannot read properties of undefined (reading 'length')_

![screenshot_vega_5_22_0](https://user-images.githubusercontent.com/37225856/158226563-c0a5afed-e25e-4b50-9ce5-cd88142d97f4.png)

The issue appears to be related to this code where a scale is used to lookup a value for fieldname:

```
"scales": [
    {
      "name": "scale_lookup_aggregate_fieldname",
      "type": "ordinal",
      "domain": ["Number of tasks", "Average hours per task", "Total hours for all tasks"],
      "range": ["task_count", "task_hours_average", "task_hours_total"]
    },
    {
      "name": "scale_y",
      "type": "linear",
      "range": "height",
      "domain": {
        "data": "data_task_hours_aggregate_by_date_utc",
        "field": {
          "signal": "scale('scale_lookup_aggregate_fieldname', signal_aggregate_type)"
          }
      },
      "zero": true,
      "nice": true
    }
```

Could this be a bug in Vega v5.22.0?

**Comment by jheer** [comment]
It looks like the initial signal value is incorrect. It is array valued but I think it should be string valued. The spec works for me if I change the first signal to be like this:

```json
  "name": "signal_aggregate_type",
  "value": "Number of tasks",
```

(instead of `"value": ["Number of tasks"],`)

I'm not 100% sure why it worked in Vega 5.21 and breaks now, but I suspect it may have to do with upgrading d3-scale to the latest version. I don't believe 5.22 changes any other relevant bits of Vega functionality.
