### ISSUE TITLE
Can't draw a single point in a group using line mark

### ISSUE THREAD

**Issue by Shoutmon** [vega/vega#350]
If there is only one point in a group, I cannot draw it using line mark. As the following code, I can't draw the data of "year 2003" unless I use symbol mark (But I don't want to use symbol mark instead, because I don't want to show other points).
http://paste.ubuntu.com/12312155/

**Comment by jheer** [comment]
This is currently the expected behavior. In general, a line or area requires two or more points to be defined. I will interpret this issue as a feature request for line marks with one point to draw a single point (e.g., sized according to the line mark's strokeWidth).

**Comment by besquared** [comment]
+1

**Comment by jheer** [comment]
The issue is slightly more complicated than that. A couple points:
- If there is only one data point in total, that may affect your scale domain/range as well. That is a separate issue that drawing a different mark doesn't address.
- Vega 3 now supports the `defined` property for line and area marks, which was introduced in D3 v4. This features allows drawing of areas or lines in which some intermediate points are undefined, introducing "breaks" in the graph. If a solitary defined data point is surrounded by undefined points, nothing is drawn -- this is similar to how nothing is drawn when the entire data consists of a single point. If we make a change to support the single item case, we then have inconsistency with the "undefined-defined-undefined" case.

Rather than add potentially brittle or inconsistent patches to the Vega code, I think this is fundamentally a question of how the d3-shape library (not vega-scenegraph) should handle these cases. You might want to file an issue on that repo with a proposal for how isolated points should be handled; Vega will automatically benefit from any changes.

Otherwise, if this is a major issue in your designs, I recommend using a layered plot with symbols *and* lines/areas, ensuring singleton points (in any of the above configurations) remain visible.

**Comment by besquared** [comment]
Just a quick follow up on this for folks coming back to this later.

This appears to work on d3 v4 with the right line caps

From the d3-shapes README:

Note that if a line segment consists of only a single point, it may appear invisible unless rendered with rounded or square line caps. In addition, some curves such as curveCardinalOpen only render a visible segment if it contains multiple points.

Working example can be found here:

http://bl.ocks.org/besquared/9a964dc144f02c62c3b4f4580b70b4c6

**Comment by jheer** [comment]
Thanks @besquared!
