### ISSUE TITLE
support more categorical colors for scale

### ISSUE THREAD

**Issue by haiwen-shaw** [vega/vega#361]
can Vega support `category20b` and `category20c`  as  D3. thanks!

**Comment by arvind** [comment]
Done with 9018ef6. Will be included in the next version of Vega.

**Comment by jheer** [comment]
Keep in mind you can always add your own custom categorical color scales, too. For example: `{"type": "ordinal", "range": ["#ff0000", "#00ff00", "#0000ff"]}`.

**Comment by floribon** [comment]
Or it is possible to extend the config to support more palettes within a spec:

````
vg.config.range.categoryCustom = ['blue', 'white', 'red'];
````

**Comment by arvind** [comment]
@floribon, extending `config` with custom range types is indeed supported. With your example, scales could then specify `"range": "categoryCustom"`. Any valid key name is supported, of course!

You can also do so on a per-instance basis (rather than globally via the `vg` object) by passing a custom `config` object [to `vg.parse.spec`](https://github.com/vega/vega/wiki/Runtime).

**Comment by floribon** [comment]
Thanks for the per-instance tip, I was already using config customization to change the default ticks colors, font sizes, etc.

**Comment by haiwen-shaw** [comment]
Thanks for the tips! love Vega more!
