### ISSUE TITLE
'Multiple changeset pulses to same node' with cross after aggregate+lookup

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#368]
Dear Vega devs,

Here I am again with a crazy combination of data transforms that fails for a (to me) mysterious reason. Please find a minimal JSON below. Note that this particular code does not make much sense on its own; it is a stripped-down version of something much more complicated. In fact it took me a couple of hours to get from 150 lines down to this.

```json
{
  "data": [
    {
      "name": "raw",
      "values": [
        {"propertyname": "thevalue"}
      ]
    },
    {
      "name": "aggr_lookup",
      "source": "raw",
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["propertyname"],
          "summarize": {"*": "count"}
        },
        {
          "type": "lookup",
          "on": "raw",
          "onKey": "propertyname",
          "keys": ["propertyname"],
          "as": ["looked_up"]
        }
      ]
    },
    {
      "name": "cross_with_raw",
      "source": "aggr_lookup",
      "transform": [
        {
          "type": "cross",
          "with": "raw"
        }
      ]
    }
  ]
}
```

In Vega 2.2.3 and above, this gives me "Multiple changeset pulses to same node". It works fine in 2.2.1. The output should be:

```json
{
  "raw": [
    {
      "propertyname": "thevalue"
    }
  ],
  "aggr_lookup": [
    {
      "propertyname": "thevalue",
      "count": 1,
      "looked_up": {
        "propertyname": "thevalue"
      }
    }
  ],
  "cross_with_raw": [
    {
      "a": {
        "propertyname": "thevalue",
        "count": 1,
        "looked_up": {
          "propertyname": "thevalue"
        }
      },
      "b": {
        "propertyname": "thevalue"
      }
    }
  ]
}
```

Interestingly, the problem does not occur if the `cross` transform is moved over to the `transform` of the `aggr_lookup` data. (Funnily, when Vega went from 2.2.1 to 2.2.3 another crash was fixed, which occurred only if `aggregate` and `cross` were used in the _same_ data.) Also, this really is a minimal example: both the aggregate and the lookup seem to be required for the cross to break.

All of the signalling stuff that is going on inside Vega's guts is still mostly a black box to me, so I'm afraid at the moment I will not be able to get to the bottom of this myself. I hope you could look into this.

Kind regards,
Jerry

**Comment by arvind** [comment]
Hi @Jerrythafast, you're getting really good at uncovering interesting (aka buggy) configurations of the dataflow graph :) I've just deployed v2.2.6 of vega which fixes a bug in vega-dataflow that should resolve this issue. 

To summarize, when multiple nodes connect to the same downstream dependent, the dataflow graph attempts to resolve/merge the two individual pulses so that we only need to visit the dependent once. There are a number of checks to ensure this is done safely. The error message you were seeing was part of such a check -- there should be at most one pulse with tuples queued for a particular node, the remaining pulses coming down other branches of the graph should all be marked as `reflow` and should not contain any pulses. Of course, the situation we forgot to test is if, in fact, we continue to propagate a previous resolved/merged pulse. 

Nice catch, and thanks for filing the issue!

**Comment by Jerrythafast** [comment]
Hi @arvind, the primary reason I'm finding all these is that I am trying to set up my Vega specs such that Vega takes a raw tab-separated data file (which is in some cases not particularly well-formatted for visualising directly) and visualises that data without help of external tools.
