### ISSUE TITLE
Builder reuses outdated changesets

### ISSUE THREAD

**Issue by jheer** [vega/vega#387]
In trying to diagnose vega/vega-scenegraph#17, I discovered that the issue was not with the scenegraph code. Rather, an incomplete set of dirty items was being provided to the renderer. (This was not apparent in the canvas renderer because the damage bounding box was large enough to force a redraw of all affected items.)

Digging deeper, it seems that an inconsistent set of changesets are being (re)used, causing dirty items to collect in different arrays with some ultimately being lost (and as a result also never having their `_dirty` flag reset by the view). The critical lines are [Builder.js#L198-L202](https://github.com/vega/vega/blob/master/src/scene/Builder.js#L198-L202), where the variable `fcs` can point to an outdated change set from a prior propagation cycle.

If I replace `fcs` with `output` in the `join` call in L201, the problem appears to resolve. However, I'm not sure if this has other unwanted effects, so I need @arvind to review.

**Comment by arvind** [comment]
Nice catch! We don't want to replace `fcs` with `output` in the `join` call because that changeset is used to do a streaming data join. Instead, as per ed976de, `join` is no longer responsible for creating a new output changeset, which is instead also passed in along with the `input`/`fcs` changeset. 

This has fixed the issue with the spec in vega/vega-scenegraph#17, and I haven't noticed any impact on the other static or interactive examples in the vega-editor. It'd be good to get a second pair of eyes on them though so please re-open if you notice any issues. Thanks!
