### ISSUE TITLE
Documentation request: putting Vega graphs in Github Pages

### ISSUE THREAD

**Issue by jowens** [vega/vega#403]
Github Pages (https://pages.github.com/) are a very nice documentation tool. How can I embed a Vega graph in Github Pages? At first glance this seems complex because I need to include a bunch of .js files in HTML headers, but at least with some Github Pages scenarios (e.g., when you write your docs in markdown), you don't really have access to the headers.

It would be terrific to have an example of how to embed Vega graphs into Github Pages in the docs. Since Vega itself is in github, maybe that's a place to start; alternatively any pointers to "Hey, look at this project, they are embedding Vega graphs in their Github Pages", and/or pointers that use Jekyll, Doxygen, etc. would be helpful.

**Comment by randyzwitch** [comment]
You can embed arbitrary JS and HTML in GitHub Pages. I just tried it and it worked, so I might move over to rendering with Vega instead of using PNG files.

The basic steps are outlined already in the [documentation](https://github.com/vega/vega/wiki/Runtime):

1. Your `_layouts` folder will have your templates in it. I'm using the `minimal` theme, so I only have one file. This file is written in HTML and provides the skeleton to your HTML; you can put all the Vega JS libraries in the head here.

2. In an individual markdown file, you can place arbitrary HTML/JS and Jekyll will render it from Markdown to HTML after you do a commit/push to `gh-pages`. For example, here's an example from my documentation:

```html
### Vertical Bar
{% highlight julia %}
using Vega

x = [1, 2, 3, 4, 5]
y = [1, 2, 3, 2, 1]

barplot(x = x, y = y)
{% endhighlight %}

 <div id="vis"></div>

 <script type="text/javascript">
// parse a spec and create a visualization view
function parse(spec) {
  vg.parse.spec(spec, function(chart) { chart({el:"#vis"}).update(); });
}
parse(

{"name":"Vega Visualization","height":450,"padding":"auto","marks":[{"properties":{"enter":{"x":{"field":"x","scale":"x"},"y2":{"field":"y2","scale":"y"},"width":{"offset":-1,"scale":"x","band":true},"fill":{"field":"group","scale":"group"},"y":{"field":"y","scale":"y"}}},"from":{"data":"table"},"type":"rect"}],"axes":[{"properties":{"title":{"fontSize":{"value":14}}},"title":"x","type":"x","scale":"x"},{"titleOffset":40,"properties":{"title":{"fontSize":{"value":14}}},"title":"y","type":"y","scale":"y"}],"data":[{"name":"table","values":[{"x":1,"y2":0,"group":1,"y":1},{"x":2,"y2":0,"group":1,"y":2},{"x":3,"y2":0,"group":1,"y":3},{"x":4,"y2":0,"group":1,"y":2},{"x":5,"y2":0,"group":1,"y":1}]}],"scales":[{"name":"x","range":"width","domain":{"data":"table","field":"x"},"type":"ordinal"},{"name":"y","range":"height","domain":{"data":"table","field":"y"},"type":"linear"},{"name":"group","range":["rgb(166,206,227)","rgb( 31,120,180)","rgb(178,223,138)","rgb( 51,160, 44)","rgb(251,154,153)","rgb(227, 26, 28)","rgb(253,191,111)","rgb(255,127,  0)","rgb(202,178,214)","rgb(106, 61,154)","rgb(255,255,153)","rgb(177, 89, 40)"],"domain":{"data":"table","field":"group"},"type":"ordinal"}],"width":450});
</script>
```

For a live example of the above, you can view source for 'Vertical Bar'
http://johnmyleswhite.github.io/Vega.jl/barplot.html

3. Only thing to keep in mind is that if you are going to render multiple visualizations on the page, you'll have to change the `div id`; it probably makes the most sense to add an argument to the `parse` function for the div id name.

Hope this helps.

**Comment by jowens** [comment]
@randyzwitch This is extremely useful. Thank you so much for this detail. We will digest and get back to you when we have questions, many thanks.

**Comment by randyzwitch** [comment]
You're welcome, please feel free to ask any questions as they arise. You probably want to use https://groups.google.com/forum/#!forum/vega-js, as I suspect this issue will get closed.

Here's another example for overkill...interactivity works as well, so there doesn't seem to be a limit to what gh-pages will accept
http://johnmyleswhite.github.io/Vega.jl/asterplot.html
