### ISSUE TITLE
Missing Documentation for Scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega#406]
- [ ] `bandWidth`
- [ ] `outerPadding` 
- Add default values for properties (Users can experiment in the editor to find the default behavior — but we better just make it clear in the doc)
  - [ ] points, nice = false
  - [ ] round = ?????
- Relationship between scale.point and `band:true` of mark’s scaleRef (#493)

**Comment by kanitw** [comment]
- Add default values for properties (Users can experiment in the editor to find the default behavior — but we better just make it clear in the doc)
  - [ ] points, nice = false
  - [ ] round? —

**Comment by kanitw** [comment]
- [ ] `outerPadding` is also undocumented

**Comment by domoritz** [comment]
- [ ] `points` is also documented

**Comment by domoritz** [comment]
At least some of these properties also seem to be missing from the typings.

**Comment by jheer** [comment]
This issue is outdated, and stems from the Vega 2.x days.

- There is no `outerPadding`. `paddingOuter` is documented under [band scales](https://vega.github.io/vega/docs/scales/#band-scales).
- There is no `bandWidth`. Range `step` is documented under [scale ranges](https://vega.github.io/vega/docs/scales/#scale-ranges).
- There is no `points`, which I believe was from the time when ordinal scales were also band and point scales. We now have different scale types (ordinal, point, band).
- And so on...

For other properties (nice, round, etc), I will update the docs to indicate default values.
