### ISSUE TITLE
Error "TypeError: data[k] is not a function" in Streaming-Data

### ISSUE THREAD

**Issue by keizer619** [vega/vega#432]
I have updated to Vega 2.3.0 and i am getting above exception when i am using following API method to update chart data in a Line chart [1]

view.data(data)
view.update();

So then i tried insert() method as mentioned document. There data is getting inserted and  x, y axis will be updated but line is not drawn 

[1] http://tharik.org/realtime-charts/streamDataDefine.html

[2] http://tharik.org/realtime-charts/streamDataInsert.html

**Comment by arvind** [comment]
Yes, `insert` is what you want to be using as you do with this line: `view.data("cars").insert([{"horsepower": 4,  "torque": 120, "z": 1}]);`. I see a line chart successfully drawn with your second link, so perhaps you've resolved your question since posting this issue? :) 

I'm going to go ahead and close this out. If you're still experiencing trouble, please post to the [vega-js google group](https://groups.google.com/forum/#!forum/vega-js). Thanks!

**Comment by keizer619** [comment]
@arvind  ; 
Actually its not drawing properly. 

Initially graph is drawn for following 3 values which is correct.
{"horsepower": 1,  "torque": 10, "z": 1},  
{"horsepower": 2,  "torque": 19, "z": 1},
 {"horsepower": 3,  "torque": 17, "z": 1}

Then i use insert() and insert following value to the existing graph. where as it should be draw for points of y axix as 10,19,17 and 120. but it keeps previous graph (with 3 points) and update x and y axis without updating the line.
[{"horsepower": 4,  "torque": 120, "z": 1}

**Comment by arvind** [comment]
Ahh I see. In your mark specification, change `enter` to `update`. See [this article](http://bost.ocks.org/mike/join/) for more information. Essentially, `enter` is only called for new data tuples, while `update` is called for new+existing tuples. As your line is only specified on enter, the points aren't redrawn (i.e., don't move) after the additional data point is inserted.

**Comment by keizer619** [comment]
@arvind  Thank you very much for the explanation, it resolves the issue.
