### ISSUE TITLE
Sorting scales and sort transform question

### ISSUE THREAD

**Issue by domoritz** [vega/vega#445]
I'm a bit surprised that the syntax for sorting scales differs from the syntax for sort transforms.

in a transform
```js
{"type": "sort", "by": "-median_yield"}
```

in a scale domain
```js
"sort": {
    "field": "yield",
    "op": "median",
    "order": "desc"
}
```

What is the reason for the difference? Does vega support sorting in a transform if the field name is not a simple identifier (e.g. it has spaces like `Foo bar`)?

**Comment by kanitw** [comment]
I think the reason scale domain has `op` is that sort transform does not have to handle duplicate values but in scale, the same domain values from different rows are grouped and therefore needs an aggregate op to aggregate values in case you want to sort the values using another field.   

When you say 
```
{"type": "sort", "by": "-median_yield"}
```

This requires that you perform aggregate transform before doing sort transform.
However, in scale domain, the aggregation is performed on the scale.

**Comment by domoritz** [comment]
My question is more about why `by` vs `field` and `-name` vs `order:desc|asc`.

**Comment by kanitw** [comment]
That part I don't know :P

**Comment by jheer** [comment]
I created the `sort` transform back in Vega 1. Since then, the updates are by @arvind, so he'll have to answer the question...

**Comment by arvind** [comment]
Good questions. The `sort.order` property was deprecated in v2.2.5 and I've removed it altogether with commit c811d5b because of the confusion it has been causing. For ordinal scales, applying any sorting (`true` for natural/key order, and an object for aggregation) will result in an ascending order. The `reverse` property can be set to `true` for the opposite. 

The reasons for `by` vs. `field` are similar to what @kanitw said above. The Sort transform's `by` parameter constructs a field accessor -- i.e., over existing fields. Ordinal scales, on the other hand, aggregate across (possibly multiple distinct) domains; the `sort` property thus simply extends the aggregation with additional operations. Any sorting specified is conducted internally to the scale, and is not reflected in the backing data sources. Reusing `by` in this context would be overly confusing -- we would only support strings of the format `AGGOP_FIELDNAME`. I instead preferred the current design of `sort` which is more explicit and constrained (via the schema). 

Hope this helps!

**Comment by domoritz** [comment]
To document the answer to the second question that was answered offline, if a field name is not a simple identifier (e.g. it has spaces like `Foo bar`), reversing in a transform still works. So 

```js
{"type": "sort", "by": "-Foo Bar"}
```

works.
