### ISSUE TITLE
Incomplete domain passed to datalib

### ISSUE THREAD

**Issue by domoritz** [vega/vega#458]
It looks like vega does not pass the complete domain to datalib's auto format. See issue https://github.com/vega/datalib/issues/50

```js
{
  "height": 200,
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,  "y": 20}
      ]
    }
  ],
  "scales": [
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "domain": {"data": "table", "field": "y"},
      "nice": true
    }
  ],
  "axes": [
    {"type": "y", "scale": "y", "format": "s"}
  ]
}
```

<img width="51" alt="screen shot 2015-11-30 at 18 58 10" src="https://cloud.githubusercontent.com/assets/589034/11491183/55e4ab16-9794-11e5-9208-0b1836064cc0.png">

**Comment by arvind** [comment]
Hmm, I'm not sure that this is a Vega issue. For linear (quantitative) scales, we only calculate the minimum and maximum values for scale domain. We could store distinct values but that would be a tremendous waste of time+space. Moreover, I think your spec is a great illustration of why this is _not_ a Vega issue: with only one value (`20`) in the dataset (and with `"zero": true` by default), the domain is `[0, 20]`. What would a "more complete" domain be? [0..20] in 1-step increments? 2-step increments? 

It looks like the bug was introduced with vega/datalib@c4c904f. datalib v1.4.6 correctly produces the following: 
<img width="36" alt="screenshot 2015-11-30 19 11 28" src="https://cloud.githubusercontent.com/assets/42262/11491377/31c69684-9796-11e5-960a-37fd60220eae.png">

**Comment by domoritz** [comment]
Note that the issue persists if the data values are `[{"x": 1,  "y": 20}, {"x": 2,  "y": 15}, {"x": 3,  "y": 0}]`. Vega still passes `[0, 20]`. 

Datalib could generate the correct (whatever that means) domain.

Vega could do something similar as well. There is no need to keep around the whole domain. What has to be passed to datalib as the domain are the values that will be used as axis labels. So in this case `[0, 2, 4, ..., 18,  20]`. So it should be enough to simply pass `major = tickValues || (scale.ticks ? scale.ticks(tickCount) : scale.domain())` as the domain to the formatter? 

However, why doesn't datalib just format numbers such that the most significant digit is preserved for each number individually? More of that discussion in https://github.com/vega/datalib/issues/50
