### ISSUE TITLE
Issue when building vega

### ISSUE THREAD

**Issue by JonathanH5** [vega/vega#522]
Hi,

I downloaded your project and tried to install the dependencies with npm install. This fails and the resulting log file asks me to open an issue about this topic here, what I do right now. I changed the file format to. txt from .log, because log files are not supported by GitHub (for whatever reason).

The corresponding operating system is Ubuntu 14.04 LTS inside a virtual machined (Parallels Desktop 11).

Best,
Jonathan.
[npm-debug.txt](https://github.com/vega/vega/files/127828/npm-debug.txt)

**Comment by arvind** [comment]
Hi @JonathanH5, this looks like an error downloading/installing somewhere deep in the dependency tree (with the `qs` module) rather than with Vega itself. I'm not having any trouble re-running `npm install` locally so I would recommend clearing out your `node_modules` folder, running `npm cache clean` and trying again.
