### ISSUE TITLE
Dynamic data urls

### ISSUE THREAD

**Issue by nyurik** [vega/vega#523]
Is there a way to dynamically construct data URLs based on a signal?  This example uses wikidata queries to generate a map, but it would be great if I could change the query based on the user's actions.

http://en.wikipedia.beta.wmflabs.org/wiki/Sparql

**Comment by arvind** [comment]
Hi @nyurik, this is currently not supported as data is loaded at parse-time rather than run-time. As a result, I'm marking this issue as a feature request (and PRs would be most welcome!). 

In the interim, one option would be to use [signal listeners](https://github.com/vega/vega/wiki/Runtime#view-component-api) and the [Streaming Data APIs](https://github.com/vega/vega/wiki/Streaming-Data). With this approach, you'd load data outside of Vega, and then feed it in.

**Comment by nyurik** [comment]
This issue might be superseded by #912
