### ISSUE TITLE
Dynamic axis formatting / scale?

### ISSUE THREAD

**Issue by jazzido** [vega/vega#525]
Hi,

I'm trying to build a stacked area chart, that reacts on a signal for toggling between absolute and normalized values. The absolute values are in a _currency_ domain and the normalized ones are percentages.

Is there any way to set an axis' `format` and `scale` properties from a signal?

https://gist.github.com/jazzido/5660ba691c465010b138

**Comment by arvind** [comment]
Unfortunately not yet, but it's a reasonable request! I've tagged this issue as an enhancement, and hope to get to it for a future release. Thanks!

**Comment by domoritz** [comment]
This would also allow us to have smarter defaults for axis formatting in Vega-Lite.

**Comment by jazzido** [comment]
I'd be happy to take a shot at implementing this. Is there any similar functionality in the codebase that I could use as a guide? If not, how would you implement this?

**Comment by arvind** [comment]
Hi @jazzido, thank you for offering! Making guides (axes and legends) respond to signals will actual involve a non-trivial amount of churn on the code (particularly if the signal is used to determine the backing scale). I've switched the tag over to a feature-request, but I anticipate having to address it in fairly short order as we will need it in order to support interactive behaviours with Vega-Lite.

**Comment by miikka** [comment]
Is there any workaround for this? I have a zoomable line chart with a time axis and I'd like to change the tick label format depending on the zoom level.

**Comment by thermokarst** [comment]
Hi @arvind, I hate to pester, but is there any status update on this feature request? I am currently working on a visualization that would benefit from a dynamic `scale` property, but I seem to be bumping up against this issue. Thanks so much, `vega` is a pretty amazing project!

**Comment by jheer** [comment]
Hi everyone, this issue is a holdout from Vega 2, and has been partially addressed in Vega 3.

- You should now be able to use a signal to dynamically set the `format` property.
- You can _not_ dynamically set the `scale` property. Information about the specific scale (in particular, its type) is used within the Vega parser to determine the appropriate output. However, there is flexibility around which data fields are used to parameterize a scale -- so you can get dynamic axes by changing the underlying scale instead. For an example, see https://vega.github.io/vega/examples/scatter-plot-null-values/

As we do not currently intend to make changes here, I'm closing out the issue.

**Comment by kenklin** [comment]
@jazzido Also remember to relocate the `scale` references in `marks` from `enter` to `update` if you want them to be dynamic.
