### ISSUE TITLE
Transforms after aggregate are not processed in order

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#538]
Hey guys,

I just stumbled upon another sneaky issue. Here's an example spec.

```json
{
  "data": [
    {
      "name": "table",
      "values": [
        {"key_letter": "a", "key_number": 1, "value":  3},
        {"key_letter": "a", "key_number": 1, "value":  2},
        {"key_letter": "a", "key_number": 2, "value":  9},
        {"key_letter": "a", "key_number": 2, "value": 14},
        {"key_letter": "a", "key_number": 3, "value": 12},
        {"key_letter": "a", "key_number": 3, "value": 91},
        {"key_letter": "b", "key_number": 1, "value":  1},
        {"key_letter": "b", "key_number": 1, "value": 31},
        {"key_letter": "b", "key_number": 2, "value": 74},
        {"key_letter": "b", "key_number": 2, "value": 43},
        {"key_letter": "b", "key_number": 3, "value": 22},
        {"key_letter": "b", "key_number": 3, "value":  4}
      ],
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["key_letter", "key_number"],
          "summarize": [{"field": "value", "ops": ["sum"], "as": ["sum_values"]}]
        },
        {"type": "formula", "field": "key_combined", "expr": "datum.key_letter + datum.key_number"},
        {"type": "formula", "field": "key_letter", "expr": "upper(datum.key_letter)"}
      ]
    }
  ]
}
```

At first glance, you would expect the `key_combined` field to contain a lowercase letter and a number. But you actually get uppercase letters instead of lowercase! If you remove the `aggregate` transform, the issue does not occur.

Kind regards,
Jerry

**Comment by arvind** [comment]
Hi @Jerrythafast, you're experiencing this behavior because autopadding is kicking in and reevaluating the transform pipeline twice. The first time round, `key_letter` becomes uppercase and is used to build the `key_combined` the second time. If you set `"padding": 0`, this should go away. 

As for why you experience this only when the aggregate transform is present, the aggregate marks all fields it operates over as modified. The subsequent formula transforms see these flags and assume that they're required to recompute. When the aggregate transform isn't present, the operators are still evaluated twice but there's nothing forcing the formula operators to recompute so they don't!

Hope that helps!

-Arvind

**Comment by Jerrythafast** [comment]
Hey @arvind, thanks for the explanation. I am not 100% sure whether I would consider this behaviour 'useful' or even 'correct', but at least it is to be 'expected' as per your explanation. And I can see it would mean a huge hassle to change this as it would require Vega to keep the unchanged `key_letter` around and all.

So I guess I'll just have to work around this. In that respect, yep, your explanation helped ;)

Jerry

**Comment by arvind** [comment]
Indeed, this is a non-intuitive edge case which is why we recommend that the formula transform primarily be used to extend the original dataset rather than override values.
