### ISSUE TITLE
Layout should be updated

### ISSUE THREAD

**Issue by domoritz** [vega/vega#547]
Vega computes the layout (padding) based on the initial set of data. But if data or signals change, the padding is not recomputed. This causes problems if the data changes and the padding was initially set to be too small. 

A problem with recomputing the layout when any signal changes is performance. Also, the chart itself would jump and change sizes.

**Comment by Jerrythafast** [comment]
For what it's worth, I'm currently working around this by doing `view.padding("auto").update();` whenever I'm making changes programmatically (e.g., via the streaming data API or signals) that could have consequences for the amount of padding or the dimensions of the visualisation in general. I simply leave out the `padding("auto")` when I know the padding won't change.

It would definitely be useful if Vega could do this automatically, but I expect that determining whether the padding needs to be recomputed is not always trivial. For example, I have some horizontal bar charts that change height depending on the number of bars in them. And there are multiple of those above/below each other in one visualisation, each potentially having a different height. The number of bar charts, their respective heights, and their respective offsets from the top of the scene are all computed from the input data. The `height` property of the scene is set to `10` as I let Vega's autopadding determine the actual height of the visualisation. I would be very impressed if Vega could reliably determine whether the padding needs to be computed due to a change in the data in a complex setting like this!

**Comment by domoritz** [comment]
Vega has `autosize.resize` to address this.
