### ISSUE TITLE
Union transform

### ISSUE THREAD

**Issue by domoritz** [vega/vega#554]
To compute the layout over multiple fields (potentially from different datasets) in Vega-Lite, we need a union transform.

**Comment by domoritz** [comment]
Duplicate of https://github.com/vega/vega-transforms/issues/10

**Comment by hydrosquall** [comment]
I see was marked as closed. Perhaps the use-case for this is in Vega-Lite rather than Vega, because Vega-Lite does not allow defining datasets in terms of arrays of `source`, making it difficult to access the `union` capability

https://github.com/vega/vega-transforms/issues/10#issue-366765813

Let's say you have a Vega-Lite spec referencing two CSVs that have the same schema (state, country, total), but involve data from different years. 

With a `union` transform, we could "combine" those tables without reaching for an external tool

Currently, you will need to perform any data unions outside of Vega. Adding a union transform seems like a natural complement to the existing lookup transform.
