### ISSUE TITLE
Theme documentation clarification

### ISSUE THREAD

**Issue by randyzwitch** [vega/vega#595]
Normally I'd make these changes to the wiki directly, but I wanted to validate first...

1. Is this the canonical way to implement themes, or is there a better way? This would be a great update to [Runtime](https://github.com/vega/vega/wiki/Runtime) and/or [Themes](https://github.com/vega/vega/wiki/Theme-Configuration)

  ```html
<html>
  <head>
    <title>Vega Scaffold</title>
    <script src="https://vega.github.io/vega-editor/vendor/d3.min.js"></script>
    <script src="https://vega.github.io/vega-editor/vendor/d3.geo.projection.min.js"></script>
    <script src="https://vega.github.io/vega-editor/vendor/topojson.js"></script>
    <script src="https://vega.github.io/vega-editor/vendor/d3.layout.cloud.js"></script>
    <script src="https://vega.github.io/vega/vega.min.js"></script>
  </head>
  <body>
    <div id="vis"></div>
  </body>
<script type="text/javascript">
// parse a spec and create a visualization view
function parse(spec) {
  vg.parse.spec(spec, config, function(error, chart) { chart({el:"#vis"}).update(); });
}

config = {
  "background": "#f9f9f9",

  "marks": {
    "color": "yellow",
    "symbolSize": 20
  },

  "axis": {
    "padding": 2,
    "axisColor": "#979797",
    "tickColor": "#979797",
    "tickLabelColor": "#979797",
    "axisWidth": 0.5,
    "tickWidth": 0.2,
    "titleColor": "#979797",
    "titleFontWeight": "normal",
    "gridWidth": 0.2
  },

  "axis_x": {
    "tickSize": 10,
    "tickSizeEnd": 0,
    "grid": {
      "ordinal": false,
      "default": true
    }
  },

  "axis_y": {
    "tickSize": 0,
    "axisColor": "transparent",
    "grid": true
  },

  "legend": {
    "padding": 1,
    "labelFontSize": 11,
    "symbolShape": "square",
    "symbolStrokeWidth": 0
  },

  "range": {
    "category10": ["yellow", "#51b2e5", "#703c5c", "#168dd9", "#d190b6",
      "#00609f", "#d365ba", "#154866", "#666666", "#c4c4c4"]
  }
};

parse({
  "width": 400,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 30, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,  "y": 28}, {"x": 2,  "y": 55},
        {"x": 3,  "y": 43}, {"x": 4,  "y": 91},
        {"x": 5,  "y": 81}, {"x": 6,  "y": 53},
        {"x": 7,  "y": 19}, {"x": 8,  "y": 87},
        {"x": 9,  "y": 52}, {"x": 10, "y": 48},
        {"x": 11, "y": 24}, {"x": 12, "y": 49},
        {"x": 13, "y": 87}, {"x": 14, "y": 66},
        {"x": 15, "y": 17}, {"x": 16, "y": 27},
        {"x": 17, "y": 68}, {"x": 18, "y": 16},
        {"x": 19, "y": 49}, {"x": 20, "y": 15}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "range": "width",
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "domain": {"data": "table", "field": "y"},
      "nice": true
    }
  ],
  "axes": [
    {"type": "x", "scale": "x"},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "x": {"scale": "x", "field": "x"},
          "width": {"scale": "x", "band": true, "offset": -1},
          "y": {"scale": "y", "field": "y"},
          "y2": {"scale": "y", "value": 0},
          "fill": {"value": "steelblue"}
        }
      }
    }
  ]
});
</script>
</html>
  ```

2. It would appear that themes are parsed first, then if the Vega spec has a value, it overwrites the theme setting. Is this the correct order of operations?

3. In the vega editor, you can choose the themes by name ('excel', 'ggplot', etc.). Is there a way to reference these names directly, similar to this:
  ```js
function parse(spec) {
  vg.parse.spec(spec, theme = 'excel', function(error, chart) { chart({el:"#vis"}).update(); });
}
  ```

4. Similar to 3, are there plans for a central theme repository, so that developers can submit themes and users can just specify their literal name? I'm thinking a similar manner to how some color scales are defined such as `category10`

Thanks!

**Comment by randyzwitch** [comment]
Anyone who can help me with this? I want to make sure I'm implementing themes correctly before I release it in my Julia package. Thanks!

**Comment by arvind** [comment]
Apologies for the delayed response, @randyzwitch. 

1. A cleaner way might be to parameterize the `parse` method with a second `config` or `theme` variable like so. 

  ```js
function parse(spec, config) {
  vg.parse.spec(spec, config, function(error, chart) { chart({el:"#vis"}).update(); });
}
  ```

  which you can then call as 

  ```js
parse({
  "width": 400,
  "height": 200,
  ....
}, {
  "background": "#f9f9f9",
})
  ```

  This keeps the `parse` method sandboxed, and not dependent on any global variables. I'll work on adding a similar example to the Themes documentation.

2. Yes, that's right. Themes provide default values for the aesthetics/visual appearance of marks, axes, and legends. These defaults can be overridden by specifying them directly within the visualization specification.

3. Unfortunately, it is not yet possible to load themes via a URL (like you can with specs). If this is functionality you'd like to see, could you please open another GitHub issue and tag it as a feature request so that we can track it? Thanks!

4. This sounds like a great idea. In lieu of a full fledged theme directory, perhaps we can start with a simple page on the wiki a la the [Examples Gallery](https://github.com/vega/vega/wiki/Gallery)? Perhaps you could also post to the [vega-js google group](https://groups.google.com/forum/#!forum/vega-js) to see if there are community members interested in contributing or building out something more robust? 

Hope this helps!
