### ISSUE TITLE
CanvasHandler.js:183 Uncaught TypeError: Cannot read property 'marktype' of undefined

### ISSUE THREAD

**Issue by owendall** [vega/vega#619]
I could not reopen the last one, but this is really a different issue:

For some reason the object "scene" is undefined.  I
![scene is not defined](https://cloud.githubusercontent.com/assets/10927/18179434/6dfdaaa0-7050-11e6-95f7-9489b94deffd.png)

http://bl.ocks.org/owendall/141e5fb23f37fdcff5842aa57b24d707

Sorry for the noob questions, but I will post the solution for others. :-)

**Comment by arvind** [comment]
@owendall Where did you find that spec? It looks like the wordcloud spec for Vega 1. The definition of the wordcloud transform has changed in Vega 2. See the [online wordcloud example](http://vega.github.io/vega-editor/?mode=vega&spec=wordcloud) for a working example.

**Comment by arvind** [comment]
Also, we encourage posting questions and requests for help to the [vega-js Google group](https://groups.google.com/forum/#!forum/vega-js) rather than the issues here (which we prefer to keep for bugs, feature requests, etc.). You're also likely to get a faster response on the Google group as many members of the wider Vega community often weigh in with answers!

**Comment by owendall** [comment]
Sorry about that. I submitted a request to join the group but did not yet hear back.

Thanks again for your help.

I didn't realize I hit a forked link:
https://trifacta.github.io/vega/editor/
