### ISSUE TITLE
Cannot center rect marks

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#64]
Bar charts need to have their marks centered against their corresponding ordinal label, but there is no "xcenter" attribute. Using only the available "x" (left), "x2" (right), and "width" (width) attributes, it doesn't appear to be possible to center rect marks (at least when the size of the visualization canvas is not known at render time). Observe that the bars are not centered at http://livecoding.io/5620264

One possible solution could be to add a new "xcenter" attribute. Another possibility could be to overload the concept of "x" and "x2" such that when they are set to the exact same value, they are treated as the center specification. E.g., the following spec would draw bars at 70% of the band width centered over the scale's range for the point:

```javascript
  "marks":[
    {
      "type":"rect",
      "from":{ "data":"table" },
      "properties":{
        "enter":{
          "x":{ "field":"data.x", "scale":"x" },
          "x2":{ "field":"data.x", "scale":"x" },
          "width":{ "scale":"x", "mult":0.7, "band":true },
          "y":{ "field":"data.y", "scale":"y" },
          "y2":{ "value":0.0, "scale":"y" }
        }
    }
  ]
```

**Comment by ajturner** [comment]
@arvind does v2 address this? I have been running into it as well with the desire to make categorical bars narrower width, centered on their axis tick

**Comment by arvind** [comment]
Hmm, looks like this issue was erroneously closed by a v2 commit referencing a uwdata/vega issue. 

@ajturner, there are `xc` and `yc` properties that can be combined with `width` and `height` respectively. However, for your particular case of varying the width of categorical bars, what you actually want to be tweaking is the `padding` of your ordinal scale. Hope that helps!
