### ISSUE TITLE
Inconsistent argument position

### ISSUE THREAD

**Issue by domoritz** [vega/vega#660]
The position of the datum argument is not consistent across functions in the expression language. 

```js
format('$.1f', datum.value)
truncate(datum.value, 25)
```

With the templating language, it used to be clear in what order you have to provide arguments. What is the reason for removing the template language in Vega 3?

**Comment by jheer** [comment]
Thanks! We do want this to be consistent. Fixed in vega/vega-parser@4c4d8ce7b977d68d8b5f0a71e8ddb96686a40791; released in Vega version `3.0.0-beta.5`.

The template language was removed to reduce surface area and simplify implementation. Now that Vega 3 is largely stable, we can consider bringing it back if warranted. For example, we could now transform template directives into Vega expressions under-the-hood. If desired, please open an issue on [vega/vega-parser](https://github.com/vega/vega-parser), including an argument for why templates should be re-introduced in the face of equivalent expression language functionality.

**Comment by kanitw** [comment]
FYI, we migrate Vega-Lite to just use signal instead.  So while we might consider bringing it back for other reasons in the future, VL is no longer one of the reasons. :)

**Comment by domoritz** [comment]
I can't think of any good reasons to bring back the template language. We as programmers are used to reading them and they are easy to test outside of vega for example in the browser console.

**Comment by kanitw** [comment]
I assume @domoritz's "them" means using string concat in JS expression.  :)

**Comment by domoritz** [comment]
No, I mean we are used to reading expressions (especially nesting). String concatenation is a bit ugly but at least understandable. A simple template language with expressions rather than the filter/modifiers seems useful (e.g. similar to es6/typescript https://basarat.gitbooks.io/typescript/content/docs/template-strings.html)
