### ISSUE TITLE
Consider dropping support for node 0.12

### ISSUE THREAD

**Issue by domoritz** [vega/vega#671]
Node 0.12 is reaching the [end of maintenance at the end of this year](https://github.com/nodejs/LTS#lts-schedule) and [usage numbers are at <6%](https://twitter.com/seldo/status/793264271417184256). 

![schedule](https://cloud.githubusercontent.com/assets/589034/20910083/4196ef12-bb14-11e6-82f3-bbbbb9169ff2.png)

![cwi9syrvuaay0gf](https://cloud.githubusercontent.com/assets/589034/20910097/5fce8f6c-bb14-11e6-9759-02358bbe66a1.jpg)

Why? We could use yarn for reproducible builds, fix [#664 by upgrading jsdom](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#700) and potentially more things in the future.

**Comment by jheer** [comment]
On the other hand, it looks like v0.10 is still ~10%?

**Comment by domoritz** [comment]
True, but we don't even test against it any more ;-) Also, I'm not exactly sure whether the numbers above also count installs from travis, which could skew the results.

**Comment by jheer** [comment]
Actually, Vega fails to compile under node v0.10 due to `rollup` trying to reference a non-existent `Map` class. I think we can drop v0.12 support by end of year. As for other aspects (use of yarn, etc) that can be handled on a different issue or PR. Closing this issue now. Related node migration discussion can continue on #664.
