### ISSUE TITLE
Simplifying field reference

### ISSUE THREAD

**Issue by nyurik** [vega/vega#692]
I was reading https://github.com/vega/vega/blob/master/PORTING_GUIDE.md#marks-and-visual-encoding about more powerful `signal`, as well as more elaborate `offset`/`mult`.  Would it make sense to simplify all of it into just one string expression?  Is there a reason to keep the multiple ways to express the same thing:

now | proposed
-----| ----- 
| `value: 10` | `10`|
| `field: "foo"` | `datum.foo`|
| `field: "foo", offset: 10`|`datum.foo + 10`|
| `field: "foo", scale: "bar"`|`bar(datum.foo)`|
| `signal: "foo + 10", scale: "bar"`|`bar(foo + 10)`|

This makes the syntax much more compact, shrinks Vega codebase, and reduces the Vega learning curve.  Of course I might not understand something about the system that makes it impossible to express it as an expression.

**Comment by arvind** [comment]
Hi @nyurik, while the inline/anonymous signals are handy when hand-writing Vega specifications, the more structured syntax simplifies generating Vega specifications as part of higher-level systems (e.g., Vega-Lite, Lyra, etc.). Without this structure, these higher-level systems would instead need to grapple with building, parsing, and reasoning about strings. It's for this reason that we introduced a more structured representation for [Vega-Lite's filter transform](https://github.com/vega/vega-lite/issues/1376), for instance.

**Comment by nyurik** [comment]
@arvind thx, but can we have the best of both worlds - if its a string, its an expression (same as signal), and if its an object, it is structured?

**Comment by nyurik** [comment]
Also, if the only reason to have a structured expression representation is to help higher level systems to treat Vega as a purely storage format, would it perhaps make sense to expose the internal vega expression parser to them? This way Lyra could look at the structure not at its raw form, but after being parsed into an expression tree, and if it can make sense of it, use it, otherwise simply reject it?  Expression generation should also be a fairly straightforward few conversion.

**Comment by arvind** [comment]
I'm sorry, I'm not sure what you mean by the "best of both worlds" -- isn't that what we will have with Vega 3? Exposing the expression parser to higher-level systems is not the most viable option because the abstract syntax tree it produces is at a much lower-level of abstraction than what is useful for these systems. 

Here's a simplified example. In Lyra, to display a UI element for the scale used by a particular visual property, I can directly access the `scale` property in the JSON. If instead the scale were specified as a string, I would first need to parse the string, then analyze the AST to determine what the string contains (a `scale()` function), and then look at its arguments to get which specific scale was referenced. Some of our other applications need to enumerate, cluster, and rank various Vega/Vega-Lite specifications, and being able to do that directly rather than through intermediary string representations considerably simplifies things.
