### ISSUE TITLE
[vega 3.0] view.on generates error

### ISSUE THREAD

**Issue by floribon** [vega/vega#695]
When writing a simple custom event listener, we get the following error:

```javascript
view.on(view.events('view', 'mouseover'), e => {
  console.log(e);
});
```

![screen shot 2016-12-30 at 5 34 34 pm](https://cloud.githubusercontent.com/assets/2934743/21568613/4d6b9a94-ceb6-11e6-88a3-cce61e142425.png)

It seems to come from `onStream` method which expects the callback to return something:

```javascript
func = function(e) {
  df.touch(target(e)); // breaks when target(e) is undefined
};
```

If you'd like (and it is a proper fix) I can create a PR with this change:

```javascript
func = function(e) {
  var t = target(e);
  if (t) {
    df.touch(t);
  }
};
```

**Comment by jheer** [comment]
Thanks @floribon. I think there is a (completely understandable) confusion here due to differences between Vega 2 and Vega 3. In Vega 2, `view.on` is used to register event listeners. In Vega 3, `view.on` is almost entirely different: it updates dataflow `Operator` instances in response to event streams or other other operators (the `View` class inherits this method from its `Dataflow` parent class). I would not use it for your purposes here.

Instead, I recommend doing one of two things:
- You are already using `view.events` to generate an event stream. You can add a listener to the event stream directly, creating a derived event stream: `view.events('view', 'mouseover').apply(function(e) { console.log(e, e.item); })`.
- Alternatively, to attach listeners akin to the Vega 2 `on` method, you can register callbacks directly with the scenegraph handler: `view._handler.on('mouseover', function(e, item) { console.log(e, item); })`. Note that this breaks encapsulation by directly accessing the underlying handler instance. We currently do not provide a public accessor method, but we could if useful. Related issues are best filed on the [vega-view repo](https://github.com/vega/vega-view/issues).

All registered listeners are copied over if the renderer/handler is changed at runtime (e.g., from SVG to canvas, or vice versa), so both approaches are robust to such changes.

**Comment by floribon** [comment]
Thanks @jheer, the first approach feels natural and clean. Your [porting guide](https://github.com/vega/vega/blob/master/PORTING_GUIDE.md) would definitely benefit from it as this is one of the only bit not covered.

I can open a new ticket on the vega-view repo if needed, but would you know if there is any alternative to **`view.onSignal`** from vega 2? Another person was having the same problematic ([cf](https://groups.google.com/forum/#!searchin/vega-js/onSignal%7Csort:relevance/vega-js/cJMX_uxWISo/H4hRgUPJCwAJ)). If there is no public way to access it yet, do you plan to add one in the future? (and a temporary internal workaround is welcome as well)

**Comment by jheer** [comment]
Yes, I'll plan to add this to the porting guide soon. I also intend to add the onSignal method soon. In the meantime, here is a "polyfill" you can use to match Vega 2's `onSignal` behavior:
```js
vega.View.prototype.onSignal = function(name, handler) {
  if (!this._signals.hasOwnProperty(name)) {
    this.error('Unrecognized signal name: ' + name);
  }
  var signal = this._signals[name];
  this.on(signal, null, function() {
    handler(name, signal.value);
  });
};
```

For example, you can then do this on the `bar-hover-label` example:
```js
view.onSignal('label', function(name, handler) { console.log(name, handler); });
```

**Comment by jheer** [comment]
I've now updated the porting guide. I've also extended the Vega `View` class with new methods:
- addEventListener / removeEventListener (for traditional input event callbacks)
- addSignalListener / removeSignalListener (which replace the v2 onSignal / offSignal methods)

**Comment by floribon** [comment]
That's really great, thanks a lot!
