### ISSUE TITLE
Use 'fit' as default for Vega3

### ISSUE THREAD

**Issue by nyurik** [vega/vega#699]
I think the width/height top-level params should be treated with "fit" option by default. Just like we set width/height on the html's <img> element and expect the image to "fit" to these values, the width/height params imply the final graph size for most users, not the internal "main drawing area" concept.  Also, I would suggest the padding to be inside the width/height, not outside of it, but this is not as important.

**Comment by arvind** [comment]
Rather than images, a better analogy would be the default [CSS box model](http://www.w3schools.com/css/css_boxmodel.asp) where the `width` and `height` properties determine the dimensions of the _content_, and padding applied thereafter for the final element sizing. In CSS, this behavior can be modified using the [box-sizing](http://www.w3schools.com/cssref/css3_pr_box-sizing.asp) property to force `width` and `height` to be the ultimate size of the box. These two modes correspond to `"autosize": "pad"` (the default) and `"autosize": "fit"` in Vega 3 respectively.

Given this well-established model, and that it can be tricky to estimate the effect of axes and legends on layout, my vote would be to maintain the default auto sizing behaviour in Vega 3.

**Comment by nyurik** [comment]
@arvind, I think padding can be left out of the width/height, but the axis and legend are clearly part of the "content". Internally Vega may treat some content as more prominent than other, but this is really an internal nuance - if you use grouping, there are also sub-content areas with their own legends, etc. Lets treat all content the same, and, by default, only pad on the outside of the width/height box?  Thanks!

**Comment by jheer** [comment]
The default of `"pad"` was chosen for multiple reasons, we don't currently plan to change it.
1. Treating width/height as the data rectangle dimensions is a long-standing Vega convention going all the way back to v1. Changing the default could cause unintended confusion among existing users.
2. Using `"pad"` as the default helps users better notice problems and fix bugs. For example, before we introduced auto-padding sometimes users inadvertently placed marks "off-screen", couldn't see them, thought Vega was buggy, and got frustrated. With auto-padding the view resizes, users see their content, and they can then can adjust the visualization as needed. This can be particularly helpful for visualizations of trees, graphs, and maps.
3. In any case, as of Vega 3 you can _change system defaults_ via configuration objects that are passed as a parameter to the Vega parser. If you want to make `"autosize": "fit"` the new default in your deployment there's actually nothing stopping you! See [the vega-parser readme](https://github.com/vega/vega-parser#top-level-properties) for details.
