### ISSUE TITLE
V2: Path (map) based graphs don't work in padding:strict

### ISSUE THREAD

**Issue by nyurik** [vega/vega#701]
Modify [choropleth](https://vega.github.io/vega-editor/?mode=vega&spec=choropleth):
```
  "width": 160,
  "height": 100,
  "padding": "strict",
```
The graph is not clipped (expected), but instead it has a strange width and a partial bottom clipping.

**Comment by arvind** [comment]
Yes, unfortunately Vega 2's more naive layout mechanism fails with cartographic transforms because their size is determined by the `scale` property in the transform definition. One workaround is to nest the `path` mark within a `group` mark clipped to the overall dimensions of the visualization like so:

```json
"marks": [
    {
      "type": "group",
      "properties": {
        "update": {
          "x": {"value": 0},
          "y": {"value": 0},
          "width": {"signal": "width"},
          "height": {"signal": "height"},
          "clip": {"value": true}
        }
      },
      "marks": [{
      "type": "path",
      "from": {"data": "counties"},
      "properties": {
        "enter": { "path": {"field": "layout_path"} },
        "update": { "fill": {"scale": "color", "field": "unemp.rate"} },
        "hover": { "fill": {"value": "red"} }
      }
    }]
    }
  ]
```

Vega 3 clips the visualization as expected.
