### ISSUE TITLE
Referencing signal for scale property not working

### ISSUE THREAD

**Issue by Naisunev** [vega/vega#763]
Great work you've been doing in releasing version 3. I'm currently porting the version 2 work to version 3 and I'm running into a referencing error. 

In marks I used to do:                   
                  "y": {"scale": {"signal": "parameter"},"field": {"datum": {"signal": "parameter"}}},

but this gives me an error in version 3:
- Uncaught (in promise) TypeError: _[("%" + datum[_.$parameter])] is not a function

I also tried: 
                  "y": {"scale": {"signal": "parameter"},"field": {"signal": "parameter"}},
But this gives a similar error.

It's todo with the "scale": not expecting a reference. This is also the case in the "axis" property for scale. 
Is this todo in the version 3 release, or am I approaching this the wrong way?

**Comment by jheer** [comment]
Thanks @Naisunev! The problems with indirect scale lookup are due to a bug in vega-parser, which is now scheduled to be fixed in the next beta release.

The axis `scale` parameter, however, currently **must** be a literal scale name. You can not use a signal reference there. You can instead make the scale itself dynamic (e.g., define the scale domain using a signal for an indirect field reference) in order to have dynamic axis bindings. To see how this can be done, check out the [Scatter Plot Null Values](https://vega.github.io/vega/examples/scatter-plot-null-values/) example.

**Comment by jheer** [comment]
A fix has been published in vega-parser v1.0.0-beta.42, and will be incorporated into the next Vega v3 beta release.
