### ISSUE TITLE
Responsiveness only seem to works on axes

### ISSUE THREAD

**Issue by mattijn** [vega/vega#772]
I tried to include a vega 3 visualization (example 'area') into resizable div element, but only the axes are scaling:
![jsfiddle](https://cloud.githubusercontent.com/assets/5186265/24820863/9eb27800-1beb-11e7-933c-8ae9d82f7ffc.gif)

Am I missing something?
Complete jsfiddle is there: https://jsfiddle.net/mattijn/dtbqgw3d/

Code here: 

```
//var state = view.getState();
//console.log(JSON.stringify(state));
var widthListener = view.addSignalListener('width', function(name, value) {
  console.log(name + ': ' + value);
});

$(function() {
  $("#resizable").resizable({
    minHeight: 150,
    minWidth: 250,
    resize: function(event, ui) {
      var width = ui.size.width - 50;
      var height = ui.size.height - 50;
      view.signal('width', width).run();
      view.signal('height', height).run();
      //state['signals']['width'] = width
      //state['signals']['height'] = height
      //console.log(JSON.stringify(state));
      //view.setState(state);              
    }
  })
});```

**Comment by jheer** [comment]
First line of defense: are your `encode` definitions in the `enter` block? If so, they will not re-run by design. If so, here are two solutions:

1. Move encoding definitions to the `update` block. This will work generally, but also means unnecessary updates may be computed in response to events other than resizing (e.g., hover).
2. Explicitly request that the `enter` block be re-evaluated when you re-run the dataflow upon resize. (Note also that you probably only want to invoke the `run` methods _once_ upon resize!)
```js
resize: function(event, ui) {
  view.signal('width', ui.size.width - 50)
      .signal('height', ui.size.height - 50)
      .run('enter');
}
```

Hope that helps!

**Comment by mattijn** [comment]
That helps a lot! It's great, thanks! Awesome haha.
