### ISSUE TITLE
Tick properties are ignored on an ordinal-scaled axes

### ISSUE THREAD

**Issue by gerwitz** [vega/vega#79]
`ticks` and its friend `subdivide` are ignored when rendering axes based on an ordinal scale. (Just because I'm drawing bar charts doesn't mean I want to render every tick and label.)

For my use case, this would be resolved by #62, but this would still be an inconsistency that ought to at least be documented.

I have devised a workaround of setting a `values` array on the axes with empty values where I do not wish a label.

**Comment by arvind** [comment]
The [[Axes]] documentation page has been updated to reflect that `ticks` are `subdivide` only apply to axes of quantitative scales. The reason that we don't support them for ordinal scales is because there's no easy way for Vega to determine _which_ ordinal values to select. This is why we provide `values` as well.
