### ISSUE TITLE
Should "rule" mark be renamed?

### ISSUE THREAD

**Issue by nyurik** [vega/vega#833]
I was reading the porting guide for vega 3, and it seems that since there is all this renaming to streamline it, would it make sense to rename "rule" to a better name?  E.g. "segment" or "line2" or ... ? Not a biggie.

**Comment by Fil** [comment]
I agree that `rule` might not be the best of names, because it makes you
think about rules and regulations, programmatic rules, etc. One could argue
that it should be line because of SVG, but hey that's toasted now.

However :

I don't like `line2` at all (there is no `line1,`, `line` is a very
different concept altogether, and you need to set `x1` and `x2` on `rule` —
I would find it confusing to have a notation of `line2.x1` and `line2.x2`).

`rule` is still better than `segment` IMO.

**Comment by nyurik** [comment]
brainstorming:  stroke, connector, edge, connector, ... ?

**Comment by jheer** [comment]
I share the sentiments above. Perhaps not the best name, but all the alternatives considered so far are inferior for one reason or another. Plus, there is the additional concern of adding one more breaking change. So I doubt we will change it at this point, but we certainly appreciate the suggestions!

**Comment by nyurik** [comment]
heh, oh well :)
