### ISSUE TITLE
Allow numeric values (unix timestamps) as datetime in parse

### ISSUE THREAD

**Issue by nyurik** [vega/vega#839]
As shown in https://github.com/vega/vega-lite/issues/2439 - numbers should be treated as datetimes if `"parse": {"field": "date"}` is set, especially if the numbers are strongly-typed (e.g.  type=json or embedded values).  Vega works fine if there is no "parse" directive, because all datetime-expecting functions can take a unix timestamp as input, but the parser fails if given a numeric value and asked to convert it to a datetime.

**Comment by jheer** [comment]
This requires a change to the `toDate` method in vega-util. I have no problem adding a conditional to our default parsing that checks for a number and uses that as a timestamp, and otherwise invokes `Date.parse`.

However, `toDate` can also accept a custom parsing function. One question is if the timestamp check should still be applied if a custom function is supplied. I lean towards "no". For example, one could imagine implementing a custom date format encoded as an integer, in which case the custom parser would never be invoked because the input values would be interpreted as UNIX timestamps.

I will go ahead and add timestamp checks to the default Date parser only. If you have any additional comments, please share!

**Comment by jheer** [comment]
Fixed in [vega-util v1.2.1](https://github.com/vega/vega-util/releases/tag/v1.2.1). Will be included in the next Vega release.
