### ISSUE TITLE
force directed layout: predefined indexed fields work while derived indexed fields do not

### ISSUE THREAD

**Issue by g3o2** [vega/vega#884]
As mentioned in #471, the dataset used in the [force directed layout example](https://vega.github.io/vega/examples/force-directed-layout/) requires "the `source` and `target` attributes [...] [to] refer to nodes by means of [zero-based] indexing.

```javascript
{
  "nodes": [
    {"name": "Myriel", "group": 1,"index": 0 },
    {"name": "Napoleon", "group": 1, "index": 1 }
  ],
  "links": [
    { "source": 1, "target": 0, "value": 1 }
  ]
}
```

Consequently, the following data structure would theoretically not work out of the box.

```javascript
{
  "nodes": [
    { "name": "Myriel", "group": 1 }, 
    { "name": "Napoleon", "group": 1 }
  ],
  "links": [
    { "source_name": "Myriel", "target_name": "Napoleon", "value": 1 }
  ]
}
```

Nevertheless, in Vega 2, as this [gist](https://bl.ocks.org/g3o2/703ff3c61c7811b8663c46fb0e1fa53b) (_please reload the page if it does not work right away_) demonstrates, it was possible to reconstitute the indices via `transform`s such that the data structure would conform to the requirements again and the visualisation was drawn as expected.

In Vega 3, it is also possible to reconstitute the indices via `transform`s (without any fiddling). The nodes are drawn (_after a few seconds_) __but__ the links are not drawn, as this [gist](https://bl.ocks.org/g3o2/0de28d093fcc9458deae60772948d89b) shows.

**Comment by jheer** [comment]
Your Vega 3 gist uses a lookup operator to bind the source/target fields of links to the input node data, but then applies the `force` transform to downstream _mark items_. This creates an error, as the nodes bound to each link are the "raw" input data objects, not the mark items upon which the force transform writes the x,y coordinates. (Internally, [D3's link force implementation](https://github.com/d3/d3-force/blob/master/src/link.js#L60) will skip any lookup if the source or target properties are objects.)

The trick here is to let the force layout perform the lookup for you, ensuring the correct binding is in place. (Note that there are major differences here between Vega 2 and Vega 3, in large part due to the move from D3 v3 to D3 v4.) Instead of performing a lookup operator, try using the [`id` parameter of the `link` force](https://vega.github.io/vega/docs/transforms/force/#link) to indicate the node property that matches the link source/target values..

**Comment by g3o2** [comment]
Thank you @jheer for the prompt answer and help!

When applying the `force` transform to downstream _mark items_, one also has to put `datum.` before the field name of the `id` property, otherwise it will still not render.

**Comment by PBI-David** [comment]
> Thank you @jheer for the prompt answer and help!
> 
> When applying the `force` transform to downstream _mark items_, one also has to put `datum.` before the field name of the `id` property, otherwise it will still not render.
> 
> P.S.: I've updated the gist here above.

This caught me out and would have been **very** useful to have in the documentation.
