### ISSUE TITLE
Unable to catch unhandled exceptions

### ISSUE THREAD

**Issue by nyurik** [vega/vega#892]
If a graph causes any kind of an exception during execution (after the initial parsing stage), there is no way to catch and prevent an "unhandled error" to be thrown.  Not throwing an error inside the logger.error() is not an option because most Vega code expects that method to abort execution.

This means that any apps like Kibana that show an error screen on unhandled error will not be able to use Vega.

We need a mechanism to catch and handle every type of exception.

**Comment by jheer** [comment]
Each dataflow instance includes an overridable method `dataflow.error` (there is no `logger.error` method). The default implementation is to simply raise an exception. In addition, the dataflow `run` method evaluates operators within a try/catch block; if an exception is raised then processing aborts, some clean-up is performed, and then `dataflow.error` is invoked.

I'm assuming the problem you're describing here arises due to use of `dataflow.error` within individual operators _and_ as the final result of error handling within `dataflow.run`. What if we added an additional `dataflow.abort` (or similar) method that is called instead of `error` when dataflow evaluation terminates early due to errors within individual operators? For example, the default implementation might be the same as `error`, but overridable for apps that would like to handle the exception. Or, perhaps we could scrub all operators to use vega-util's `error` method but _not_ the `dataflow.error` method, which could then be reserved for the final step (i.e., in the same role as `abort` above).

Also happy to entertain other possible solutions here.

**Comment by nyurik** [comment]
Right, I meant `view.error` & `view.warn`.

Here's an example of the code that passes the initial `run()`, but fails (code crashes with unhandled exception - editor does not warn about it - there are no error indicators, but console shows it, and many web apps that are strict about unhandled exceptions would crash.  I suspect nodejs is safe because it only does an initial run inside the try/catch.

Paste this code into https://vega.github.io/editor/#/examples/vega/bar-chart and move the mouse over one of the bars. Examine the debug console.

```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 400,
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    }
  ],

  "signals": [
    {
      "name": "tooltip",
      "value": {},
      "on": [
        {"events": "rect:mouseover", "update": "datum"},
        {"events": "rect:mouseout",  "update": "{}"}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "height"
    }
  ],

  "axes": [
    { "orient": "bottom", "scale": "xscale" },
    { "orient": "left", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0}
        },
        "update": {
          "fill": {"value": "steelblue"}
        },
        "hover": {
          "fill": {"value": "red"}
        }
      }
    },
    {
      "type": "text",
      "encode": {
        "enter": {
          "align": {"value": "center"},
          "baseline": {"value": "bottom"},
          "fill": {"value": "#333"}
        },
        "update": {
          "x": {"scale": "xscale", "signal": "tooltip.category", "band": 0.5},
          "y": {"scale": "yscale", "signal": "tooltip.amount", "offset": -2},
          "text": {"signal": "tooltip.amount"},
          "fillOpacity": [
            {"signal": "if(tooltip.category,tooltip.a.a.a, 0)"}
          ]
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment]
As of v3.0.0-rc2, any errors generated during dataflow or event stream evaluation are caught and then routed through the `dataflow.error` (aka `view.error`) logging function. By default this prints to the console. Clients can override this method (by assigning a new function) to perform custom error logging or presentation.

**Comment by nyurik** [comment]
Tested, works great, thanks!!!!  I simply removed all the `throw err` statements from the custom `view.error = (err) => ...` handler, and it continues to report the errors without crashing.
