### ISSUE TITLE
bar-chart example ignores fillOpacity test

### ISSUE THREAD

**Issue by nyurik** [vega/vega#901]
https://vega.github.io/editor/#/examples/vega/bar-chart -- deleting `{"test": "datum === tooltip", "value": 0},`  seems to do nothing.  Is it needed/used?

**Comment by jheer** [comment]
There is a single text element on the page. This line hides it by changing its opacity; this is in addition to the text getting set to an empty string when `tooltip.amount` evaluates to `undefined`. It is not strictly necessary, but is included to serve as an example of an encoding with a production rule.

**Comment by jheer** [comment]
Looks like the issues tab was not available previously, sorry! I enabled it so you can submit issues for the editor here: https://github.com/vega/editor/issues

**Comment by nyurik** [comment]
@jheer thanks for the explanation.  When playing with examples, I usually delete/modify portions of the spec to see what changes it makes to the result. When deleting the line didn't make any changes, it wasn't clear why its needed.  Would it make sense to modify this example somehow to make it clearer?  In Vega2, I usually created a source with one entity, and used it in a mark with a filter - if filter passed, the singleton (e.g. text) mark would be drawn, otherwise it wouldn't even try to draw it.

**Comment by vaughnkoch** [comment]
I seem to be missing something here.

Here's the original update code:
```
"update": {
  "x": {"scale": "xscale", "signal": "tooltip.category", "band": 0.5},
  "y": {"scale": "yscale", "signal": "tooltip.amount", "offset": -2},
  "text": {"signal": "tooltip.amount"},
  "fillOpacity": [
    {"test": "datum === tooltip", "value": 0},
    {"value": 1}
  ]
}
```


However, when I use this code (in the Vega Editor) for the update part of the barchart example, just to add logging and show the text mark permanently:
```
"update": {
  "x": {"scale": "xscale", "signal": "tooltip.category", "band": 0.5},
  "y": {"scale": "yscale", "signal": "tooltip.amount", "offset": -2},
  "text": {"signal": "warn(datum, datum.amount, tooltip, tooltip.amount, format(tooltip.amount, '.2f'))"},
  "fillOpacity": [
    {"value": 1}
  ]
}
```

Hovering over the 'A' rect gives me:

```
logger.js:3 WARN EXPRESSION {Symbol(vega_id): 1882} undefined {category: "A", amount: 28, Symbol(vega_id): 1872} 28 28.00
logger.js:3 WARN EXPRESSION {Symbol(vega_id): 1882} undefined {}__proto__: Object undefined NaN
```

Inspecting the text mark gives me:
 
```
$0.__data__.datum
{Symbol(vega_id): 1882}
```

Also, the docs on fillOpacity say this:

```
# https://vega.github.io/vega/docs/marks/text/
fillOpacity	  Number	The fill opacity from 0 (transparent) to 1 (opaque).
```

My understanding of the barchart example is as follows:
- There's a single text mark with vega_id=1882, which is the hover-text showing the amount.
- The mark isn't visible, (in my modified code, it shows in mine as 'NaN' at the upper left of the chart since I'm calling format(...))
- When evaluating the production rule datum === tooltip, it's comparing vega_id=1882 to whatever the vega_id of the rect is. So this will never be true. As a result, fillOpacity is always 1, meaning opaque.
- The text mark doesn't appear in non-hover contexts simply because its text value is null.
- The example's explanation seems to imply that when `datum === tooltip`, it would set fillOpacity to opaque (and thus show the text), but the value is set to 0, which from the docs should mean transparent.

Is my understanding incorrect? I would love to understand how this is supposed to work under the hood.
