### ISSUE TITLE
vertical rule to hover closest point on x axes revisited

### ISSUE THREAD

**Issue by mattijn** [vega/vega#938]
I saw in issue #799 the idea of creating _1D_ voronoi diagrames based on a second dataset using the mean values to enable a vertical rule connected to the closest point on x axes. 

I combined it using the zoom functionality and get this far:
![hover_zoom](https://user-images.githubusercontent.com/5186265/28458388-db6ea1ae-6e09-11e7-8ff4-d4f4febcdbdb.gif)

The spec for this visualization is there: https://gist.github.com/mattijn/8dafce612b9274b1ced3691bc0e2e78b

Two issues:
1. Currently the [close to] mean values are manually set in the `c` variable. No matter what I try (see data|name `voronMean`) I can't seem to compute this using an expression in combination with a mean aggregation.
2. The `y` value of the `tooltip` is now connected to the `yLocationHighligthed`, but it always stays at the same height (namely of the `c` variable`)

**Comment by jheer** [comment]
1. Why use the mean? _Any_ y-coordinate (including zero in _pixel space_) will suffice to create a 1D Voronoi diagram (the cells will have "infinite" height, but clipped to the diagram's extent).
2. The `y` value of the tooltip is constant because the `hovervoron` signal gets sets to the Voronoi cell, whose y value is always the center value. Instead, you'll want to access the (x, y) values of the actual data point -- or run the underlying (u, v) values through the appropriate scales.
