### ISSUE TITLE
axis.minExtent = 0 can be overridden by config

### ISSUE THREAD

**Issue by kanitw** [vega/vega#948]
For example, given [this spec](https://pastebin.com/xMgHwxTz), 
I somehow get an extent offset for the y-grid-axis.

![vega_editor](https://user-images.githubusercontent.com/111269/28795252-08f4da3a-75ee-11e7-8290-dbcb4359bb95.png)

However, if I set the minExtent to `1` instead of `0` or remove the `config.axis.minExtent` then the weird offset is removed.

**Comment by jheer** [comment]
I am unable to reproduce the issue. For the internal gridline y-axes I can confirm that the minExtent is correctly `0`, regardless of the config setting. So all I'm seeing is the offset due to the grid layout, not the extra spacing you are seeing here. Perhaps your local build has an outdated version of vega-parser?

(Note: Just to be comprehensive, I'll also note that the spec does not include a `minExtent: 0` for the y-axes in the row headers, so the axis titles are offset.)

**Comment by kanitw** [comment]
Thank you.  I would like to confirm that this works fine for me in `rc5`.
