### ISSUE TITLE
Top-level title incorrectly positioned with layout

### ISSUE THREAD

**Issue by kanitw** [vega/vega#960]
![vega_editor](https://user-images.githubusercontent.com/111269/28993296-d54a7906-7967-11e7-8b10-e39a7fcc6f66.png)

Spec: https://pastebin.com/NYJeSUgd

**Comment by jheer** [comment]
Thanks for reporting. Currently the title's horizontal layout is determined relative to the parent group's `width` and `height`. For the top-level specification, this defaults to the values of the `width` and `height` signals (which you've set to `200`).

Similar to `flush`/`full` bounds for grid layout, we might want to provide an option that sets the title based on the computed view bounds rather than the spec's width / height encodings.

In the meantime, other options include (1) setting the title to use `"anchor": "start"` so that the title text is left aligned (which here will line up nicely with the leftmost y-axes), or (2) using the `column-title` role in conjunction with the grid layout.

**Comment by kanitw** [comment]
(Accidentally close due to commit message in https://github.com/vega/vega-lite/commit/d7e937971dfd81880430b7eb03afdaba64df644e)  

Note that, if we want to change this in Vega anyway, I won't introduce a temporary fix in VL.
For now, we won't include `title` in VL's schema and docs for now and will ship it when it's fully ready.

**Comment by jheer** [comment]
I think you should use orient:top and anchor:start for title and do not allow other configurations for the time being.

**Comment by jheer** [comment]
Closing out this stale issue. Title subsequently added support for setting the layout `frame`.

**Comment by kanitw** [comment]
Thanks, note that I just tried and found that `frame: 
"group"` doesn't work with facet+layout as the group doesn't know its own width. 

![image](https://user-images.githubusercontent.com/111269/54092374-99e2e180-4348-11e9-94bc-2b2da2d88f78.png)

Meanwhile, setting `frame: "bounds"` is working correctly, but it doesn't look nice since it won't align with header title:

![image](https://user-images.githubusercontent.com/111269/54092393-b3842900-4348-11e9-9fb0-e6b08acf1d93.png)


I think I'll keep the default title anchor = "start" for composition operators (facet/concat/repeat) in Vega-Lite for now.
