### ISSUE TITLE
Layout bounds calculation seems to ignore axis labels 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#968]
Spec: https://pastebin.com/6DN3Skht

![image](https://user-images.githubusercontent.com/111269/29189618-0f22b07c-7dcc-11e7-91c5-6a64654d78a1.png)

(I use `layout: "full"` already)

Related Feature: I remember you talk about the axis property to make left-most and right-most labels align left and align right. This may help us avoid running into this issue.

**Comment by jheer** [comment]
Thanks for documenting the issue. This arrangement arises because the grid layout bounds are determined by the content cells only. The header and footer cells to do not current participate in the bounds determination. So this is not (technically speaking) a bug. If you think the design should be amended, please file a feature request issue on the [vega-view-transforms](https://github.com/vega/vega-view-transforms) repo!
