### ISSUE TITLE
No tick / label when continuous scale has only one unique value in the domain

### ISSUE THREAD

**Issue by kanitw** [vega/vega#969]
(This might be a D3 bug, but I'm not sure.)

In this spec, https://pastebin.com/zi242PT9, we only have 2016 for the time scale. 

![image](https://user-images.githubusercontent.com/111269/29189851-e1fd6b4a-7dcc-11e7-84f2-0e0952ae8fbe.png)

Similarly, same thing happens for a quantitative scale if I set `zero` to `false`. 

https://pastebin.com/BL35frxW

![image](https://user-images.githubusercontent.com/111269/29189978-539b6bee-7dcd-11e7-95d3-75a1dadcda5b.png)

**Comment by jheer** [comment]
When the scale domain has no span, no ticks are generated. This is standard D3 behavior.

```js
d3.scaleLinear().domain([1,1]).range([0,100]).ticks() // []
```

I think what we need is a more general solution for determining the domain min/max when there is only a single value in a data set.

**Comment by kanitw** [comment]
>  a more general solution for determining the domain min/max when there is only a single value in a data set.

Where should this be handled?  It seems like this logic should still be in Vega's scale domain node?  If so, we should leave this open?

**Comment by jheer** [comment]
How is Vega supposed to know what a reasonable extension of the domain should be? Vega's responsibility is to generate the domain based either on the data provided or specific values. If only a single value is provided, the domain is under-determined and it is not clear what value of padding is sensible. 1? 0.0000001? 1e6?

I'd be happy to hear sensible proposals, but I'm not (yet) convinced that it's Vega's job to provide some kind of automagically produced domain here. Or, if you think the underlying scales should behave differently (e.g., when the domain span is zero, generate a single tick and place items at the midpoint of the range rather than the minimum point), file an issue with D3.

**Comment by kanitw** [comment]
>  if you think the underlying scales should behave differently (e.g., when the domain span is zero, generate a single tick and place items at the midpoint of the range rather than the minimum point), file an issue with D3.

Yeah, that's what Tableau does.  I filed https://github.com/d3/d3-scale/issues/113.
