### ISSUE TITLE
Question: Implementing a binary tree as a force directed graph

### ISSUE THREAD

**Issue by davidhousedev** [vega/vega#996]
Hello,
I am new to Vega and data visualization in general. I hope that you all can assist me with what may be a simple question.
I am using the [Force Directed Layout example](https://vega.github.io/editor/#/examples/vega/force-directed-layout) to represent a binary tree. However, I cannot figure out how to make higher value nodes appear above others.

What is a good method for establishing different center points for a force directed layout, based on data node values?

Any assistance would be appreciated!

**Comment by jheer** [comment]
Hi @davidhousedev! You might use the [`y` force](https://vega.github.io/vega/docs/transforms/force/#y) to attract nodes at a particular depth level to a specific on screen point. For this to work, your tree nodes will need to have an attribute indicating their depth.

Alternatively, you might try using the [tree layout](https://vega.github.io/vega/docs/transforms/tree/) to position the nodes instead.

Finally, rather than posting a GitHub issue, questions like these are typically better suited to the [vega-js Google Group](https://groups.google.com/forum/#!forum/vega-js).
